- documentation/milestones/milestone_dependency_diagram.mmd
Improves the logic of the legend, which now reads from "pre-planning" towards execution.
> Updating legend order

- documentation/milestones/milestone_template.md
Proposes some updates to the milestone template.
Fixes: #25 
- Replaces Delivery section with summary table at the top of the template
- Adds a User Stories section
- Adds some helper place holder text to guide how template is filled out
- Marks each section as required or optional
- Does the current labeling of required/optional align with your expectations?
- Is there any additional helper text or guidance we want to provide within the sections?
> [ISSUE 25] Milestone template updates

- documentation/decisions/adr/0005-backend-tooling.md
- documentation/decisions/adr/000n-backend-tooling.md
Resolves #101 
Describes decision for back-end code quality tooling. Assumes we are using the Flask template repository, however, set of tooling is extensible to any solution we choose.
> [ISSUE 101] ADR for back-end code quality tools

- documentation/decisions/adr/0001-recording-architecture-decisions.md
- documentation/decisions/adr/0002-ci-cd-task-runner.md
- documentation/decisions/adr/0004-api-framework.md
- documentation/decisions/adr/0006-db-choices.md
- documentation/decisions/adr/0007-front-end-language.md
Fixes #240
Update existing ADRs to be correct and uniform for the status.
> [Issue 240] Update ADRs to use correct status

- documentation/goals.md
Work in progress, not yet ready for review.
> (WIP) Goals

- documentation/decisions/adr/0011-frontend-tooling.md
- documentation/decisions/adr/00NN-frontend-testing.md
- documentation/decisions/template.md
Fixes #183 
- ADR for tooling around front-end testing and coverage.
- Small changes to ADR template to include issue number in url and change pro -> pros
> [ISSUE 183] Front-end Testing Framework and Coverage

- .grype.yml
- frontend/Dockerfile
- frontend/Makefile
- frontend/next-i18next.config.js
Fixes #394
Each commit below has a link that corresponds to a change being pulled in from the next.js template. Most importantly, health check needed `wget`!
💪
> [ISSUE 394] Failing health check for next.js app

- frontend/public/locales/en/common.json
- frontend/src/components/FullWidthAlert.tsx
- frontend/src/components/FundingContent.tsx
- frontend/src/components/GoalContent.tsx
- frontend/src/components/Hero.tsx
- frontend/src/components/WtGIContent.tsx
- frontend/src/pages/index.tsx
- frontend/src/styles/_uswds-theme-custom-styles.scss
- frontend/src/styles/_uswds-theme.scss
Fixes #404
Lots of little changes here, but mostly visual. I'll leave inline comments in the PR explaining… 
> [Issue 404] Design pass at styles

- CODE_OF_CONDUCT.md
removed the placeholder for Contributor Covenant link in the last sentence of the document. this was just a carryover from the planning document.
Fixes #{ISSUE}
> remove typo in the last sentence

- frontend/src/components/Footer.tsx
Fixes #448
- Make the footer layout look nicer on various small screen sizes 
- Make the logo larger so it's legible
- Remove the repetitive text next to the logo (the logo's alt text is enough for accessibility) 
- Make the footer columns more dynamic so the Social links don't awkwardly wrap on small screens
- Reorders the social links in a more logical order (maybe, to me at least)
Be sure to resize the window an look at the footer at every possible size as it changes
> update footer layout

- CODE_OF_CONDUCT.md
- COMMUNITY_GUIDELINES.md
Fixes #419
Add CODE_OF_CONDUCT.md and initial COMMUNITY_GUIDELINES.md
The community guidelines will evolve as we ramp up.
> [Issue 419] Add Code of Conduct and Community Guidelines

- documentation/decisions/2023-08-21-branch-conv-release-workflow.md
- documentation/decisions/adr/2023-08-21-branch-conv-release-workflow.md
Fixes #185 
Adds ADR described in #185 
This merges #185 and #112 .
> [Issue 185] Branch Convention and Release Workflow ADR

- frontend/src/constants/environments.ts
- frontend/src/pages/_app.tsx
Fixes #482 
Stop using ga environments
> [ Issue 482 ] Simplify GA Tag

- documentation/decisions/adr/2023-09-22-hhs-comms-site.md
Outlines options for creating a communications site for information about the Simpler Grants initiative that is tailored to HHS staff.
Fixes #498 
Added the [`decisions/adr/2023-09-22-hhs-comms-site.md`](https://github.com/HHS/grants-equity/blob/issue-498-adr-hhs-comms-site/documentation/decisions/adr/2023-09-22-hhs-comms-site.md) with the options and outcome for this decision.
It may be easier to review the [rendered version of this document](https://github.com/HHS/grants-equity/blob/issue-498-adr-hhs-comms-site/documentation/decisions/adr/2023-09-22-hhs-c …
> [Issue 498] ADR HHS comms site

- documentation/goals.md
No issue number, updates goals.
> Updating goals based on internal review

- api/Dockerfile
- docker-compose.yml
- frontend/Dockerfile
- infra/modules/service/main.tf
Fixes #591 
update health check to use curl
> [Issue 591 healthcheck

- documentation/decisions/adr/2023-10-16-Listserv
> [Issue 378] ADR 2023-10-16-Listserv

- infra/modules/database/networking.tf
- infra/networks/main.tf
Fixes #505 
- Add SecureString SSM parameters for peering owner and vpc ids
- Terraformed VPC peering connection for DMS
- Route table entry for peering connection
> [ISSUE 505] Setup VPC Peering for DMS

- frontend/package-lock.json
Fixes #754
Update sharp package on the frontend to pass anchore scans
> [Issue 754] Update Sharp

- documentation/decisions/adr/2023-10-16-email-marketing.md
made some typo updates
Fixes #{590}
> [Issue #590] Email Marketing ADR

- documentation/decisions/adr/2023-10-16-email-marketing.md
Updated the ADR based on information from Sammy and Andy when implementing the newsletter on simpler.grants.gov
> Update Email Marketing ADR

- frontend/public/locales/en/common.json
Partially addresses #888
- Update the content to match newest approved Figma
> [Issue 888] Update mlietsone 1 intro text

- frontend/public/locales/en/common.json
- Make links bold (to match Figma)
> [Issue 888] Make CTA links bold on process page

- frontend/public/locales/en/common.json
- Update the intro p
- Update the "For applicants" p
- Update the "For grantmakers" p
This change updates the site to match the latest approved content in Figma.
> [Issue 888] Update "The goal" content

- frontend/src/constants/routes.ts
- frontend/src/pages/content/ProcessMilestones.tsx
Fixes #910
- Link to each milestone 30K issue (instead of the GH Project)
> [Issue 910] Link milestone buttons to 30K issues

- frontend/public/locales/en/common.json
Fixes #929
* Change "awards" to "grants" per [Slack thread](https://betagrantsgov.slack.com/archives/C05TGEL3C6Q/p1702591002925099?thread_ts=1702048316.112959&cid=C05TGEL3C6Q)
* Also nixes a stray unusual new line character (prob copy/pasted from Figma)
> [Issue 929] Change awards to grants

- frontend/src/constants/routes.ts
Fixes #915 
Update RSS link in the footer
> [Issue 915] Update RSS Footer Link

- frontend/public/locales/en/common.json
> HOTFIX: fix typo

- README.md
Fixes #819 
- Add a period missing between sentences
This is a fast follow PR for #932 which had the typo
> [Issue 819] Add missing period

- CONTRIBUTING.md
- documentation/README.md
- documentation/decisions/adr/2023-08-01-analytics-platform.md
- documentation/decisions/adr/2023-10-16-email-marketing.md
- documentation/deliverables/individual_deliverables/search_mvp.md
- documentation/deliverables/individual_deliverables/static_site_public_launch_infrastructure_content.md
- documentation/goals.md
Removes old language from docs to align with edits suggested by HHS leadership
- Fixes references to previous repo name
- Fixes references to outdated phrasing
- Fixes end of line space
We may want to set up a GitHub action that runs `pre-commit run --all` to enforce pre-commit hooks if folks haven't installed it locally.
> [Issue 819] Remove old language from docs

- documentation/decisions/adr/2023-12-20-contact-us-email.md
Fixes #682 
This documents the decision already made to use simpler@grants.gov for the "Contact Us" call-to-action.
> [Issue 682] Contact Us ADR

- DEVELOPMENT.md
Fixes #867 
Start the release versioning format with `-1` to make the versioning clearer.
> [Issue 867] Update Calver format

- documentation/api/development.md
Fixes https://github.com/HHS/simpler-grants-gov/issues/1011
1. adds instructions about copying the `frontend/.env.local` file
2. modifies the instructs to be run from the top level directory
Nava slack: https://nava.slack.com/archives/C05GQF7DP33/p1704746497341639
> Small fixes to the startup docs

- .github/CODEOWNERS
- MAINTAINERS.md
Fixes https://github.com/HHS/simpler-grants-gov/issues/870
> [Issue 870] Adds myself to codeowners + MAINTAINERS.md

- .github/labeler.yml
- .github/renovate.json
- .github/workflows/labeler.yml
Fixes #748
- Adding labeler action, inspired by https://github.com/navapbc/archive-massgov-pfml/blob/main/.github/labeler.yml to improve PR labeling not only for renovate PRs
- Update Renovate PR reviewers
- Update Renovate schedule to bi-weekly
> [Issue 748] PR Labeling and Renovate Updates

- MAINTAINERS.md
updated product and delivery
Fixes #1007 
> [Issue 1007] Update MAINTAINERS.md

- infra/api/service/outputs.tf
- infra/frontend/service/outputs.tf
- infra/modules/service/variables.tf
A couple small changes that were suggested in the platform.
> [Issue 960 fast follow] PR cleanup

- infra/networks/subnet-backfill.tf
Fixes https://github.com/HHS/simpler-grants-gov/issues/1061
I made the mistake of deploying the NAT gateways into the private subnets. The private subnets don't have internet access, and so the NAT gateways didn't have internet access, and so requests to external services (like Sendy) started failing.
Deploy the NAT gateways into the public subnets. The way it works is that there's a private subnet, with a route table pointing at the NAT gateway, which itself should be in the public subnet. That's how all the private subnets get internet access.
https://docs.aws.amazon.com/vpc/latest/userguide/nat-gateway-troubleshooting.html#nat-gateway-troubleshooting-no-internet-connection
> [Issue 1061] Move NAT Gateways go into the public subnets

- infra/modules/database/networking.tf
- infra/modules/dms-networking/security.tf
Part of  #1038 
* update the security group for the replication instance in us-east-1
> [DMS] Update security groups via terraform

- infra/modules/database/networking.tf
> [DMS] Update Security group rule ID 

- documentation/decisions/infra/0010-production-networking-long-term-state.md
> [Issue 1051] Production Networking ADR

- DEVELOPMENT.md
Fixes https://github.com/HHS/simpler-grants-gov/issues/1056
> [Issue 1056] Adds step by step release instructions

- infra/modules/service/waf.tf
Fixes #887 
* Add WAF and rules
* Add logging groups for cloudwatch
> Implement WAF for the Simpler assets in the AWS environment.
* This is currently in the console
> [Issue 887] Implement WAF

- frontend/public/robots.txt
- frontend/src/pages/_app.tsx
Fixes #975 
Add a robots.txt file to prevent web crawlers from crawling certain routes.
Adding GoogleTagManager component as done puts the tag in the head instead of the body of the html
While these are good things to implement, I'm not 100% sure this will remove them from the `Reports/Raise Brand Aawreness/Pages and Screens` and `Reports/Examine User Behavior/Pages and Screens`.
> [Issue 975] Google Analytics nextjs build urls

- MAINTAINERS.md
Add Brett Rosenblatt
Fixes #1079
> [Issue 1079] Add Brett Rosenblatt to MAINTAINERS.md 

- MAINTAINERS.md
> [Issue 1188] Add Brandon Tabaska to MAINTAINERS.md 

- frontend/src/api/mock/APIMockResponse.json
Fixes #1297 
- Add mock data from API factories to create random data 
- Will be used for some of the upcoming search UI when trying to simulate mock data
- Also can be used for tests
> [Issue 1297] Add mock API response to frontend

- infra/modules/network/main.tf
Fixes #1356
Creates a set of "security subnets" by MicroHealth's request
I deployed these changes to `dev` to test
> [Issue #1356] Create more subnets for MicroHealth

- frontend/Makefile
Fixes #1359 
add frontend make target to reinstall modules
> [Issue #1359]: add frontend reinstall-deps make command

- infra/modules/network/main.tf
Fixes #1356
They are interfering with deploys: https://github.com/HHS/simpler-grants-gov/actions/runs/8090834113/job/22109074109
> [Issue #1356] Rename MicroHealth's subnets

- api/src/app.py
Fixes #1258
Fix format issue on #1346
> [Issue 1258] Fix format for local lib update

- frontend/src/app/search/SearchForm.tsx
- frontend/src/app/search/_search.scss
- frontend/src/app/search/loading.tsx
- frontend/src/components/search/SearchBar.tsx
- frontend/src/components/search/SearchOpportunityStatus.tsx
- frontend/src/components/search/SearchPagination.tsx
- frontend/src/components/search/SearchResultsHeader.tsx
- frontend/src/components/search/SearchResultsList.tsx
Fixes #1296 
- Setup basic search layout 
- Based on v7 figma: https://www.figma.com/file/Zm7oIeBpwjrsXcmjV3K7HR/Search?type=design&node-id=4977-1764&mode=design&t=o0rDewrSfyG5Nlek-0
- Still need to get the input and submit button to span the entire width
random page size :
https://github.com/HHS/simpler-grants-gov/assets/93001277/c430af0d-bd11-4a94-8bad-6f065cc37a3e
> [Issue #1296]: setup uswds layout

- frontend/src/app/api/mock/APIMockResponse.json
- frontend/src/types/searchTypes.ts
Fixes #1449 
- New mock file generated and added
- Update typescript search types to reflect new structure
- The API updated the data on their v0.1 search opportunities endpoint
> [Issue #1449]: Refresh api mock response and search types

- frontend/src/app/search/SearchForm.tsx
- frontend/src/components/search/SearchBar.tsx
- frontend/src/components/search/SearchCallToAction.tsx
- frontend/src/components/search/SearchResultsHeader.tsx
- frontend/src/components/search/SearchResultsListItem.tsx
Fixes #1545 
Update the page layout of Search to match the Figma design: 
- Add missing "Search terms" label + help text 
- Position sorting select top-right, next to count
- Fix indentation of breadcrumbs
- Match CTA font
- Adjust spacing between items
- Right-align the award meta
| Before | After | 
| --- | --- | 
| ![image](https://github.com/HHS/simpler-grants-gov/assets/409279/e55eaf64-a60f-4d9d-9416-9799baabff16) | ![image](https://github.com/HHS/simpler-grants-gov/assets/409279/39db2218-cbd7-4c1c-8098-579b5d45a751) |
> [Issue #1545] Layout improvements

- MAINTAINERS.md
Adding Ebuwa Evbuoma-Fike to Maintainers.md
Fixes #1580
> Added Ebuwa Evbuoma-Fike to the maintainers.md.
> No additional instructions.
> No additional information.
> Update MAINTAINERS.md with Ebuwa Evbuoma-Fike

- frontend/src/components/search/SearchFilterAccordion/SearchFilterSection/SectionLinkLabel.tsx
- frontend/src/components/search/SearchPagination.tsx
- frontend/src/components/search/SearchSortBy.tsx
- frontend/tests/components/search/SearchBar.test.tsx
- frontend/tests/components/search/SearchFilterAccordion/SearchFilterAccordion.test.tsx
- frontend/tests/components/search/SearchFilterAccordion/SearchFilterCheckbox.test.tsx
- frontend/tests/components/search/SearchFilterAccordion/SearchFilterSection/SearchFilterSection.test.tsx
- frontend/tests/components/search/SearchFilterAccordion/SearchFilterSection/SectionLinkCount.test.tsx
- frontend/tests/components/search/SearchFilterAccordion/SearchFilterSection/SectionLinkLabel.test.tsx
- frontend/tests/components/search/SearchFilterAccordion/SearchFilterToggleAll.test.tsx
- frontend/tests/components/search/SearchPagination.test.tsx
- frontend/tests/components/search/SearchResultsHeader.test.tsx
- frontend/tests/components/search/SearchResultsListItem.test.tsx
- frontend/tests/components/search/SearchSortBy.test.tsx
Fixes #1471
- Tests for most of the search components 
- `jest-axe` tests uncovered some small issues that required updates in the source files
> [Issue #1471]: Tests for search components

- .gitignore
- .vscode/launch.json
- documentation/api/development.md
- frontend/README.md
Fixes #1272
- Commit `launch.json` file at `./.vscode` folder
- Debugging targets for both frontend Next and API 
- Update API and frontend docs
- Debugging was setup/merged with a prior PR (on the same #1272 task)
> [Issue #1272]: Commit launch.json for debugging

- MAINTAINERS.md
Correct my name spelling, added margaret, engineers, and designers
Fixes #1581 
> [Issue #1581] Update MAINTAINERS.md

- README.md
Updated the README.md to add a link to the wiki
Fixes #1702
> Added a short blurb to the readme with a link to the wiki
> [Issue# 1702]: Update README.md to add link to wiki

- frontend/public/locales/en/common.json
- frontend/src/constants/routes.ts
- frontend/src/pages/content/ProcessInvolved.tsx
Fixes #{1678}
> Added a link with some copy to ProcessInvolved sub-page
> Small link change.
> [Issue# 1678]: Added Wiki link to Process Page on Static Site

- .github/ISSUE_TEMPLATE/internal_30k.md
Updates the issue template for 30k deliverables
Fixes #1675 
- Removed all existing sections except for "Description"
- Adds "Key links" section
Reviewers can test out the new template using [my demo project](https://github.com/widal001/project-demo/issues/new/choose).
The resulting ticket creation page should look like this:
> [Issue #1675] Updates 30k issue template

- .github/actions/configure-aws-credentials/action.yml
- .github/workflows/build-and-publish.yml
Fixes #{ISSUE}
Add `TF_LOG` to the build and publish workflow step thats failing `Configure AWS credentials`
> Turn on TF Logging

- frontend/src/components/AppLayout.tsx
- frontend/src/components/Header.tsx
- frontend/src/components/Layout.tsx
- frontend/src/pages/_app.tsx
- frontend/tests/components/Layout.test.tsx
Fixes #1664 
- Add search nav link behind a feature flag
https://github.com/HHS/simpler-grants-gov/assets/93001277/cad8e445-15ae-43c4-bd2c-117a11139799
> [Issue #1664]: Add a search nav link behind feature flag

- infra/modules/service/s3.tf
> [Issue #1659] updates s3 permissions

- infra/api/app-config/dev.tf
- infra/api/app-config/prod.tf
- infra/api/app-config/staging.tf
Fixes https://github.com/HHS/simpler-grants-gov/issues/1805
> [Issue #1805] Doubles DB scaling (again)

- infra/api/app-config/dev.tf
- infra/api/app-config/prod.tf
- infra/api/app-config/staging.tf
Fixes https://github.com/HHS/simpler-grants-gov/issues/1805
> [Issue #1805] 4x DB scaling 

- .github/workflows/cd-frontend-infra.yml
Fixes #1288, follows up on https://github.com/HHS/simpler-grants-gov/pull/1649/files#r1561288689
> [Issue #1288] Frontend doesn't have a database

- frontend/src/components/Layout.tsx
Fixes #1855
Fix nav menu in mobile:
> [Issue #1855 ] Fix nav menu mobile

- documentation/decisions/adr/2024-04-10-dashboard-tool.md
Fixes #1507
Updates the BI tool ADR with our recent account configuration discoveries.
> [Issue #1507] Update BI Tool ADR

- .github/workflows/cd-analytics.yml
- .github/workflows/cd-api.yml
- .github/workflows/cd-frontend.yml
Fixes #{ISSUE}
* update env logic
Deploys were resolving to `[APP] Array` instead of the actual environment which was breaking deploys
[Example](https://github.com/HHS/simpler-grants-gov/actions/runs/8913679992)
> [Patch] Update cd-* scripts to deploy staging

- infra/api/app-config/dev.tf
- infra/api/app-config/staging.tf
> [Issue #1833] Adds a 2nd database to dev and staging

- frontend/src/components/search/SearchFilterAccordion/filterJSONLists/agencyFilterList.ts
Fixes #1834 
- Fix all erroneous spacing in agency filter list
> [Issue #1834]: fix Agency filter space

- .github/workflows/vulnerability-scans.yml
- .grype.yml
Confirms that grype is scanning down to "medium" level vulnerabilities
I wasn't sure that it was already doing this, and this PR confirms that it is.
> Confirm effectiveness of vuln scans

- documentation/wiki/SUMMARY.md
- documentation/wiki/decisions/adr/2024-10-02-search-engine.md
Fixes #684
Create the ADR for OpenSearch
> [Issue #684] Initial draft of ADR for selection of OpenSearch

- .github/workflows/ci-infra.yml
- infra/modules/canary/main.tf
- infra/modules/container-image-repository/main.tf
- infra/modules/database/kms.tf
- infra/modules/database/main.tf
- infra/modules/database/role-manager.tf
- infra/modules/network/flow-logs.tf
- infra/modules/network/main.tf
- infra/modules/service/access-control.tf
- infra/modules/service/load-balancer.tf
- infra/modules/service/waf.tf
- infra/modules/terraform-backend-s3/main.tf
- Updated checkov
- Adds various TODOs and ignores to our code, in service of making checkov pass
Checkov is a terraform security linter. I'm doing this PR now for two reasons:
1. renovate bot has been pinging me non-stop with checkov update requests
2. I got some strange checkov bugs in https://github.com/HHS/simpler-grants-gov/pull/2341, so I decided it was time to update
> Updates checkov

- frontend/src/app/[locale]/layout.tsx
Fixes N/A
The favicon is not loading properly. This fixes that.
> Update [locale]/layout.tsx to restore favicon

- infra/api/service/search.tf
fast-follow to https://github.com/HHS/simpler-grants-gov/pull/2341
> fix opensearch env vars

- frontend/src/constants/routes.ts
Fixes #2343 
-Update newsletter archive url
Verify clicking the link in the footer works now.
> Fix newsletter archive URL

- frontend/Dockerfile
Attempt to manually zap esbuild since we don't need it and it's failing the security scans.
> [Unticketed] Esbuild failing scans

- infra/analytics/app-config/env-config/environment-variables.tf
- infra/analytics/app-config/env-config/outputs.tf
- infra/analytics/metabase/.terraform.lock.hcl
- infra/analytics/metabase/main.tf
- infra/analytics/metabase/prod.s3.tfbackend
- infra/analytics/metabase/secrets.tf
- infra/analytics/metabase/staging.s3.tfbackend
Relates to, but does not fully complete, https://github.com/HHS/simpler-grants-gov/issues/2391
- Configures metabase with the latest secrets management stuff.
- Adds configure for deploying metabase staging and prod. Deploys are manual, and I haven't done them just yet.
The secrets stuff is like 90% of this diff, sorry about that 🙏🏼
> [Issue #2391] More Metabases

- .github/workflows/lint-set-points-and-sprint.yml
Hot fix on relative path in `lint-sent-points-and-script.yml`
- Time to review: 1 minute
Changes the relative path to the script in the yaml file.
Unfortunately we can only check this after it's merged.
> [Issue #2479] Update `lint-set-points-and-sprint.yml`

- documentation/wiki/SUMMARY.md
- documentation/wiki/decisions/adr/2024-10-18-document-storage.md
Fixes #2277
Document our decision process for file storage for documents associated with Opportunities, NOFOs and otherwise.
> [Issue #2277] Document storage ADR

- infra/api/app-config/env-config/outputs.tf
Found this while deploying opensearch to prod
> [no ticket] fix opensearch variable typo

- infra/analytics/app-config/env-config/environment-variables.tf
Relates to "Connect to Analytics Database" in #2391
The steps described are done in dev, and still need to be done in staging / prod
> [Issue #2391] Adds documentation about connecting Metabase to Analytics DB

- infra/frontend/app-config/dev.tf
- infra/frontend/app-config/staging.tf
- infra/frontend/service/main.tf
Fixes a broken deploy: https://github.com/HHS/simpler-grants-gov/actions/runs/11633853129/job/32400072906
> [no ticket] Removes `beta.grants.gov` cert references

- .github/workflows/labeler.yml
This is currently failing a lot of CI builds
> [no ticket] update labeler action version

- infra/analytics/service/main.tf
Relates to #2665
Adds `ENVIRONMENT` env var to the analytics container
https://betagrantsgov.slack.com/archives/C05TSL64VUH/p1731362475436509
> [Issue #2665] env on analytics container

- infra/api/app-config/env-config/outputs.tf
Contributes to #2600
https://github.com/HHS/simpler-grants-gov/actions/runs/11802929736/job/32879723263#step:5:143
> [Issue #2600] fix availability zone count variable

- infra/analytics/app-config/env-config/outputs.tf
The analytics service doesn't have an analytics schema, and this seems like the fastest way to get unblocked
https://betagrantsgov.slack.com/archives/C05TSL64VUH/p1731524249617059?thread_ts=1731459618.190739&cid=C05TSL64VUH
> [no ticket] Hardcode schema name

- .github/workflows/vulnerability-scans.yml
This was always the intention here, I just forgot to adjust the condition
> [no ticket] only bother slack on failure

- infra/analytics/app-config/env-config/environment-variables.tf
Fixes #2845
Documents 2 more commands I had to run in order to get metabase working
> [Issues #2845] add metabase permissions

- infra/api/service/draft_documents.tf
https://github.com/HHS/simpler-grants-gov/actions/runs/11897878841/job/33153115195#step:5:56
> [no ticket] Update service name variable

- .github/CODEOWNERS
> [Issue #2925] Remove Max from documentation PRs

- .github/workflows/ci-cron-vulnerability-scans.yml
I forgot to uncomment this line >_>
> [no ticket] Send slack alert on vuln scan failures

- analytics/pyproject.toml
Fixes https://github.com/HHS/simpler-grants-gov/issues/2976
Followup to https://github.com/HHS/simpler-grants-gov/pull/2978
> [Issue #2976] db_migrate => migrate_database

- .github/workflows/cd-analytics-infra.yml
- .github/workflows/cd-analytics.yml
- .github/workflows/cd-api-infra.yml
- .github/workflows/cd-api.yml
- .github/workflows/cd-frontend-infra.yml
- .github/workflows/cd-frontend.yml
- .github/workflows/cd-metabase.yml
> [Issue #1930] Action Workflows ignoring environment

- frontend/src/constants/environments.ts
Fixes #{ISSUE}
After bugs were found in https://github.com/HHS/simpler-grants-gov/pull/3001, this will point all environments to GTM. GTM will handle setting GA ID based on hostname. Will clean things up later - this is being done quickly to unblock a deployment
> hardcode prod GTM id while we work out a better solution

- .grype.yml
Fixes #3015
We're running a newer than "fixed" version for these CVEs and we believe they're hitting on a false positive so we're ignoring them.
> [Issue #3015] Ignore false positive CVEs

- frontend/src/components/search/SearchFilterAccordion/SearchFilterOptions.ts
Fixes #2886
Update labels for non profit eligibility filter options for user comprehensibility
1. view the search page on this branch
2. _VERIFY_: name of non profit related eligibility filter options match the text provided in the ticket
> [Issue #2886] update non profit eligibility labels

- .github/workflows/ci-cron-vulnerability-scans.yml
The issue is visible here: https://github.com/HHS/simpler-grants-gov/actions/runs/12118942297/job/33784611951
> [no ticket] Fix cron vulnerability scans not alerting slack

- frontend/artillery-load-test.yml
> [no ticket] Puts artillery to reasonable numbers

- infra/modules/service/cdn-logs.tf
follows https://github.com/HHS/simpler-grants-gov/pull/3082
> [no ticket] Adds some checkov skips

- infra/modules/service/cdn.tf
https://github.com/HHS/simpler-grants-gov/actions/runs/12203802779/job/34047555079
> [no ticket] fix a cdn name collision between staging and dev

- infra/modules/service/main.tf
2 quick infra fixes to unblock prod deploy
I deployed this to dev already to test
> 2 service deploy fixes

- infra/frontend/service/outputs.tf
- infra/modules/service/cdn-logs.tf
- infra/modules/service/cdn.tf
- infra/modules/service/draft_documents.tf
- infra/modules/service/main.tf
- infra/modules/service/outputs.tf
> [hotfix] drafts bucket env var && cdn fixes

- frontend/src/app/[locale]/research/ResearchMethodology.tsx
Fixes #3180
Update Ethnio link on Research page
> [Issue #3810] Update ResearchMethodology.tsx for ethnio link

- api/src/adapters/aws/s3_adapter.py
Fixes #3095
Update timeout period (in seconds)
> [Issue #3095] Update presigned S3 URLs to last 2 hours

- documentation/frontend/featureFlags.md
- documentation/frontend/internationalization.md
- frontend/README.md
Fixes #2498
Bringing frontend and README docs up to date (plus a few updates for typos, formatting, etc.)
Note that internationalization file was largely copy pasted from the Nava platform
1. probably good to just load up the newly edited files and read them, rather than trying to make sense of the diff
2. _VERIFY_: all information is correct and presented in a digestable way without leaving out anything important
> [Issue #2498] update some docs

- frontend/package-lock.json
- frontend/package.json
Fixes NA
Remove deprecated i18n packages.
> [Unticketed] Update package.json to remove dep i18n

- .github/CODEOWNERS
Updates codeowners for the latest state of the world, in my professional opinion
> [no ticket] Update CODEOWNERS

- api/openapi.generated.yml
- api/src/api/opportunities_v1/opportunity_routes.py
- api/src/api/opportunities_v1/opportunity_schemas.py
- api/tests/lib/seed_agencies.py
- api/tests/src/db/models/factories.py
- frontend/src/components/search/SearchFilterAccordion/SearchFilterOptions.ts
- frontend/tests/e2e/search/search.spec.ts
Fixes #3237
Remove some Agencies that shouldn't appear in the Search UI anyway.
> [Issue #3237] Remove bad Agencies from manual list

- infra/modules/service/main.tf
See: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#attribute-reference
> [fast follow] use bucket ids

- OPERATIONS.md
> [no ticket] Update OPERATIONS.md for terraform state lock issues

- frontend/src/app/[locale]/process/ProcessIntro.tsx
- frontend/src/app/[locale]/research/ResearchImpact.tsx
- frontend/src/app/[locale]/research/ResearchIntro.tsx
- frontend/src/components/search/SearchCallToAction.tsx
- frontend/src/components/search/SearchResultsListItem.tsx
- frontend/src/styles/_uswds-theme.scss
Fixes #3347
- Swap all serif fonts for sans
> [Issue #3347] Swap all serif fonts for sans

- frontend/package-lock.json
Fixes #3395
Security update for Next.js
> [Issue #3395] Update Next to 14.22.2

- frontend/src/app/robots.ts
Fixes #2841
Flip check that was explicitly Dev to test that things were working as expected in Dev/Stage to know it'll work in Prod
> [Issue #2841] Put planned Prod test in place

- infra/api/app-config/dev.tf
- infra/api/app-config/env-config/environment-variables.tf
- infra/api/app-config/prod.tf
- infra/api/app-config/staging.tf
Fixes #3133
Added all of the env vars to connect to login.gov
Added secrets to parameter store for all envs
I've previously tested the lower env values locally
> [Issue #3133] Add auth env vars for login.gov OAuth

- infra/api/app-config/env-config/environment-variables.tf
Remove env var from definition that is defined as a secret further down
> [Unticketed] Remove extra env var that is defined as a secret

- frontend/src/styles/_uswds-theme.scss
Fixes #3397
- add theme setting for sans-serif heading fonts 
before & after:
> [Issue #3397] set all headings to sans-serif

- DEVELOPMENT.md
Unticketed
Added some relevant details to deployment directions
1. read the changes
2. _VERIFY_: they make sense, are useful, and do not divulge any sensitive information
> [Unticketed] minor additions to deployment directions

- api/src/search/backend/load_opportunities_to_index.py
- api/tests/src/search/backend/test_load_opportunities_to_index.py
Fixes [#{3497}](https://github.com/HHS/simpler-grants-gov/issues/3497)
Added Filter to only files with the allowed suffixes (case-insensitive)
Update test
> [Issue 3497] add allowed list to filter through attachments

- infra/api/app-config/env-config/environment-variables.tf
Fixes #3588 
Add env var for a New Relic license key
Also updated parameter store to have that key
Pretty simple env var update - I did verify the key I grabbed works and you can actually see some local metrics in New Relic.
> [Issue #3588] Add New Relic license key env var

- infra/analytics/service/api_analytics_bucket.tf
- infra/analytics/service/main.tf
Relates to #3160
https://github.com/HHS/simpler-grants-gov/pull/3589 was half done, this PR finishes it
I've deployed this to make sure the infra works. I tested the step function and:
> [Issue #3160] Actually fixes analytics IAM policy

- .devcontainer/devcontainer.json
Adds a devcontainer so non-devs or devs who don't want to spin up the site locally can QA frontend changes that don't require the API
> [Unticketed] Add devcontainer for frontend QA

- frontend/src/hooks/usePrevious.ts
Unticketed
Somehow merged https://github.com/HHS/simpler-grants-gov/pull/3629 with all checks passing, but TS check failed after merge. This fixes the error
> [unticketed] fix typescript error in usePrevious implementation

- frontend/package-lock.json
- frontend/package.json
Fixes #3675
Upgrades storybook from 8.4x to 8.5x. I didn't notice any changes to storybook after running this upgrade. This is just to get us on better footing as we start to use storybook more.
> [Issue #3675] Upgrade storybook

- infra/analytics/app-config/main.tf
- infra/analytics/app-config/outputs.tf
- infra/analytics/service/main.tf
I tested frontend and API in https://github.com/HHS/simpler-grants-gov/pull/3699, but not analytics
I deployed this to dev, there weren't any changes of note
> [Issue #2575] Fix analytics compatibility with platform version v0.7

- api/src/data_migration/transformation/subtask/abstract_transform_subtask.py
- api/src/data_migration/transformation/subtask/transform_opportunity_attachment.py
Adds support to batch the opportunity attachment transforms
Been hitting memory issues with the opportunity attachment transformations. Wanted a way to process fewer at a time (fetching/committing in batches). This approach sets up a way to support batching on all of our transformation work, without actually changing the other processes yet.
Effectively now each batch of opportunity attachment transforms will be:
* Fetch 100 attachments
* Transform each of those
* Commit
* Repeat up to 100 times
> [Unticketed] Add batching support for transforming attachments

- .grype.yml
- analytics/Dockerfile
- api/Dockerfile
- frontend/Dockerfile
Fixes #3855
Upgrade the debian library to get a patched version, ignore the esbuild issue for now since we don't install/call it and it's low likelihood of exploit.
> [Issue #3855] Address anchore issues

- .github/actions/configure-aws-credentials/action.yml
- .github/workflows/cd-api.yml
followup from: https://github.com/HHS/simpler-grants-gov/commit/9eca4df4f71f403c07165a5a3e71b02888daa529
> [no ticket] fix terraform deploy

- analytics/Dockerfile
- api/Dockerfile
- frontend/Dockerfile
Fixes #3907 
Force updated library version to install during Docker build
> [Issue #3907] Update affected library

- infra/analytics/app-config/dev.tf
- infra/analytics/app-config/prod.tf
- infra/analytics/app-config/staging.tf
https://betagrantsgov.slack.com/archives/C05TSL64VUH/p1739983620297659
> [no ticket] Doubles analytics memory

- api/src/data_migration/transformation/subtask/transform_opportunity_attachment.py
- api/tests/src/data_migration/transformation/subtask/test_transform_opportunity_attachment.py
Fixes #3973
Quick follow on PR to check more fields.
Test failed for other missing fields we want to guard against.
> [Issue #3973] Guard against null mime type / description / file size

- .github/CODEOWNERS
- MAINTAINERS.md
- documentation/api/development.md
Fixes #3964
Added @freddieyebra to codeowners and maintainers files. Also added note to api troubleshooting docs.
Add Freddie Yebra to codeowners and maintainers as a part of onboarding. No application/functionality changes. Also added note to api troubleshooting docs.
> [Issue #3964] Add Freddie Yebra to MAINTAINERS.md and CODEOWNERS

- infra/project-config/aws-services.tf
Fixes: https://github.com/HHS/simpler-grants-gov/actions/runs/13839161541/job/38722490822
> Adds cloudfront

- infra/project-config/aws-services.tf
> [no ticket] Adds step functions deploy permissions

- infra/analytics/app-config/outputs.tf
- infra/api/app-config/outputs.tf
https://github.com/HHS/simpler-grants-gov/actions/runs/13861984381/job/38792694212
> [no ticket] Adds some missing var outputs

- .github/workflows/ci-weekly-vulnerability-report.yml
- .github/workflows/vulnerability-scans.yml
- .grype.yml
Fixes #3946 
Need a vulnerability report that bypasses any ignored/suppressed issues so that our security posture can be reported up through HHS.
This was requested by MicroHealth, but it will also provide value to Nava by letting us know when something can be removed from the overrides as this report runs without honoring any of our overrides.
> [Issue #3946] Weekly Full Vulnerability Report

- .grype.yml
Add ignores for vulnerabilities that we just need to wait until the Debian image is updated
> [Unticketed] Add ignores for vulnerability scans

- api/openapi.generated.yml
- api/src/api/users/user_blueprint.py
- infra/api/app-config/prod.tf
- infra/api/app-config/staging.tf
Enable login.gov in staging & prod
Prod will be tested by connecting to the integration environment
> [Unticketed] Enabled login.gov in staging and prod for the API

- analytics/src/analytics/integrations/etldb/main.py
Fixes #3063 
Minor change to how acceptance criteria metric is calculated 
> [Issue 3063] acceptance criteria totals do not include acceptance metric subtotals

- infra/modules/service/load_balancer.tf
[Deploy to prod is failing](https://github.com/HHS/simpler-grants-gov/actions/runs/13951190732/job/39051564708)
> [no ticket] Updates the alb rule priority orders

- api/src/data_migration/transformation/subtask/transform_agency.py
- infra/api/app-config/env-config/environment_variables.tf
- infra/api/app-config/prod.tf
Fixes #4265 
Add more agencies that shouldn't show in the get agencies endpoint
> [Issue #4265] Expand the test agency list to account for Prod data

- infra/analytics/service/.terraform.lock.hcl
- infra/api/service/.terraform.lock.hcl
- infra/frontend/service/.terraform.lock.hcl
Fixes https://github.com/HHS/simpler-grants-gov/actions/runs/13999275498/job/39202160044
> [no ticket] Updates lockfiles

- infra/modules/service/access_control.tf
- infra/modules/service/main.tf
https://github.com/HHS/simpler-grants-gov/actions/runs/14085035330/job/39447174780
> Task status (lastStatus, stopCode, stoppedAt, stoppedReason): STOPPED	TaskFailedToStart	2025-03-26T14:00:01.111000+00:00	ResourceInitializationError: unable to pull secrets or registry auth: execution resource retrieval failed: unable to retrieve secrets from ssm: service call has been retried 1 time(s): invalid ssm parameters: /api//new-relic-license-key
> Use shared new relic key

- OPERATIONS.md
Adjusts https://github.com/HHS/simpler-grants-gov/pull/4328 slightly to document the real way I actually do it. One description of fast, another description of slow.
> [no ticket] Document how I ACTUALLY do it

- analytics/src/analytics/logs/ecs_background_task.py
Address lack of CloudWatch logs that is breaking deploy like we did to fix API deploy.
> [Unticketed] Resolve deploy issue from no Cloudwatch logs like we did on API

- infra/api/app-config/env-config/environment_variables.tf
- infra/api/app-config/prod.tf
Fixes #4263 
Get config cleaned up for enable_https set right in Prod
> [Issue #4263] Fix up enable_https

- infra/api/service/main.tf
- infra/modules/service/cdn.tf
- infra/modules/service/load_balancer.tf
- infra/modules/service/networking.tf
- infra/modules/service/variables.tf
In a manifestation of pure chaos... we were grabbing and inputting the cert twice... 
This is obviously bad, so I have resolved this situation
I probably caused this situation 😅 The curse of being solo is that its easier to make silly mistakes such as this
> [no ticket] Only pass in cert once

- infra/analytics/service/main.tf
- infra/frontend/app-config/prod.tf
- infra/frontend/service/main.tf
Same PR as
- https://github.com/HHS/simpler-grants-gov/pull/4362
- https://github.com/HHS/simpler-grants-gov/pull/4320
> [no ticket] Fix more https / cert typos

- infra/frontend/app-config/env-config/environment_variables.tf
- infra/frontend/app-config/env-config/main.tf
We want to be able to observe our application more effectively!
A description of each variable is provided as documentation links above the variable
> [no ticket] Enables a bunch of nextjs logging

- infra/api/app-config/dev.tf
- infra/api/app-config/staging.tf
Fixes #4400
Enable apply endpoints in dev/staging
It'll be a while before this is live in prod, but for testing/demoing, we'll want them in dev/staging
> [Issue #4400] Enable apply endpoints in dev/staging

- infra/api/app-config/prod.tf
Fixes #4300
Point OAuth at Prod Login.gov
> [Issue #4300] Re-enable prod Login.gov config

- infra/frontend/app-config/env-config/environment_variables.tf
- infra/frontend/app-config/env-config/main.tf
See: https://github.com/HHS/simpler-grants-gov/actions/runs/14204521926/job/39799165956
> [no ticket] Hardcode account id

- api/tests/lib/seed_local_db.py
- api/tests/src/db/models/factories.py
Create a competition in our seed script at a static ID for frontend dev of the application workflow
We can create more competitions with more variance in the future, but this'll make a competition with the same form every time.
> [Unticketed] Update seed script to create a competition for frontend devs

- api/newrelic.ini
- api/tests/src/logging/test_flask_logger.py
Disable transaction tracing locally as it might conflict with some test setup
> [Unticketed] Attempt to fix deploy problem

- api/src/form_schema/csv_to_jsonschema.py
- api/src/form_schema/dat_to_jsonschema.py
- api/src/form_schema/dat_to_jsonschema_cli.py
- api/src/form_schema/jsonschema_builder.py
- api/tests/src/form_schema/test_csv_to_jsonschema.py
- api/tests/src/form_schema/test_dat_to_jsonschema.py
Fixes #4396
Adds a new option to generate UI schema to CLI utility, down to the json schema builder.
Should this be a dict instead of a list? The example json result looks like a list.
See unit tests
> [Issue #4396] Update JSON Schema utility to also generate an UI schema ile

- frontend/Dockerfile
Install patched library
Bump library that anchore scan is catching
> [Unticketed] Address anchore scan

- infra/analytics/service/main.tf
- infra/api/service/main.tf
- infra/frontend/service/main.tf
- infra/modules/service/events_jobs.tf
- infra/modules/service/scheduled_jobs.tf
More tags help to slice the data in new relic more effectively
> [Issue #2631] Add a few more tags

- api/src/services/legacy_users/utils.py
- api/tests/src/db/models/factories.py
- api/tests/src/services/legacy_users/test_utils.py
Fixes #{[4253](https://github.com/HHS/simpler-grants-gov/issues/4253)}
Utility Added
Factories Created/Updated
Added Test
> [Issue #4253] Create a utility to fetch a legacy user from staging tables

- infra/api/app-config/env-config/scheduled_jobs.tf
I'm going to use this to determine what a failure looks like in the AWS metrics. Unfortunately it's kind of annoying figuring that out!
> [Issue #2631] Step function that fails on purpose

- analytics/src/analytics/cli.py
Fixes #4548 
Remove a logging statement that for unknown reasons throws [error in new relic](https://onenr.io/0VjYlMEPvR0)
> [Issue 4548] Remove timer logging

- infra/api/app-config/dev.tf
- infra/api/app-config/prod.tf
- infra/api/app-config/staging.tf
We have been overscaled for quite some time, and passively aware of that fact. I'm doing something about that now, to offset the cost increase of the fluent bit containers.
> [no ticket] Scale down RDS

- analytics/src/analytics/logs/app_logger.py
Adds the app_name to the analytics logs which we use when filtering in New Relic
> [Unticketed] Add app_name to all analytics logs

- api/src/app.py
> [Unticketed] Remove 5xx test

- infra/api/app-config/env-config/scheduled_jobs.tf
Makes the names more accurate to their functions
> [no ticket] Fixes Step Function Names

- api/src/form_schema/csv_to_jsonschema.py
- api/src/form_schema/field_info.py
- api/tests/src/form_schema/test_csv_to_jsonschema.py
Fixes #4564
Use field ID in our schema files for `title` attribute. 
Update tests
Modified unit tests to pass given the new schema fields.
> [Issue #4564] Modify process that turns .DAT files into JsonSchema to populate the title from the Field Label

- api/src/services/opportunities_v1/opportunity_version.py
- api/tests/src/task/opportunities/test_store_opportunity_version_task.py
Fix query to use first() to pick up the latest version if none returns None.
> [no ticket] Fix query to first or none

- .github/workflows/cd-api.yml
This will help with testing https://github.com/HHS/simpler-grants-gov/pull/4303
> [Issue #4663] Disable dev API deploys temporarily

- .github/ISSUE_TEMPLATE/config.yml
Remove the blank issue template from our repo
No longer necessary now that the bug preventing folks from opening tickets with an issue type has been resolved
> [Unticketed] Remove blank issue template

- infra/frontend/app-config/dev.tf
- infra/frontend/app-config/staging.tf
This will make our lives easier!
(3, 4) of (10)
> [Issue #3949] frontend staging / frontend dev DNS + certs

- .github/pull_request_template.md
unticketed
Updates PR template as internally discussed 
Hopefully simplifies and clarifies the template for everyone
> updates based on team discussion

- frontend/tests/components/Header.test.tsx
- frontend/tests/components/__snapshots__/Header.test.tsx.snap
- frontend/tests/hooks/useClientFetch.test.ts
- frontend/tests/hooks/useRouteChange.test.ts
- frontend/tests/services/auth/useUser.test.tsx
- frontend/tests/services/fetch/fetchers/clientUserFetcher.test.ts
Fixes #4549
Add missing tests for new behavior introduced in https://github.com/HHS/simpler-grants-gov/pull/4521
1. _VERIFY_: tests pass
> [Issue #4549] token expiration unit tests

- .github/pull_request_template.md
unticketed
fixes a typo in the pr template (introduced by me last week), and fixes up some formatting
> [unticketed] fix typo in pr template (and some formatting)

- .github/CODEOWNERS
- MAINTAINERS.md
- documentation/api/development.md
Fixes #4882 
Adding myself to the maintainers and codeowners
Fix a typo
> [Issue #4882] docs(maintainers): updating docs to add My

- analytics/src/analytics/integrations/etldb/migrations/versions/0010_add_user_saved_opportunity_and_search_tables.sql
- api/src/task/analytics/create_analytics_db_csvs.py
- api/tests/src/api/users/test_user_update_saved_search.py
- api/tests/src/task/analytics/test_create_analytics_db_csvs.py
Fixes #[4616](https://github.com/HHS/simpler-grants-gov/issues/4616) 
Added tables `user_saved_opportunity` and `user_saved_searches` to opportunity extracts for analytics
Added Test
Migration file for analytics db for both tables
> [Issue #4616] upload user saved opportunity s3 [1/3]

- documentation/frontend/authentication.md
- documentation/frontend/request-patterns.md
Fixes #4626
Docs added to cover fetch and token management patterns
1. read docs
2. _VERIFY_: docs are complete, with no errors, and make sense
> [Issue #4626] fetching and expiration docs

- frontend/src/i18n/messages/en/index.ts
- frontend/tests/components/search/SaveSearchModal.test.tsx
- frontend/tests/components/search/__snapshots__/SaveSearchModal.test.tsx.snap
- frontend/tests/components/workspace/EditSavedSearchModal.test.tsx
- frontend/tests/components/workspace/__snapshots__/EditSavedSearchModal.test.tsx.snap
Fixes #4902 
- modal copy was updated this affects the following components: 
- EditSavedSearchModal
- SaveSearchModal 
- adds snapshot test for the two components affected
> [Issue #4902] search query save modal

- .github/CODEOWNERS
So @pcraig3 get automatically requested on some types of stuff
> [no ticket] Updates codeowners to info nofos paths

- .github/workflows/ci-nofos.yml
> [Issue #4912] Actually run NOFOs tests

- .github/workflows/deploy-metabase.yml
https://github.com/HHS/simpler-grants-gov/actions/runs/14889301574
> [no ticket] Fix metabase deploy probably

- .github/workflows/cd-nofos.yml
- .github/workflows/deploy-nofos.yml
The shell of a NOFOs deploy process. Doesn't actually deploy anything yet, this PR is just a checkpoint.
> [Issues #4951] NOFOs CD

- .github/workflows/cd-nofos.yml
- .github/workflows/ci-nofos.yml
- .github/workflows/deploy-nofos.yml
Relates to #4951
In this CI run, you can see the deploy process getting as far as trying to stand up an actual service.
https://github.com/HHS/simpler-grants-gov/actions/runs/14984225470/job/42095028418?pr=5022
That means that it's getting through all the prior steps, in particular its successfully publishing a docker image!
> [Issues #4951] NOFOs CD part 2

- infra/nofos/app-config/env-config/outputs.tf
- infra/nofos/service/main.tf
Probably finishes https://github.com/HHS/simpler-grants-gov/issues/4951
Fixes some random bits here and there that were breaking the nofos terraform apply
`terraform apply` gets as far as looking for the specific image tag it needs to deploy
> [Issues #4951] NOFOs CD part 3

- infra/nofos/service/main.tf
https://stackoverflow.com/a/75349769/3055558
> [no ticket] NOFOs need to write to its filesystem

- infra/nofos/app-config/dev.tf
- infra/nofos/app-config/prod.tf
- infra/nofos/app-config/staging.tf
NOFOs doesn't need to amount of resources that grants.gov application does
> [no ticket] Scales nofos down to minimums

- infra/analytics/database/main.tf
- infra/analytics/metabase/main.tf
- infra/analytics/service/main.tf
- infra/api/database/main.tf
- infra/api/service/main.tf
- infra/frontend/service/main.tf
- infra/nofos/database/main.tf
- infra/nofos/service/main.tf
We want to be able to slice our costs in AWS by application and by team (Nava vs Bloomworks)
> [no ticket] Adds tags for cost allocation

- api/src/services/applications/submit_application.py
- api/tests/src/api/applications/test_application_routes.py
- api/tests/src/services/applications/test_submit_application.py
Fixes #4696
Respect competition closing_date and grace period when submitting an application.
Tweak existing tests, add new tests
All logic done in EST
See new tests and tweaks to existing tests.
> [Issue #4696] Enforce competition close date on application submission 

- api/src/task/notifications/closing_date_notification.py
Fixes #3920
Content on the Email notification for Upcoming due dates was improved.
Added another test to exercise logic for multiple upcoming opportunity due dates.
See [this document](https://docs.google.com/document/d/19soxXfps4VFcNUsvdo5xH_qctPTx5j5EpBJpysIq7vY/edit?tab=t.0) for specific content guidance.
These are example emails generated from inspecting the tests. 
**Subject**
```
Applications for your bookmarked funding opportunity are due soon
```
**HTML Body**
```
Applications for your bookmarked funding opportunity are due soon
<a href='https://example.gov/opportunity/ABC123' target='_blank'>Research Grant for Climate Change Studies</a>
Application due date: November 15, 2023
Please carefully review the opportunity listing for all requirements and deadlines.
<a …
```
> [Issue #3920] Email notification content for close date matches content design

- .github/ISSUE_TEMPLATE/5_internal_epic.yml
Fixes #5108
Per request, reduced number of fields in create-epic template.
> [Issue 5108] Remove fields from epic template

- frontend/src/components/opportunity/ZipDownloadButton.tsx
- frontend/src/utils/opportunity/zipDownloadUtils.ts
- frontend/src/utils/testing/fixtures.ts
- frontend/tests/api/opportunities/[opportunityId]/attachments-download/route.test.ts
- frontend/tests/components/ZipDownloadButton.test.tsx
Fixes #4784
Add better automated testing for the new Zip Download button, based on stuff that was flagged in the original PR.
> [Issue #4784] Improve tests for Zip Download

- frontend/src/constants/environments.ts
unticketed
updates env var name within the environments file to reference the correct env var for the drawer feature flag
1. _VERIFY_: dev deployment succeeds
2. _VERIFY_: drawer is not shown in deployed envs
> fix drawer env var name

- frontend/src/components/search/SearchFilterAccordion/AllOptionCheckbox.tsx
> quick fix for breaking agency search on no child options

- frontend/src/types/applicationResponseTypes.ts
- frontend/src/types/competitionsResponseTypes.ts
- frontend/src/types/opportunity/opportunityResponseTypes.ts
Adds response types recently introduced to the API.
Multiple PRs could use this groundwork first.
Tests pass.
> Update for new types

- OPERATIONS.md
Update docs with more details for adding certs to AWS
> [Issue #5620] Include more details around certificate rotations

- DEVELOPMENT.md
Just a quick update to the docs to better reflect our current process.
> [Unticketed] Update Release steps to reflect we tag through the UI and terminal would be a backup.

- OPERATIONS.md
Update docs based on our nofos process
> [Unticketed] Updates to certificates docs per nofos prod experience

- .github/workflows/ci-frontend-vulnerability-scans.yml
unticketed
1. make a change to frontend/package.json
2. push the branch
3. _VERIFY_: vulnerability scans are run in ci
> allow frontend vuln scan to pick up package.json changes

- frontend/src/components/Pill.tsx
- frontend/stories/components/Pill.stories.tsx
- frontend/tests/components/Pill.test.tsx
Fixes #4718 (partial)
Creates pill component
1st step toward building filter pill display on search results page, pill component not yet utilized within the app.
1. start storybook on this branch with `npm run storybook`
2. visit http://localhost:6006/?path=/docs/components-pill--docs
3. _VERIFY_: pill component matches designs and basic functionality required for #4718
> [Issue #4718] filter pill component

- api/src/task/notifications/opportunity_notifcation.py
- api/tests/src/task/notifications/test_opportunity_notification.py
Remove html tags from email subject line.
> [Issue #5003] Update subject line

- frontend/src/components/workspace/EditSavedSearchModal.tsx
- frontend/src/i18n/messages/en/index.ts
- frontend/tests/components/workspace/EditSavedSearchModal.test.tsx
see https://github.com/HHS/simpler-grants-gov/pull/5148
> Glenn 4899 saved query name display

- api/src/task/notifications/opportunity_notifcation.py
- api/tests/src/task/notifications/test_opportunity_notification.py
Fixes https://github.com/HHS/simpler-grants-gov/issues/5003
Update content generation for Description section per [DOC](https://docs.google.com/document/d/1ypejg8hL7uOXdrI7auwf9SWQ1Ag07o7rCjnrVCLfA-s/edit?tab=t.0#heading=h.sl8i9r9yex9j)
Add tests
First implementation.
> [Issue #5003] description fields content

- api/src/task/notifications/opportunity_notifcation.py
- api/tests/src/task/notifications/test_opportunity_notification.py
Skip opportunity_attachments change from notification
Fix opportunity_attachments content, update test
> [Issue #5003] opportuntiy_attachments skip

- api/src/form_schema/forms/README.md
- api/src/form_schema/forms/sf424.py
- api/src/form_schema/forms/sflll.py
- api/tests/lib/seed_local_db.py
- api/tests/src/form_schema/forms/test_sflll.py
Work for #5599
Setup the SFLLL form which asks questions about lobbying and is generally optional
This is the last "big" form we are expecting to need for our pilot, not as many questions as the SF424, and not as complicated as the SF424A. Really just a lot of name/address fields repeated in different ways.
Frontend is still making some adjustments for supporting some recent changes to forms, so can't test it with the UI schema quite yet.
> [Issue #5599] Create the SFLLL form

- frontend/src/components/search/Filters/FilterSearchNoResults.tsx
- frontend/src/components/search/SearchResultsTable.tsx
- frontend/tests/components/TableWithResponsiveHeader.test.tsx
- frontend/tests/components/__snapshots__/TableWithResponsiveHeader.test.tsx.snap
- frontend/tests/components/search/SearchResultsTable.test.tsx
- frontend/tests/components/search/__snapshots__/SearchResultsTable.test.tsx.snap
Work for #4940 (partial)
Adds a meaningful empty state for search results table
2. visit http://localhost:3000/search?query=asdgsdg&_ff=searchDrawerOn:true;searchTableOn:true
3. _VERIFY_: a helpful message appears rather than an empty table
> [Issue #4940] no search results state

- frontend/tests/components/__snapshots__/TableWithResponsiveHeader.test.tsx.snap
- frontend/tests/components/search/__snapshots__/SearchResultsTable.test.tsx.snap
Work for #ISSUE
https://github.com/HHS/simpler-grants-gov/pull/5660 somehow got through with broken snapshots
> update jest snapshots

- infra/modules/service/autoscaling.tf
Work for #5672
Adjust auto-scaling thresholds, Memory: 99 -> 70, CPU: 75 -> 70
> [Issue #5672] Adjust scaling limits

- analytics/Dockerfile
- api/Dockerfile
- frontend/Dockerfile
Work for #5711
Didn't actually change what we force to install, actually removed a couple older ones since we probably didn't need them anymore.
PR tests are passing
> [Issue #5711] Update package installs for vulnerabilities

- frontend/package-lock.json
Fixes #5748
Ran an `npm audit fix` to address vulnerability in form-data that's failing the scans. Only committed the changes that had to do with form-data not the other noise.
> [Issue #5748] Address form-data vulnerability

- .github/pull_request_template.md
Work for n/a
Update the PR template to include guidance for when to use "Fixes" or "Work for"
> Provide "Fixes/Work for" guidance in PR template

- api/src/services/applications/application_validation.py
- api/tests/src/services/applications/test_application_validation.py
Fixes #5771 
Adjust the logic for `is_included_in_submission` to only skip validation when we're in the submit endpoint.
This means validation will still happen on the application page, and the application form page even if the flag isn't set.
The error we add for saying the `is_included_in_submission` flag is required is only ever added during submission as well.
I made a truth table for the various scenarios we want to account for and then turned that into the `test_validate_is_included_in_submission_behavior` test.
> [Issue #5771] Only skip validation for is_included_in_submission during submit

- api/src/services/applications/get_application.py
Changes how we do the GET Application query used in most of our endpoints to be very explicit with which relationships we load.
I noticed in dev that the GET application endpoint (and others that hit this get app logic) were taking more than a second. When digging into the New Relic trace, I saw it was querying every table multiple times.
I removed the `selectinload("*")` entirely because although we can use `lazyload` to remove some relationships from this join, that wasn't quite working. For example, the application_form table has a relationship back to the application table. If we just have `*` then even if we removed the `application.competition.opportunity`, we didn't remove `application.application_forms[0].application.competition.opportunity` or other route in our relationships to …
> [Unticketed] Change the GET Application query to load explicitly

- api/src/form_schema/forms/project_abstract_summary.py
- frontend/src/components/applyForm/types.ts
- frontend/src/components/applyForm/utils.tsx
- frontend/src/components/applyForm/validate.ts
- frontend/src/components/applyForm/widgets/FieldsetWidget.tsx
- frontend/src/components/applyForm/widgets/TextAreaWidget.tsx
Work for #5702
Tweaks for project abstract form, and ability to add description text to form section
Note, PDF of form can be found here https://grants.gov/forms/form-items-description/fid/591
2. start an application as descriped in readme (https://github.com/HHS/simpler-grants-gov/blob/16f5ca621c3ce1469d0a5b250efe52d6718ae28e/frontend/src/app/%5Blocale%5D/workspace/applications/application/%5BapplicationId%5D/README.md)
3. click "Project Abstract Summary"
4. _VERIFY_: form matches requirements based on PDF
5. click save
6. _VERIFY_: proper failed validations are returned and displayed
> [Issue #5702] minor tweak to form section, add description to section display

- api/src/form_schema/forms/budget_narrative_attachment.py
Work for #5699 
Updates UI for budget narrative form
1. start a local frontend server on this branch
2. run `make volume-recreate db-seed-local populate-search-opportunities populate-search-agencies start` on /api
3. start an application as described in the readme (https://github.com/HHS/simpler-grants-gov/blob/16f5ca621c3ce1469d0a5b250efe52d6718ae28e/frontend/src/app/%5Blocale%5D/workspace/applications/application/%5BapplicationId%5D/README.md)
4. open the project narrative attachment form
5. click save
6. _VERIFY_: validation errors are returned
7. add multiple attachments
8. click save
9. _VERIFY_: it saves (validation errors are expected at this point)
10. return to the application page
11. _VERIFY_: your uploaded files appear in the attachment section
> [Issue #5699] update budget narrative form

- api/Dockerfile
Update package failing vulnerability scan
> [Unticketed] Update packages for vulnerability scans

- api/openapi.generated.yml
- api/src/api/application_alpha/application_schemas.py
- api/src/api/competition_alpha/competition_schema.py
Fixes #5140 
Add descriptions and examples for things we have built but have not had adequate time to document.
No substantive changes here other than docs.
Cleanup after we've built a bunch of stuff out quickly
Check examples / docs to ensure accuracy.
> [Issue #5140] Update the API schema for application/competition endpoints to have descriptions/examples

- infra/api/app-config/dev.tf
- infra/api/app-config/env-config/environment_variables.tf
- infra/api/app-config/prod.tf
- infra/api/app-config/staging.tf
Add relevant env vars for PDF generation 
Currently unticketed. Will close / rename this if a ticket is created.
Confirm env vars are set after TF is applied.
> [Unticketed] Add PDF Terraform env vars

- .github/CODEOWNERS
- MAINTAINERS.md
Add myself to CODEOWNERS and MAINTAINERS.md
> [Issue #6079] Add jakobpederson to CODEOWNERS and MAINTAINERS.md

- frontend/src/app/[locale]/(base)/workspace/applications/application/[applicationId]/form/[appFormId]/page.tsx
- frontend/src/app/[locale]/(base)/workspace/applications/application/[applicationId]/page.tsx
Fixes #5932 
Move bookmark alert on application pages.
1. create an application
2. see that bookmark alert is on app page and not on form pages
> [Issue #5932] Move bookmark alert

- .github/CODEOWNERS
Remove Freddie to cut down on his GitHub spam
> [Unticketed] Update CODEOWNERS

- api/src/services/pdf_generation/clients.py
- api/src/services/pdf_generation/config.py
- api/tests/src/services/pdf_generation/test_clients.py
Make javascript configurable for DocRaptor
We want to try testing enabling javascript for docraptor - made it an environment variable defaulted to false (what it already would be). Will manually override to test.
> [Unticketed] Make Javascript configurable with DocRaptor

- api/Dockerfile
Testing locally, the vulnerabilities seem to be updated from our Dockerfile, I think we just need it to rebuild, so added a helpful comment to our Dockerfile
> [Unticketed] Update vulnerabilities

- api/src/form_schema/forms/sf424.py
- api/src/form_schema/forms/sf424a.py
- api/src/services/xml_generation/constants.py
- api/src/services/xml_generation/service.py
- api/src/services/xml_generation/transformers/base_transformer.py
- api/src/services/xml_generation/value_transformers.py
- api/tests/src/services/xml_generation/test_none_handling.py
- api/tests/src/services/xml_generation/test_value_transformers.py
- api/tests/src/services/xml_generation/test_xml_generation_service.py
Work for #6155
Add value transformations - error handling by falling back if transform fails. Integrated with existing rule processing patterns
Boolean yes/no conversion
Currency formatting
String utilities (truncation, case conversion if necessary e.g. state codes, agency codes, )
This builds on the core PR by adding some extra functionality to the JSON -> XML conversion. Subsequent PRs will tackle more complex. The following PR, if deemed necessary, will include more advanced transforms and conditional logic.
See added tests.
> [Issue #6155] Add value transforms and data formatting [2/4]

- frontend/src/components/workspace/StartApplicationModal/StartApplicationDescription.tsx
> fix mailto typo on start application modal

- api/src/form_schema/forms/sflll.py
- api/tests/src/form_schema/forms/test_sflll.py
Make tier field in SFLLL never required
Double-checked the dat and XSD and it's not required regardless of other fields.
https://grants.gov/forms/form-items-description/fid/670
https://apply07.grants.gov/apply/forms/schemas/SFLLL_2_0-V2.0.xsd
> [Unticketed] Remove tier from required fields in SFLLL

- frontend/src/constants/defaultFeatureFlags.ts
Fixes / Work for unticketed
sets application / form related behavior and pages to be visible by default. Should only affect local development since this has been switched on in deployed envs already
1. run `npm run dev` on this branch
3. search for "pilot"
4. click into the opportunity detail
5. _VERIFY_: you see a button for starting an application
> switch applications on by default

- frontend/src/i18n/messages/en/index.ts
Fixes  #6429 
Updating 2 links on the developer page to newly added documentation.
> [Issue #6429] Update link on developer page to wiki

- api/.gitignore
- api/Makefile
- api/pyproject.toml
- api/tests/validate_legacy_soap_api/validate_soap_endpoints.py
Fixes #ISSUE 6360
Create prototype for testing SOAP endpoints and validating schemas
Run the same request against the proxy and the S2S API directly and confirm the responses are identical
This can potentially be done in Postman or a Script.
Documenting this can become a model for something going forward.
> [Issue #6360] Create process for testing soap endpoints

- bin/current-region
Fixes #6609 
Handle both versions of AWS CLI output, with extra ":" characters (new) or without (old)
> [Issue #6609] Handle newer AWS CLI format if it's present
