- documentation/milestones/individual_milestones/communication_platforms.md
- documentation/milestones/milestone_dependency_diagram.mmd
- documentation/milestones/milestone_short_descriptions.md
Adding some additional milestones to the planning documents.
> Milestone updates

- documentation/milestones/individual_milestones/communication_platforms.md
- documentation/milestones/milestone_template.md
Updates the Communication Platforms milestone definition. We will use this branch to document feedback and suggestions after the milestone meeting on Wednesday.
Fixes: #22 
- Finishes adding definition of done for calendar, listserv, and shared email inbox
- Finishes adding proposed metrics for calendar, listserv, and shared email inbox
- Formalizes list of options to consider for each of the tools and links to landing page for each option
- Groups the requirements, definition of done, and proposed metrics by tool
- Adds a delivery summary
> [ISSUE-22] Comms Platforms milestone

- documentation/decisions/adr/0004-api-framework.md
Resolves #28 
ADR to discuss 3 python api frameworks, as well as 2 extensions on the flask framework for consideration for the backend api.
> [Issue 28] Back End Framework ADR 

- .github/ISSUE_TEMPLATE/adr.yml
- documentation/decisions/README.md
- documentation/decisions/adr/0001-recording-architecture-decisions.md
- documentation/decisions/template.md
Updates the GitHub issue template for ADRs and outlines ADR process to make it clearer for future architecture decisions.
Fixes #145 
- Updates ADR issue template:
- Adds Approver section (to be filled out during sprint planning)
- Updates acceptance criteria in Definition of Done section
- Updates README with ADR process
- Removes the following statuses from template, since ADRs with these statuses wouldn't be merged in:
- Draft
- Proposed
- Rejected
- Test out a sample of the [new ADR issue template](https://github.com/widal001/project-demo/issues/new/cho …
> [Issue 145] Update ADR template and process

- documentation/decisions/adr/000n-design-diagramming-tool.md
Resolves #116 
This PR proposes the use of Mural for diagramming and whiteboarding. 
Thinking about this tool from a cross-discipline perspective. There's overlap with eng/product/project needs. @acouch, it'd be good to get engineering's opinion on the MermaidJS bits. @sumiat / @widal001, it's be good to get your product perspective.
> [116] ADR: Use Mural for diagramming and whiteboarding

- documentation/decisions/adr/000n-design-prototyping-tool.md
Resolves #103 
This ADR recommends the use of Figma for design prototyping.
> [103] ADR: Use Figma as design prototyping tool

- documentation/milestones/individual_milestones/api_planning.md
- documentation/milestones/individual_milestones/communication_platforms.md
- documentation/milestones/individual_milestones/frontend_planning.md
- documentation/milestones/milestone_dependency_diagram.mmd
- documentation/milestones/milestone_short_descriptions.md
Creates the Front-end Planning milestone definition.
Resolves: #32 
- Creates `documentation/milestones/individual_milestones/frontend_planning.md`
- Updates the status of `FE-Plan` in the dependency diagram
- Links milestone definition into short description doc
- Fixes issues with published milestone docs:
- Updates Comms Platform doc status to "Completed"
- Updates location for publishing API Planning metrics
> [ISSUE-32] Front-end Planning

- documentation/milestones/individual_milestones/developer_tools.md
- documentation/milestones/milestone_short_descriptions.md
Proposes the first draft of the individual milestone definition for Developer Tools.
Fixes: #20 
- Creates `docs/milestones/individual_milestones/developer_tools.md`
- Links this milestone to `docs/milestones/milestone_short_descriptions.md` under the Developer Tools section
1. Schedule a meeting to review this milestone definition
2. Document and implement feedback from the meeting
> [ISSUE-20] Developer tools milestone

- .github/workflows/ci-api.yml
- .github/workflows/ci-frontend.yml
- .github/workflows/ci-openapi.yml
Fixes #321 
Update naming of GA workflows that will be used in PR checks to be clearer.
- Smash front-end checks for linting, testing, format checking and type checking together. They were separate and doing separate `npm ci` installs for each. Extra time + making PR checks look quite cluttered. If you want to see a specific, you can click on "details" and then expand the section that you're interested in, same as when they were separated.
- Update path naming for API workflow because it was wrong and not getting run.
- Leave FE & API in naming convention for sub-categories of workflows. The reasoning is that when setting up branch protection rules, it makes it easier to find the check you're looking for since you search by sub-category. It does look a bit redundant on PRs, but doesn't …
> [ISSUE 321] Standardize Github Action workflow naming conventions

- frontend/Dockerfile
- frontend/package-lock.json
- frontend/package.json
Fixes #390
This PR fixes 2 issues:
- Installs Sharp package (and sub-dependencies) to remove error about image optimization in production using the `Image` component in next.js
- Images are cached, but we have a read only root directory for Fargate tasks that prevents next.js from writing to its desired directory. Fix that by creating it then adding the `nodejs` user as owner of that particular directory
This one is going to be tough to test individually, but I don't see any more errors in our AWS logs. The cache issue only happens in production.
Note: appears the health check endpoint is failing now and causing the task to restart repeatedly, but that's a separate issue.
> [ISSUE 390] Production Image Caching

- frontend/.gitignore
- frontend/README.md
n/a
- Extend the VSCode instructions in the `frontend/` README 
- Add VSCode to `gitignore`
As a recovering Atom user, I had a bit of trouble setting up VSCode. So I updated the instructions based on conversations w/ @daphnegold (and Nava platform engies). 
n/a
> Clarify VSCode setup options

- frontend/public/locales/en/common.json
- frontend/src/components/PageSEO.tsx
- frontend/src/pages/index.tsx
- frontend/tests/components/PageSEO.test.tsx
Fixes #397 
- Added Head to index page with title and meta description
- Added content for title and meta description to i18n
I took a guess at the content, so that'd be the most important piece to review. But changing/updating that in the future would be a 1 point ticket, so it's really not a big deal to update.
> [Issue 397] SEO title and description

- .github/workflows/build-and-publish.yml
- .github/workflows/cd-frontend.yml
- .github/workflows/ci-infra.yml
- .github/workflows/ci-vulnerability-scans.yml
- .github/workflows/database-migrations.yml
- .github/workflows/deploy.yml
- Makefile
- infra/test/infra_test.go
Fixes #406 
- Add more restrictions for `APP_NAME` in makefile
- Pass `APP_NAME` to all relevant make commands
- Create `cd-frontend.yml` that calls `deploy.yml`
Test workflow dispatch: https://github.com/HHS/grants-equity/actions/runs/5957648324
cmd: `gh workflow run cd-frontend.yml --ref daphnegold/issue-406-build-publish-fix --app-name frontend`
https://github.com/HHS/grants-equity/actions/runs/5967002978?pr=407
https://github.com/HHS/grants-equity/actions/runs/5968825293/job/16193471947?pr=407
> [ISSUE 406] Fix deploy Github Actions workflow

- frontend/public/locales/en/common.json
- frontend/src/components/Hero.tsx
- frontend/src/styles/_uswds-theme.scss
Fixes #440
- Add a button linking to this GitHub repo in the Hero component. 
per Lucas's request to make this call-to-action more prominent
> [Issue #440] add github CTA to Hero

- .github/workflows/ci-infra.yml
- .github/workflows/ci-vulnerability-scans.yml
- Makefile
- frontend/Makefile
Fixes #487
- Pass the `--cache-to` and `--cache-from` commands exclusively for GA builds. They require a different Docker driver that is set up in GA with `setup-buildx-action` but really not necessary locally. Now `make build-release` is fixed locally and for deploys again, until deploys leverage caching as well.
Out of curiosity, spent what felt like forever trying to leverage how Docker caching works locally against already-built images without having to cache the Docker layers explicitly. Meaning in GA we would only have to cache the .tar then load it for Docker daemon and then build then voila. But I *cannot* get it to work. Something is invalidating the cache, and I have reached max futzing capacity with no more ideas. Reverted back to caching layers and made it so it doesn't break …
> [ISSUE 487] Fix caching and build command

- frontend/public/locales/en/common.json
- frontend/src/components/Footer.tsx
- frontend/src/components/GoalContent.tsx
- frontend/src/components/WtGIContent.tsx
- frontend/src/constants/routes.ts
- frontend/src/pages/index.tsx
Fixes #506
- remove the NOFO content from `index` (we can deprecate/delete the `<FundingContent />` component later)
- update remaining content to not reference HHS NOFO improvement (plus a few grammar improvements) 
- add border to divide content sections (as we no longer have grey background of NOFO section)
- fix emails… 
- replace `tbd@` with a real email
- add new route for `equityingrants@hhs.gov` (footer and "get involved" sections should use diff emails) 
- refactor how emails in the routes are passed to content (probably coulda separated this into its own, but couldn't help myself when fixing `tbd`) 
- visible email address must always match the `mailto:` value
- the value can be changed in 1 place
- avoid passing emails in content strings; they don't need translation (yet?) 
- …
> [ISSUE #506] Remove NOFO content

- infra/frontend/app-config/main.tf
- infra/frontend/app-config/outputs.tf
- infra/frontend/service/main.tf
- infra/modules/service/autoscaling.tf
- infra/modules/service/variables.tf
Fixes #417 
- Add target based autoscaling triggered on CPU utilization to service module
- Enable autoscaling for frontend-dev and prod, infra provisioned
A lot of times we will see an alarm associated with the target strategy that is warning us we have low CPU utilization. AWS knows this is a thing. There's a button to "hide autoscaling alarms". These alarms are differentiated from our monitoring alarms in that they are separate from the monitoring module entirely, and provisioned along with autoscaling. Therefore these shouldn't trigger any oncall alerts or integrate with our email integration/monitoring services via sns topics.
If you want to test the autoscaling, you use something like this to slam our service with requests over an extended period of time (credit @acouch): `ab -n …
> [ISSUE 417] Add Autoscaling for Static site

- infra/frontend/service/main.tf
- infra/modules/service/load-balancer.tf
- infra/modules/service/networking.tf
- infra/modules/service/variables.tf
- infra/networks/main.tf
Fixes #534 
- Load cert to load balancer for frontend by domain
- Create HTTPs listener and forward/redirect rules
- Security group ingress for port 443
- We will need to apply account changes first to get acm imported via the networks/main.tf module.
- We need to make sure the backend won't break without a cert
- We need to make sure to redirect via https if the cert exists
> [Issue 534] Set up HTTPS for beta

- documentation/milestones/individual_milestones/api_planning.md
- documentation/milestones/individual_milestones/communication_platforms.md
- documentation/milestones/individual_milestones/db_planning.md
- documentation/milestones/individual_milestones/developer_tools.md
- documentation/milestones/individual_milestones/frontend_planning.md
- documentation/milestones/individual_milestones/get_opportunities.md
- documentation/milestones/individual_milestones/static_site.md
- documentation/milestones/milestone_template.md
Updates milestone docs to remove NOFO content and target release date attribute
Fixes #514 
- Removes references to NOFO transformation workstream from milestone doc
- Removes "target release date" row from milestone doc metadata
- Updates template to include metadata that is consistent across milestone docs
It may be easier to view the rendered versions of the docs to review
> [Issue 514] Remove NOFO content from static site milestone

- Makefile
Fixes #565
Use tfvars file for now
The template moved away from tfvars files, we incorporated some of those changes but not all.
Short term, use tfvars file to unbreak deployment. Long term, pull in the rest of the changes and make sure they work with our new domain environment variable.
Already discussed with @acouch and James Bursa at Nava.
> [Issue 565] Update Makefile for use tfvars for apply

- frontend/Dockerfile
Fixes #573
The PR #573 upgraded next, however the static site won't build in the release target because of the issue described here: https://github.com/i18next/next-i18next/issues/2214 . This downgrades next from `13.5.4` to `13.5.3` to fix the issue.
This also temporarily white-lists `postcss`, which is fixed in next `13.5.4` by upgrading postcss.
> [Issue 573] Update next to fix build and temporarily ignore postcss vuln

- frontend/Dockerfile
Fixes #588 
We updated the docker image and node version because of vulnerabilities, but now the health checks are failing. 
Maybe this can bring things back online.
* Keep node version 20?
* Move from alpine to bullseye slim
If vulnerability tests and terratest passes, the only way to verify is by deploying to ecs.
> revert dockerfile

- api/Dockerfile
- docker-compose.yml
- frontend/Dockerfile
- infra/modules/service/main.tf
This reverts commit 8bb0c9236e2ccc65c284628b6686a22f7f22e60a.
Relates to #591
Rolls back changes for health check.
> Revert "[Issue 591 healthcheck (#592)"

- .github/workflows/ci-infra-service-api.yml
- .github/workflows/ci-infra-service-frontend.yml
- .github/workflows/infra-service.yml
- .github/workflows/vulnerability-scans.yml
Fixes #586
- Move jobs for infra service into their own callable workflow
- Create ci-infra-service-frontend.yml and ci-infra-service-api.yml to run checks for frontend and api respectively
We were only running infra checks for frontend, let's run them for api too.
> [ISSUE 586] Fix ci-infra-service.yml to work for api too, not just frontend

- api/Makefile
- api/bin/wait-for-local-db.sh
- api/local.env
- docker-compose.yml
Fixes #617
Renamed the docker container for the app and DB to make them less generic.
Nothing too fancy, just updated the names and where we reference them.
Verified that everything works locally (`make init format lint test`) and the API comes up and is usable (`make run-logs` go to  http://localhost:8080/docs ).
If you check this out, I suggest you do `make clean-volumes` to delete any existing DB volume as it was renamed.
> [Issue 617] Rename app and db in docker-compose

- api/src/db/migrations/versions/2023_08_01_base_migration.py
- api/src/db/migrations/versions/2023_08_10_default_table_privileges.py
Fixes https://github.com/HHS/simpler-grants-gov/actions/runs/6736356093/job/18311731606
Adjusted the alembic migrations to reference a `9fe657340f70` revision that was deleted in a prior PR. I had mistakenly assumed the migrations were not already running and it was safe to delete them. This adds a dummy migration so that we can safely run the migrations again as it will pick up from this dummy migration.
Alembic migrations are pretty simple, a table exists in the DB called `alembic_version` which has a single column+row with the current migration ID. Alembic reads all the migration files in the migration folder and finds that ID, then runs all the migrations after it. Right now it is seeing `9fe657340f70` in the DB, but that doesn't exist, so by creating a migration file with that ID, …
> Adjust DB migrations as deleted ones ran already and need to be referenced

- .grype.yml
- api/openapi.generated.yml
- api/src/app.py
Fixes #623
Updated the contact info on our openapi docs
Also a minor update for the openapi version + how the openapi json formats while we're modifying this
Contact info just links to the simpler website
Updating the version of openapi adjusts how a few things generate in openapi, but nothing that we need to worry about with what we have at the moment (better to do before we start setting up more). And the `compact = False` option just makes it so if you click the openapi.json file it is nicely formatted.
What the contact info looks like
What the OpenAPI file looks like now:
> [Issue 623] Update contact info on openapi

- frontend/src/pages/health.tsx
- frontend/src/pages/index.tsx
Fixes #530
Depends on: #569, #583 
1. Upgrade to latest version of next and i18next
2. Move to `getStaticProps` for SSG
This PR updates the static site to be much more performant. The [most recent version of Next](https://nextjs.org/blog/next-13-5) includes a number of performance improvements.
Moving to [Static Site Generation](https://nextjs.org/docs/pages/building-your-application/rendering/static-site-generation) will also dramatically improve the number of requests the server can handle. It also provides the correct HTML headers for adding a CDN (#555).
When running `npm run build` you will now get the following:
```bash
λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
● …
```
> [Issue 530] Move Next to SSG

- frontend/src/components/FullWidthAlert.tsx
Fixes #496
Add `tablet:position-sticky top-0 z-top` to `FullWidthAlert` component.
> [Issue 496] make FullWidthAlert sticky

- api/openapi.generated.yml
- api/src/api/opportunities/opportunity_routes.py
- api/src/api/route_utils.py
- api/src/services/opportunities/get_opportunities.py
- api/tests/src/route/test_opportunity_route.py
Fixes #644
Added a GET /opportunity/<opportunity_id> endpoint
Pretty basic endpoint, re-uses the opportunity response + db models we already have.
Running locally:
> [Issue 644] Add a GET /opportunity/:opportunity-id endpoint

- .grype.yml
- .trivyignore
Adds vulnerabilities to ignore list
Several Postgres vulnerabilities in our Debian image (which the Python image pulls from). I believe these are fixed in Debian, but we need to wait for the Debian Docker image to be rebuilt (last rebuild at end of October) and they avoid rebuilding frequently, likely will be fixed in a few weeks.
https://github.com/HHS/simpler-grants-gov/actions/runs/6861302163/job/18656801836?pr=688
https://github.com/HHS/simpler-grants-gov/actions/runs/6867481396/job/18675968227?pr=690
> Add vulnerabilities to ignore file

- documentation/infra/set-up-monitoring-alerts.md
- infra/api/service/main.tf
- infra/frontend/service/main.tf
Fixes #484
- Add email monitoring alerts for api and frontend (both dev and prod)
I don't see a way currently to add email alerts to a service and disable them by environment. I can add that if we want it without a lot of trouble? Let me know.
> [ISSUE 484] Configure Alerts for Static Site Launch

- analytics/README.md
- analytics/src/analytics/datasets/deliverable_tasks.py
- analytics/src/analytics/datasets/sprint_board.py
- analytics/src/analytics/metrics/base.py
- analytics/src/analytics/metrics/burndown.py
- analytics/src/analytics/metrics/percent_complete.py
- analytics/tests/conftest.py
- analytics/tests/datasets/test_sprint_board.py
- analytics/tests/metrics/test_burndown.py
Adds support for calculating sprint burndown using `@current` instead of specifying the name of a sprint. This allows us to set a schedule-based GitHub action that will calculate sprint burndown dynamically.
Fixes #740 
- Adds two new methods to `SprintBoard`
- `SprintBoard.get_sprint_name_from_date()` Which accepts a date and returns the name of the sprint that contains it.
- `SprintBoard.current_sprint` Which returns the name of the currently active sprint
- Adds private method `SprintBurndown._get_and_validate_sprint_name()` which is used to ensure that the value passed to the `sprint` argument is a valid sprint name
- Refactors `BaseMetric.chart` to be a property instead of an attribute whose value was set during `__init__()` This …
> [Issue 740] current sprint report

- frontend/public/locales/en/common.json
- frontend/src/components/Breadcrumbs.tsx
- frontend/src/components/ProcessContent.tsx
- frontend/src/pages/process.tsx
- frontend/stories/components/ProcessContent.stories.tsx
- frontend/tests/components/ProcessContent.tsx
Fixes #716 
Process intro section
NA
The result isn't exactly a match on desktop b/c of the USWDS defaults:
> [Issue 716] Add ProcessContent.tsx and process page update

- frontend/public/locales/en/common.json
- frontend/src/components/ResearchIntro.tsx
- frontend/src/pages/research.tsx
- frontend/tests/components/ResearchIntro.test.tsx
Fixes #719 
Adds intro to research page.
Copies intro setup from #788 
NOTE: That PR addresses the breadcrumb padding, this is just the intro without that fix:
> [Issue 719] Add research intro component

- frontend/public/locales/en/common.json
- frontend/src/pages/content/ResearchArchetypes.tsx
- frontend/src/pages/content/ResearchImpact.tsx
- frontend/src/pages/content/ResearchMethodology.tsx
- frontend/src/pages/content/ResearchThemes.tsx
- frontend/src/pages/newsletter.tsx
- frontend/src/pages/research.tsx
- frontend/stories/components/ReaserchImpact.stories.tsx
- frontend/stories/components/ReaserchThemes.stories.tsx
- frontend/tests/components/ResearchImpact.test.tsx
- frontend/tests/components/ResearchThemes.test.tsx
- frontend/tests/pages/research.test.tsx
Fixes #722 #723 #724 
Completed the Research page
- components for research impact and theme content
- test and stories
- required fields in newsletter form
- fix a broken link
desktop:
mobile:
> [ Issues 722, 723, 724] Complete research page

- frontend/public/locales/en/common.json
- frontend/src/components/BetaAlert.tsx
- frontend/src/components/FullWidthAlert.tsx
- frontend/src/pages/404.tsx
- frontend/src/pages/index.tsx
- frontend/src/pages/newsletter-confirmation.tsx
- frontend/src/pages/newsletter-unsubscribe.tsx
- frontend/src/pages/newsletter.tsx
- frontend/src/pages/process.tsx
- frontend/src/pages/research.tsx
- frontend/stories/components/BetaAlert.stories.tsx
- frontend/tests/components/BetaAlert.test.tsx
- frontend/tests/pages/404.test.tsx
Fixes #859
- Adds a new `BetaAlert` component that can be called in each page that needs an alert. This allows us to have a single instance of the content strings for the alert, instead of repeating them on each page that has it. 
- Updates all the pages to use the new `BetaAlert` component
- Adds the alert to the 404 page (IDK why it wasn't there. Seems intentional, as the test explicitly made sure it wasn't.) 
- Moves `sticky` to `BetaAlert`, separating that concern from `FullWidthAlert` (which might not always need to be sticky) 
- Closes #859 by updating the content of the alert
…
> [Issue 859] Add BetaAlert component and update its content

- frontend/src/components/ContentLayout.tsx
- Adds the `maxw-tablet-lg` to the headers in the `ContentLayout` component so that they are more legible 
Very long line lengths are difficult to read. Having a max width improves legibility. 
This change updates the site to better match the Figma.
> [Issue 888] Add max width to `ContentLayout` headers for legibility

- frontend/src/pages/content/IndexGoalContent.tsx
- frontend/src/pages/content/ProcessAndResearchContent.tsx
- frontend/src/pages/content/ProcessMilestones.tsx
- frontend/src/pages/content/ResearchMethodology.tsx
- Changes the method used for spacing icons within buttons so that they are not orphaned when the text wraps to multiple lines. 
- `margin-right` on a span containing the text causes it to wrap to a 2nd line sooner that would
- negative `margin-left` on the icon pulls it back closer to the text and makes sure it's always on the same line
On smaller screens, or when the grid column is smaller than the width of the text, buttons can wrap to two lines. At the largest point at which this happens, only the icon was wrapping to the second line. This fix makes it so that the icon is always on the same line as the last word of the text.
> [Issue 888] Prevent orphaned button icons

- frontend/public/locales/en/common.json
-  Make links bold (to match Figma)
-  nix stray period after the link
> [Issue 888] Fix typos in end paragraph on /research

- frontend/src/components/Hero.tsx
- Add `desktop-lg:margin-top-2` to the Hero's heading to decrease the space between it and the button
- Decrease the `line-height` of the intro paragraph
- Add `desktop-lg:margin-bottom-0` to the intro paragraph to nix the extra space at bottom of Hero
This change updates the site to better match the Figma.
> [Issue 888] Tweak responsive spacing of Hero

- frontend/public/locales/en/common.json
- Changes 2 instances of "Grants gov" to "Grants.gov"
This is just fixing a typo.
> [Issue 888] Fix 'Grants gov' typo

- frontend/public/locales/en/common.json
- Change the site title in the header from "Simpler Grants.gov" to "Simpler.Grants.gov"
- Do the same in the tab titles for each page
This change updates the site to match the Figma. We use the full URL — Simpler.Grants.gov — when referring to this beta website. We only use "simpler Grants.gov" (with a space and a lowercase s) when referring to the ultimate goal of making Grants.gov simpler.
> [Issue 888] Use dot not space when referring to Simpler.Grants.gov

- frontend/public/locales/en/common.json
- Makes the CTA links bold in the paragraphs on the newsletter subpages (to match Figma)
> [Issue 888] Make CTAs bold on newsletter subpages

- frontend/public/locales/en/common.json
- frontend/src/components/ContentLayout.tsx
- frontend/src/pages/content/ProcessMilestones.tsx
Partially addresses #873 
- Add a border below the roadmap section 
- Add chevron icons to the end of the first two items in the roadmap
- Positioning them between the columns to show direction
- hiding them on small screens, when the columns are stacked
- Update the `ContentLayout` component so that it accepts `gridGap` sizes 
- …because the roadmap grid needs to always have the widest gutter possible to acomodate the chevron icons 
- Set this to `true` by default, which is the setting for auto-sized gutters when just passing `gap` w/o an argument
- Reordered the props too (they were inconsistent, used alpha) 
**wide screen:** 
**medium screen:** 
**small screen:**
> [Issue 873] Roadmap chevrons, ContentLayout GapSizes

- frontend/public/locales/en/common.json
- frontend/src/components/ContentLayout.tsx
- frontend/src/pages/content/ProcessMilestones.tsx
- frontend/tests/components/ContentLayout.test.tsx
Partially addresses #873 
- Add prefixes to the milestone headers that indicate which roadmap item they're for
- Style them to look like a smaller pre-heading
> [Issue 873] Update milestone layout

- documentation/decisions/adr/2023-12-06-database-migrations.md
Fixes #779
Created ADR for database migrations with a focus on our usage of Alembic
We already use Alembic, this is an odd ADR that is aiming to explain "why" we use it (in short - it works well with SQLAlchemy, alternatives are a lot of effort or have a cost).
> [Issue 779] Writeup Alembic pros & cons ADR

- .github/CODEOWNERS
- MAINTAINERS.md
Fixes #633
Add new team members to MAINTAINERS and CODEOWNERS
> [Issue 633] Add Alsia and Michael to project

- README.md
Fixes #819
Update the index README with a bit more project context, the goal from the site, and a links back to the site (so that folx arriving on GitHub can easily navigate to or get back to Simpler.Grants.gov).
> [Issue 819] update index README with site info

- documentation/api/api-versioning.md
Fixes #697
Document API versioning now, and in the future
Our current approach for API versioning is simple so doesn't require much to explain it, but one idea that Lucas brought up regarding using headers to version the API is also discussed. I did spend a bit of time researching how we might do it which I documented, but from our most recent discussion it sounded like it was fine to wait on actually making a long-term decision on versioning. When we do that, this information will be useful in an ADR.
> [Issue 697] Document API versioning approach

- infra/modules/terraform-backend-s3/main.tf
Fixes #959
- Enable deletion protection for DynamoDB table `terraform_lock`.
Deletion protection is recommended by Security Hub.
This DynamoDB table is only used for terraform atomic locking. It doesn't contain any valuable data.
Verified that terraform plan looks as expected:
```terraform
~/Grants/simpler-grants-gov/infra/accounts$ terraform plan
...
module.backend.aws_dynamodb_table.terraform_lock: Refreshing state... [id=simpler-grants-gov-315341936575-us-east-1-tf-state-locks]
...
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:
~ resource "aws_dynamodb_table" "terraform_lock" {
~ deletion_protection_enabled = false -> true
id …
```
> [Issue 959] Enable deletion protection for DynamoDB table `terraform_lock`

- infra/api/app-config/main.tf
- infra/api/app-config/staging.tf
- infra/api/database/staging.s3.tfbackend
- infra/api/service/main.tf
- infra/api/service/staging.s3.tfbackend
- infra/frontend/app-config/main.tf
- infra/frontend/app-config/staging.tf
- infra/frontend/service/main.tf
- infra/frontend/service/staging.s3.tfbackend
- infra/modules/database/role_manager/role_manager.py
- infra/modules/service/access-control.tf
- infra/modules/service/load-balancer.tf
- infra/modules/service/main.tf
- infra/modules/service/variables.tf
- infra/networks/main.tf
- infra/networks/subnet-backfill.tf
- infra/networks/variables.tf
Fixes https://github.com/HHS/simpler-grants-gov/issues/963
This PR will be split into 3 major stages:
The existing networking infrastructure is in its "default" (AWS provided) state. This state does not meet the standards of our [ideal network layer design](https://github.com/navapbc/template-infra/blob/main/docs/decisions/infra/0011-network-layer-design.md) in a few ways. But the most notable one is: the default networking infrastructure lacks private subnets. You cannot remove the public IP addresses from the ECS instances without a first creating private subnets. So I'm requesting code review for Stage 1, backfilling the private subnets into the default VPC. This also includes attaching the VPC endpoints onto those private subnets.
Deploying this will require me to deploy the subnets …
> [Issue 963] Moves ECS services into private subnets

- .github/workflows/infra-service.yml
Fixes #1041 
Update the terraform version used in infra service checks to be the same as the terraform version for the rest of the project (1.2.1 to 1.4.6)
> [Issue 1041] Update infra service tf version

- infra/api/database/main.tf
- infra/api/service/main.tf
- infra/frontend/service/main.tf
In service of, but does not fix, https://github.com/HHS/simpler-grants-gov/issues/1037
@SammySteiner found that the frontend tests started failing once I created the staging VPC via https://github.com/HHS/simpler-grants-gov/pull/1044. This happened because the subnet selection logic is trying to deploy to every subnet in the account, as opposed to just the subnets for the current VPC. So when you create a 2nd VPC, the subnet selection logic fails. The error looks like this:
> Error: creating ELBv2 application Load Balancer (t-agywei-frontend-dev): InvalidConfigurationRequest: All subnets must belong to the same VPC
1. I'm deleting all the resources I created for https://github.com/HHS/simpler-grants-gov/pull/1044
2. This PR, which changes the subnet filter to only look for subnets in the …
> [Issue 1037] Harden subnet selection logic

- .github/workflows/cd-api.yml
- .github/workflows/cd-frontend.yml
Related to release documentation, eg. https://github.com/HHS/simpler-grants-gov/pull/1057, https://github.com/HHS/simpler-grants-gov/issues/1056
https://betagrantsgov.slack.com/archives/C05TSL64VUH/p1705952749866289
^ Currently `prod` releases are mislabeled, and say they are `dev`
I haven't tested this, so its possible this syntax doesn't work inside of the `run-name:` key. We wouldn't find that out until our next release, unfortunately!
> [Issue 1056] Fix release run names

- infra/api/database/main.tf
- infra/api/service/main.tf
- infra/frontend/service/main.tf
- infra/networks/subnet-backfill.tf
- infra/project-config/main.tf
- infra/project-config/outputs.tf
In service of, but does not resolve, https://github.com/HHS/simpler-grants-gov/issues/1037
- Changes all 3 terraform apps (frontend, backend, database) to allow them to be deployed from a non-default VPC
- Deploys the database into the "database" subnets, which have been backfilled into the default VPC
The Nava template has been updated to use non-default VPCs as our core networking layer. Migrating to that infrastructure will take quite some time, so I'm doing it piece by piece. The center of this piece is this code:
```hcl
network_configs = {
dev     = { vpc_name = "default" }
staging = { vpc_name = "staging" }
prod    = { vpc_name = "default" }
}
```
Which maps `environment` to `vpc name`. Currently, only `staging` is using a non-default VPC. I plan on having a long running branch …
> [Issue 1037] Allow choosing between multiple VPCs

- infra/modules/database/networking.tf
part of https://github.com/HHS/simpler-grants-gov/issues/1038
This code failed once I deployed the DMS networking layer to `staging`, since there were newly 2 security groups called `dms`
> [DMS] Select the DMS security VPC with a VPC filter

- infra/modules/dms-networking/main.tf
- infra/modules/dms-networking/variables.tf
- infra/modules/network/main.tf
- infra/modules/network/outputs.tf
- infra/modules/network/variables.tf
- infra/networks/.terraform.lock.hcl
- infra/networks/main.tf
- infra/project-config/main.tf
Rolls up to #1051
- Pipes in some DMS stuff are variables.
- Changes the second octet (eg. `x` in `10.x.0.0`) in the VPC cidr to be a variable. `dev`s cidr is staying the same, `staging` and `prod` are changing.
- I decided on this course of action after thinking about the DMS overnight. I concluded that the overlapping CIDRs might create a networking problem on the MicroHealth side.
- I'll need to redeploy staging and prod's VPCs in order to finish this PR. That'll take me a bit.
> [Issue 1051] Fix CIDR overlap

- infra/api/app-config/dev.tf
- infra/api/app-config/env-config/outputs.tf
- infra/api/app-config/env-config/variables.tf
- infra/api/app-config/prod.tf
- infra/api/app-config/staging.tf
- infra/api/database/main.tf
- infra/modules/database/main.tf
- infra/modules/database/variables.tf
Part of #1086 
- Add a `database_enable_http_endpoint` variable to the app config.
- If the variable is set, enable the HTTP endpoint for the RDS database.
- Set the new variable to `true` for all non-prod environments.
To enable work on #1086, we need to view the existing roles in the database. This enables the HTTP endpoint, which in turn enables the Query Editor on the AWS Console.
Partial terraform plan from `make infra-update-app-database APP_NAME=api ENVIRONMENT=dev`:
```terraform
~ resource "aws_rds_cluster" "db" {
~ enable_http_endpoint                = false -> true
id                                  = "api-dev"
tags                                = {}
}
```
> [Issue 1086] Enable HTTP endpoint to RDS databases

- infra/modules/dms-networking/main.tf
- infra/modules/dms-networking/networking.tf
Rolls up to #1038
Instead of associating the DMS exclusively with the main route table, I made it associate with all the route tables.
The new DMS connection isn't working ☹️ and this is a part of my debugging
> [Issue 1038] Explicitly associate the DMS with every subnet

- infra/modules/database/dms-instance.tf
Fixes #{ISSUE}
* change availability_zone attribute
DMS replication was failing in TF with:
```
Error: creating DMS Replication Instance (db-replication-instance): InvalidParameterCombinationException: The specified network type 'IPV4' is not supported by replication subnet group 'default'.
```
reference: https://github.com/hashicorp/terraform-provider-aws/issues/29198
> Patch Update DMS to Terraform

- .trivyignore
Fixes #1215 
Added CVE-2024-0567 and CVE-2023-5981 to trivy ignore whitelist.
> [Issue 1215] Trivy Ignore CVE-2024-0567 and CVE-2023-5981

- infra/modules/service/access-logs.tf
Part of #966
- Modify the bucket policy for the `*access-logs*` buckets to allow SSL requests only.
This policy is required by Security Hub control S3.5. See https://repost.aws/knowledge-center/s3-bucket-policy-for-config-rule
Tested by deploying to dev using `make infra-update-app-service APP_NAME=api ENVIRONMENT=dev`.
Before deploy:
After deploy:
Confirmed that the control switched from FAILED to PASSED on Security Hub:
> [Issue 966] Configure access log S3 buckets to allow SSL requests only

- .gitignore
Fixes #{ISSUE}
- Add `.vscode` folder to `.gitignore` to match setup instructions in docs
- frontend docs call for creating `.vscode/` workspace-specific settings to allow for prettier and eslint to run (on save) - so if developers add this folder, I believe it should be ignored?
- `.vscode/settings.json` controls the workspace settings
- Not sure if we need a ticket for this kind of quick change?
> TODO: Ignore local vscode settings

- api/Makefile
- api/src/app.py
- api/src/data_migration/__init__.py
- api/src/data_migration/copy_oracle_data.py
- api/src/data_migration/data_migration_blueprint.py
Fixes #1240
Setup a quick script that connects to the database
Let me know if you think there would be a better name for any of these files, quickly named a lot of this.
While it may seem odd, we actually can run tasks via Flask (this doesn't actually run routes - just re-using app setup). Running this way automatically handles setting up DB sessions, logging, and a few other utilities that we can re-use easily in a backend ECS task script. This shows how simple it is to set something new up (minus the infra).
The actual implementation will come in a follow-up script, this is just to unblock any infra work and let them have something to try to run.
You can run the task with `make copy-oracle-data` - for now this works locally and produces the following output:
> [Issue 1240] Create a basic ECS script which will become the copy process for Oracle data

- frontend/package.json
Fixes #1257 
- Set minimum node version in package.json to match docker
> TODO: set min node version to match docker

- api/src/data_migration/copy_oracle_data.py
Fixes #1241
Added the truncate + load commands for copying from the Oracle foreign data wrapper table
Note that there may be a way to set this up locally for unit testing purposes, but that will require a bit of work to build out, will follow up with that work once we've manually tested and confirmed this approach works without any major modifications.
Running locally I made a temporary table duplicated from `transfer_topportunity` and loaded records into it. I then loaded different records into transfer table, and ran the script, it deleted and loaded the records as expected.
Some of the logs:
> [Issue 1241] Truncate and load the transfer_topportunity table

- infra/api/database/main.tf
- infra/modules/database/networking.tf
- infra/modules/database/variables.tf
- infra/modules/dms-networking/main.tf
- infra/modules/dms-networking/variables.tf
- infra/networks/main.tf
- infra/project-config/main.tf
Helps with https://github.com/HHS/simpler-grants-gov/issues/1267
- Adds permissions for the database to query Oracle on port 1521, via means of the foreign data wrapper.
- Renames a variable since it won't be exclusively used for DMS anymore
```
+ resource "aws_vpc_security_group_egress_rule" "egress_to_oracle" {
+ arn                    = (known after apply)
+ cidr_ipv4              = "10.220.0.0/16"
+ description            = "Allow Orcale I/O into database"
+ from_port              = 1521
+ id                     = (known after apply)
+ ip_protocol            = "tcp"
+ security_group_id      = "sg-0011e7397e1025c78"
+ security_group_rule_id = (known after apply)
+ tags_all               = {
+ "description"         = "Database resources for the dev environment"
+ "environment"         = …
```
> [Issue 1267] Adds foreign data wrapper security group permissions

- frontend/Makefile
- frontend/README.md
Fixes #1259 
- add frontend make build target
- when adding a new package with npm and running `make dev`, local docker needs to rebuild to pull in new dependencies
> [Issues 1259] add frontend make build target

- infra/api/app-config/prod.tf
Contributes to #1281
Allow the RDS data API in prod, so I can use it for https://github.com/HHS/simpler-grants-gov/issues/1281, per conversation here: https://betagrantsgov.slack.com/archives/C05TSL64VUH/p1708451899268239
> [Issue 1281] Allow RDS Data API in prod

- infra/modules/dms-networking/main.tf
- infra/modules/dms-networking/networking.tf
- infra/modules/dms-networking/security.tf
- infra/modules/dms-networking/variables.tf
- infra/networks/main.tf
- infra/project-config/main.tf
Fixes #1285
no changes!
- replace the fake placeholder VPC cidr with the real one
- re-create the peering connection
terraform diff:
```
-/+ resource "aws_route" "dms" {
~ destination_cidr_block    = "10.220.0.0/16" -> "10.250.0.0/16" # forces replacement
~ id                        = "r-rtb-031ad0ccaf4d5da413548427919" -> (known after apply)
+ instance_id               = (known after apply)
+ instance_owner_id         = (known after apply)
+ network_interface_id      = (known after apply)
~ origin                    = "CreateRoute" -> (known after apply)
~ state                     = "blackhole" -> (known after apply)
~ vpc_peering_connection_id = "pcx-00e7861e707a69690" -> (known after apply)
}
-/+ resource "aws_route" "dms" {
~ destination_cidr_block    = "10.220.0.0/16" -> …
```
> [Issue 1285] Configure prod peering connection

- infra/modules/monitoring/main.tf
Fixes #1323
Makes the `high-app-response-time` alarm treat missing data as not breaching.
Right now this alarm is blowing up our inboxes because its swapping back and forth between `INSUFFICIENT_DATA` and `OK`. It's doing this because there's truly not enough data for most of the evaluation periods. My suggested fix for this is to treat missing data as a non-issue, so we don't get alerts when there is simply low traffic on the API.
This is a "plan and pray" situation, I haven't tested this.
> [Issue 1323] Fix a mis-firing alarm 

- infra/modules/dms-networking/networking.tf
Might help debug why https://github.com/HHS/simpler-grants-gov/issues/1285 isn't working
Allows DNS resolution over the peering connection, which might help with debugging why the production foreign data wrapper isn't working.
This will allow for enhanced DNS resolution between Grants.gov and Simpler. I'm not sure that it's required, but I don't think that it will hurt.
> [Issue 1285] Allow DNS resolution over peering

- .github/CODEOWNERS
The CODEOWNERS file syntax is
```
filename reviewers
filename reviewers
...
```
As shown here: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file
With this syntax, I believe it was assuming that `@acouch` was a filename.
> [Issue #1343] Address a CODEOWNERS issue

- .github/CODEOWNERS
Helps with #1343
Fixes the folder matching pattern
According to the docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
```
docs/*  docs@example.com
...
/docs/ @doctocat
```
The second pattern is actually what we want
> [Issue #1343] Fix codeowners syntax

- infra/api/app-config/dev.tf
- infra/api/app-config/env-config/outputs.tf
- infra/api/app-config/env-config/variables.tf
- infra/api/app-config/prod.tf
- infra/api/app-config/staging.tf
- infra/api/service/main.tf
- infra/modules/service/main.tf
- infra/modules/service/variables.tf
Fixes #1277
It feels like we require too much boilerplate to setup env vars, but I don't feel compelled to solve that today.
> [Issue #1277] add enable_v01_endpoints env var

- analytics/src/analytics/cli.py
- analytics/src/analytics/datasets/deliverable_tasks.py
- analytics/src/analytics/metrics/percent_complete.py
- analytics/tests/datasets/test_deliverable_tasks.py
- analytics/tests/metrics/test_percent_complete.py
- documentation/analytics/usage.md
Fixes #853 
- Adds `deliverable_status` as a column to the `DeliverableTasks` dataset to use in filtering
- Adds a private method `_isolate_deliverables_by_status()` that optionally filters deliverables if `statuses_to_include` is passed during instantiation
- Updates the other methods to use `self.deliverable_data` which stores the output of `_isolate_deliverables_by_status()`
This PR is stacked with #1319 and should be merged into that PR before both are merged into `main`
I need to complete the following items before this ready to be merged:
If you've …
> [Issue 853] Filter 30k deliverables based on status

- .github/workflows/ci-analytics.yml
- analytics/.vscode/settings.json
- analytics/Makefile
- analytics/src/analytics/cli.py
- analytics/src/analytics/datasets/base.py
- analytics/src/analytics/datasets/deliverable_tasks.py
- analytics/src/analytics/datasets/utils.py
- analytics/src/analytics/metrics/percent_complete.py
- analytics/tests/conftest.py
- analytics/tests/datasets/test_deliverable_tasks.py
- analytics/tests/integrations/test_slack.py
- analytics/tests/metrics/test_percent_complete.py
- documentation/analytics/usage.md
Adds a flag to the `analytics calculate deliverable_percent_complete` method for us to use the strategy for assigning issues to deliverables as described in [this ADR](https://github.com/HHS/simpler-grants-gov/blob/main/documentation/decisions/adr/2023-12-15-deliverable-reporting-strategy.md)
- Fixes #1016 
- Fixes #885 
- Fixes #853 
Also includes code from #1326 
- Added a new class method `DeliverableTasks.load_from_json_files_with_roadmap_data()` that creates the DeliverableTasks dataset by joining roadmap and sprint data using the `deliverable` column
- Adds a new flag to the `calculate_deliverable_percent_complete()` CLI entrypoint function that, when passed, will use this new strategy.
> Testing instructions, background context, …
> [Issue 1016] Switch to using deliverable column to join issues and deliverables

- frontend/.env.production
Fixes #1295 
- add `NEXT_PUBLIC_API_URL` for local and prod
- Need to come back for a part 2 for this ticket for `dev` and `staging`. I propose getting this merged so as not to block the rest of search.
- we could add to the staging work to this 10k: https://github.com/HHS/simpler-grants-gov/issues/1273 . Although it kind of makes sense to setup dev and staging for both at the same time?
- `npm run build` then `npm start` - this loads a production build locally . I printed `process.env.NEXT_PUBLIC_API_URL` seen here working from console:
- The local development env `npm run dev` loads `http://localhost`
> [Issue #1295]: add env vars for local and prod

- DEVELOPMENT.md
- api/Makefile
- api/artillery-load-test.yml
- frontend/Makefile
- frontend/README.md
- frontend/artillery-load-test.yml
Fixes #647
- Moves the load testing documentation to the root of the repo
- adds load testing scripts to the `api/Makefile`
- copies `artillery-load-test.yml` from `frontend` to `api`, then modifies the load balancer host + routes for the API
I used the same load characteristics that @SammySteiner added in https://github.com/HHS/simpler-grants-gov/pull/739
See `DEVELOPMENT.md` documentation. You should be able to run it locally. I suggest running it against staging.
> [Issue #647] artillery load testing for the backend

- api/Makefile
- api/src/db/models/base.py
- api/src/tool/console/interactive.py
Fixes #1446
- Add `make login-db` command to connect to the local database using the `psql` cli.
- Add a `__rich_repr__` method to `class Base` so that database objects are rendered more readably in `make console` sessions.
These changes are for developer convenience in local development.
Example of using `make login-db`:
Example of `make console` output of a database object:
Current output in comparison:
> [Issue #1446] Add `make login-db` and add `Base.__rich_repr__` method

- frontend/src/app/not-found.tsx
- frontend/src/app/search/page.tsx
- frontend/src/components/BetaAlert.tsx
- frontend/src/services/FeatureFlagManager.ts
- frontend/tests/services/FeatureFlagManager.test.ts
Fixes #1451 
- Update `FeatureFlagManager` to handle server component request cookies
- Create new server component copy of `NotFound` page (called when FF off)
- Put search page behind `showSearchV0` feature flag
https://github.com/HHS/simpler-grants-gov/assets/93001277/644f5631-5fb4-431d-9b01-177c38d2b895
Since we moved the search page to a server component - we need to allow for the FeatureFlagManager to be called with server request cookies. For any client components, we still have the custom hook `useFeatureFlags` which wraps the `FeatureFlagManager`.
> [Issue #1451] Put search page behind feature flag

- infra/api/app-config/env-config/outputs.tf
- infra/api/app-config/env-config/variables.tf
- infra/api/app-config/prod.tf
- infra/api/service/main.tf
Fixes https://github.com/HHS/simpler-grants-gov/issues/906
Adds configuration for deploying the `api.simpler.grants.gov` cert to the prod load balancer
```
data.terraform_remote_state.current_image_tag[0]: Reading...
module.service.data.aws_region.current: Reading...
module.service.data.aws_iam_policy_document.ecs_tasks_assume_role_policy: Reading...
data.aws_ssm_parameter.api_auth_token: Reading...
module.service.data.aws_region.current: Read complete after 0s [id=us-east-1]
module.service.data.aws_iam_policy_document.ecs_tasks_assume_role_policy: Read complete after 0s [id=597844978]
module.service.data.aws_caller_identity.current: Reading...
aws_scheduler_schedule_group.copy_oracle_data: Refreshing state... [id=api-prod-copy-oracle-data] …
```
> [Issue 906] Adds prod API domain

- api/gunicorn.conf.py
Fixes #1391
Set the number of gunicorn workers to 2*cpu count + 1
We temporarily set the number of workers to exactly 2 while getting the API running initially. This shouldn't be needed anymore, and would mean we are potentially underutilitizing our API instances. This number follows the recommended values:
See: https://docs.gunicorn.org/en/stable/design.html#how-many-workers
also: https://docs.gunicorn.org/en/latest/configure.html#configuration-file
Currently, we run 2 workers always. With our current API configuration, this should change to 5. We actually log the `sched_getaffinity` value when the process starts up. Pulling from the prod logs, this gives (trimming extra info for brevity):
```json
{
"name": "src.logging.config",
"levelname": "INFO",
"levelno": 20,
"pathname": …
```
> [Issue #1391] Set the gunicorn workers based on CPU count

- frontend/src/app/search/SearchForm.tsx
- frontend/src/app/search/actions.ts
- frontend/src/components/FilterCheckbox.tsx
- frontend/src/components/search/SearchBar.tsx
- frontend/src/components/search/SearchFilterAccordion/SearchFilterAccordion.tsx
- frontend/src/components/search/SearchFilterAccordion/SearchFilterCheckbox.tsx
- frontend/src/components/search/SearchFilterAccordion/SearchFilterSection/SearchFilterSection.tsx
- frontend/src/components/search/SearchFilterAccordion/SearchFilterToggleAll.tsx
- frontend/src/components/search/SearchFilterAgency.tsx
- frontend/src/components/search/SearchFilterFundingInstrument.tsx
- frontend/src/components/search/SearchOpportunityStatus.tsx
- frontend/src/components/search/SearchPagination.tsx
- frontend/src/components/search/SearchResultsHeader.tsx
- frontend/src/components/search/SearchResultsList.tsx
- frontend/src/hooks/useSearchFilter.ts
- frontend/src/hooks/useSearchFormState.ts
- frontend/src/hooks/useSearchParamUpdater.ts
- frontend/src/types/requestURLTypes.ts
- frontend/src/types/searchTypes.ts
- frontend/src/utils/convertSearchParamsToStrings.ts
- frontend/tests/components/search/SearchOpportunityStatus.test.tsx
- frontend/tests/hooks/useSearchFilter.test.ts
- frontend/tests/hooks/useSearchFormState.test.ts
- frontend/tests/hooks/useSearchParamUpdater.test.ts
Fixes #1489 
- Finish debounced update for accordion filter (agency and funding instrument)
- Accordion filter loads initial state 
- Add custom hook `useSearchFormState` that wraps the new React `useFormState` 
- Add tests for custom hooks 
- Explicitly mark client components with `use client`
https://github.com/HHS/simpler-grants-gov/assets/93001277/1af0cdd7-e625-485d-bf52-d1be961d5a9a
> [Issue #1489] Complete search filter accordion logic

- documentation/architecture/README.md
Fixes https://github.com/HHS/simpler-grants-gov/issues/1276
- removes the mermaid AWS architecture diagrams
- adds a lucidchart AWS architecture diagram
This architecture diagram is meant to be viewed as an abstraction of the important high level components of our architecture. As such, there's some fine details that are intentionally missing from it. For example, the "VPC Endpoints" section intentionally doesn't list every single AWS service we are accessing through VPC endpoints.
Given that, I'm interested in feedback on whether or not the architecture diagram is missing some high level components. For example, in early versions of this diagram I forgot the foreign data wrapper + step functions setup. Large components like that are important to have called out in the diagram, so please …
> Updated architecture diagram

- api/docker-compose.yml
- docker-compose.yml
- frontend/docker-compose.yml
Fixes #1510
- Move `nextjs` and `storybook` service to `./frontend/docker-compose.yml`
- Move `grants-api` and `grants-db` service to `./api/docker-compose.yml`
- Top level `./docker-compose.yml`
- Command from FE folder => `make build-dev dev storybook`
- Command from BE folder => `make build start run-logs`
> [Issue #1510]: Split FE / BE docker-compose

- api/Makefile
- api/openapi.generated.yml
- api/src/api/opportunities_v0_1/opportunity_schemas.py
- api/src/services/opportunities_v0_1/search_opportunities.py
- api/tests/lib/seed_local_db.py
- api/tests/src/api/opportunities_v0_1/test_opportunity_route.py
- documentation/api/database/database-local-usage.md
Fixes #1455
Implements logic for the query field in the search API
Updated the seed script to allow you to generate more opportunities locally
This logic is deliberately very, very simple at the moment. It basically just does a text contains check across several columns. This is the most naive approach, and it is expected that if you tried to search two separate words at the same time, you probably won't get any results.
A few options we may consider later (depending on the level of effort we want to put into a non-search-index approach):
- Postgres text search / tsvectors: https://www.postgresql.org/docs/current/textsearch.html
- Postgres text similarity: https://www.postgresql.org/docs/current/pgtrgm.html
The `ids` function I added for the tests was because there are a lot of tests and …
> [Issue #1455] Implement logic for query box in the search API

- frontend/src/components/search/SearchResultsList.tsx
- frontend/src/components/search/SearchResultsListItem.tsx
Fixes #1229 
- Add a new component for SearchResultsListItem
- Conditionally render and format the dates with "tag" styles
--
> [Issue #1229] Dynamic tag format in search results

- infra/frontend/app-config/dev.tf
- infra/frontend/app-config/env-config/environment-variables.tf
- infra/frontend/app-config/env-config/outputs.tf
- infra/frontend/app-config/env-config/variables.tf
- infra/frontend/app-config/prod.tf
- infra/frontend/app-config/staging.tf
- infra/frontend/service/main.tf
- infra/modules/service/main.tf
- infra/modules/service/variables.tf
Closes https://github.com/HHS/simpler-grants-gov/issues/1519
- removes old secrets pattern for sendy SSM secrets
- adds new fancy secrets pattern for sendy SSM secrets
I did this so our repo would contain up to date examples of how to get the frontend to read SSM parameters.
Read the documentation for this system, if you haven't already: https://github.com/HHS/simpler-grants-gov/blob/main/documentation/infra/environment-variables-and-secrets.md
I deployed to dev, inspected the task definition, and tested sendy
task definition with sendy secrets: 
sendy test:
> [Issue #1519] Configure sendy with new secrets pattern

- api/openapi.generated.yml
- api/src/api/schemas/search_schema.py
- api/tests/src/api/opportunities_v0_1/test_opportunity_route.py
Fixes #1493
Updated search schema logic to disallow:
1. Empty `one_of` lists
2. Empty filter lists
These changes remove a few edge cases that have undefined / difficult to define behavior if we allow them (ie. what do we do if a list is empty, `opportunity_status in [ ]`). Rather than try to sort out what the behavior might mean / modify a users search request and interpret what we think they probably mean, we don't allow that type of request and chalk it up to user error in constructing a request.
Note that this does not modify the behavior of just not passing filters, that's still perfectly fine, we just want to avoid being passed filters that are half-built. See the additional section below for what is / isn't allowed.
An example request looks like:
```json
{
"filters": {
"agency": { …
```
> [Issue #1493] Update search schema to disallow empty filters

- analytics/src/analytics/cli.py
- analytics/src/analytics/metrics/burndown.py
- analytics/src/analytics/metrics/burnup.py
- analytics/src/analytics/metrics/utils.py
Relates to https://github.com/HHS/simpler-grants-gov/issues/1541
I ran `make lint` then committed most of the results. I didn't commit all of the results because this isn't my code and so I don't want to overstep. Which is to say, `make lint` produced even more changes that you don't see in this PR. I think it would ideally be the responsibility of the code author(s) to address those changes.
This PR is necessary due to CI not actually checking if the lining is being done. See https://github.com/HHS/simpler-grants-gov/issues/1541 for more details.
> [Issue 1541] Ran `make lint` on analytics folder

- api/src/services/opportunities_v0_1/search_opportunities.py
- api/tests/src/api/opportunities_v0_1/test_opportunity_route.py
Fixes #1494
Adjust the logic for filtering by agency to be an exact match instead of the prior "starts with" logic.
This adjustments comes out of a recent discussion with our front-end folks. Turns out they intend to pass us every agency for sub-agencies (eg. `HHS-123`, `HHS-456`, etc). I had implemented sub-agency logic assuming we'd want prefixes, which is clunky. This makes the logic more intuitive by just being a simple match.
Note that previously the agencies were also case-insensitive which is no longer here, but that also isn't really necessary.
Updated a few tests that assumed prior logic - nothing too significant here
> [Issue #1494] Modify agency filter to be an exact match

- api/src/app.py
- api/src/task/__init__.py
- api/src/task/opportunities/set_current_opportunities_task.py
- api/src/task/task.py
- api/src/task/task_blueprint.py
- api/src/util/datetime_util.py
- api/tests/src/task/opportunities/test_set_current_opportunities_task.py
Fixes #1365
Created a script that fetches all opportunities, determines what the current opportunity summary + opportunity status should be, and sets them
Added some miscellaneous backend task utilities for logging / metrics
https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/v1V0jIH7mb7Yb3jlNrgk/engineering/learnings/opportunity-endpoint-data-model#calculating-current-summary provides the context for this change.
In simplest terms, the algorithm is actually quite simple:
* Fetch all opportunities
* For each, determine the latest forecast and non-forecast summary
* Determine which of these 2 summaries can be used (they must not be deleted, must on/after the post date)
* Choose the non-forecast if possible, otherwise the forecast, otherwise null
* Set the current opportunity summary + …
> [Issue #1365] Create script to setup the current opportunities table

- .github/workflows/ci-analytics.yml
- analytics/Makefile
- analytics/src/analytics/metrics/burnup.py
- analytics/src/analytics/metrics/utils.py
Fixes https://github.com/HHS/simpler-grants-gov/issues/1541
Splits `lint` into:
- format
- format-check
- lint
Their purposes are explained inline
See https://github.com/HHS/simpler-grants-gov/issues/1541
> [Issue #1541] Fail CI when there are outstanding linter changes

- infra/analytics/database/outputs.tf
Contributes to #1551
Adds a terraform `output` required to run `make infra-update-app-database-roles APP_NAME=analytics ENVIRONMENT=dev`. I forgot to copy this when I was copying the database files earlier.
I've already deployed this
```
$ make infra-update-app-database-roles APP_NAME=analytics ENVIRONMENT=dev
```
```
./bin/create-or-update-database-roles.sh analytics dev
Initializing the backend...
Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Initializing modules...
Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Reusing previous version of hashicorp/archive from the dependency lock file
- Reusing previous version of hashicorp/aws from the dependency lock file …
```
> [Issue #1551] Add missing output to analytics database

- infra/api/service/copy_oracle_data.tf
Relates to #1548
- added `aws_cloudwatch_log_group` to fix an error:
> Error: creating Step Functions State Machine (...): InvalidLoggingConfiguration: Invalid Logging Configuration: The CloudWatch Logs Resource Policy size was exceeded. We suggest prefixing your CloudWatch log group name with /aws/vendedlogs/states/.
This error occurs periodically (eg. not every time) when trying to deploy this configuration
This change originated in https://github.com/HHS/simpler-grants-gov/pull/1604
> [Issue #1548] Update Oracle SFN logs

- infra/analytics/app-config/dev.tf
- infra/analytics/app-config/env-config/environment-variables.tf
- infra/analytics/app-config/prod.tf
- infra/analytics/app-config/staging.tf
Fixes #1621
- Adds the dev / staging / prod configuration for the analytics service secrets
- Adds the "ACTION" env var for dev / staging / prod, with inline explanations of what it does
```hcl
-/+ resource "aws_ecs_task_definition" "app" {
~ arn                      = "arn:aws:ecs:us-east-1:315341936575:task-definition/analytics-dev:11" -> (known after apply)
~ arn_without_revision     = "arn:aws:ecs:us-east-1:315341936575:task-definition/analytics-dev" -> (known after apply)
~ container_definitions    = jsonencode(
~ [
~ {
~ environment            = [
+ {
+ name  = "ACTION"
+ value = "show-results"
},
{
name  = "AWS_REGION"
value = "us-east-1"
},
]
~ linuxParameters        = {
~ capabilities       = {
- add  = []
}
}
- mountPoints            = []
name                   = "analytics-dev" …
```
> [Issue 1621] Adds Analytics secrets

- frontend/src/app/api/SearchOpportunityAPI.ts
- frontend/src/app/search/SearchForm.tsx
- frontend/src/app/search/actions.ts
- frontend/src/components/search/SearchFilterCategory.tsx
- frontend/src/components/search/SearchFilterEligibility.tsx
- frontend/src/hooks/useSearchFormState.ts
- frontend/src/services/search/FormDataService.ts
- frontend/src/services/search/searchfetcher/SearchFetcher.ts
- frontend/src/types/search/searchRequestTypes.ts
- frontend/src/utils/search/convertSearchParamsToProperTypes.ts
- frontend/tests/api/SearchOpportunityApi.test.ts
- frontend/tests/hooks/useSearchFormState.test.ts
Fixes #1593 
- Add  eligibility and category filters
- working with API request, checked boxes load with initial query params, and results actually filter based on values   
- `category` in the frontend becomes `funding_category` for the API request
- `elgibility` in the frontend becomes `applicant_type` for the API request
https://github.com/HHS/simpler-grants-gov/assets/93001277/2a4afc2a-b566-45a9-a95d-ea6d1f81da60
> [Issue #1593]: Add eligibility and category filters

- api/Makefile
- api/docker-compose.debug.yml
- api/poetry.lock
- api/pyproject.toml
- documentation/api/development.md
Fixes #1272
- Add API debugger (currently just supporting VSCode)
- Add docs for how to set it up
- It was first added to the template project here: https://github.com/navapbc/template-application-flask/pull/222
- we've just copied it into this repo with a few minor path changes
- `launch.json` setup was added to docs, but that file is not checked into the repo
- branch name is accidentally issue 1271 when it should be 1272
- see demo:
https://github.com/HHS/simpler-grants-gov/assets/93001277/654e329a-6c6e-4b56-9910-4b81c7489804
> [Issue #1272]: Setup API Debugger for VSCode

- analytics/Makefile
- analytics/src/analytics/cli.py
- infra/analytics/database/prod.s3.tfbackend
- infra/analytics/database/staging.s3.tfbackend
- infra/analytics/service/prod.s3.tfbackend
- infra/analytics/service/sfn_sprint_reports.tf
- infra/analytics/service/staging.s3.tfbackend
Fixes #1625
- fixes an instance of a path being hardcoded to `./data`
- adds staging and prod terraform configuration
Staging step function running successfully:
output is here: https://betagrantsgov.slack.com/archives/C06L7JGT9M0/p1712613628944219
Prod step function running successfully:
output is here: https://betagrantsgov.slack.com/archives/C064Y8VNW14/p1712613702615029
> [Issue #1625] Deploy to staging and prod, fix path

- api/Makefile
Fixes #1446
- Fix `make login-db` to set the schema search path.
Follow up to #1444 and #1520 so that `make login-db` sets the schema search path to `api`
Example of `make login-db` followed by `\dt` (list tables):
> [Issue #1446] Fix `make login-db` to set schema path

- infra/api/app-config/env-config/environment-variables.tf
- infra/api/app-config/env-config/outputs.tf
- infra/api/service/main.tf
- infra/modules/service/main.tf
- infra/modules/service/variables.tf
- infra/modules/task-service/main.tf
- infra/modules/task-service/variables.tf
Fixes #1521
Both `infra/api` and `infra/frontend` were defining a variable called `API_AUTH_TOKEN`. The way they were defined made them clash, leading to the following error message:
> Error: creating ECS Task Definition (frontend-dev): ClientException: The secret name must be unique and not shared with any new or existing environment variables set on the container, such as 'API_AUTH_TOKEN'
Refactors the terraform configuration so the `API_AUTH_TOKEN` definition is no longer clashing between the frontend and backend
I have already deployed both the API and the frontend to dev to test that this is working.
> [Issue #1521]: fix API_AUTH_TOKEN clash between backend and frontend

- .github/actions/configure-aws-credentials/action.yml
- .github/workflows/cd-api.yml
Fixes #1781
- removes `-refresh-only` from `terraform apply`
- adds miscellaneous logging 
Without these changes, are terraform deploys in CI are broken.
> [Issue #1781] terraform debugging

- api/src/constants/lookup_constants.py
- api/src/db/models/lookup_models.py
Fixes #1853
Move where we define the LookupConfig definitions to reduce circular dependencies
This doesn't change the configs, just where they're defined. We frequently want to import the enums defined in lookup_constants, but because that file in turn depends on the DB lookup files, we run into some odd circular dependencies that require manually sorting imports to resolve. Instead, we'll just define those LookupConfig classes in the only place they're ever used to avoid the headache.
> [Issue #1853] Move where we define the lookup mapping to avoid constant import issues

- .github/workflows/ci-frontend.yml
Fixes #1842
- update workflow to use jest coverage report 
https://github.com/marketplace/actions/jest-coverage-report
I believe subsequent PRs should show the diffs in coverage report that the respective PR introduces -  for example this is a snapshot of a PR from the template project 
* this is a much smaller project so it's easier over there to get above 90% coverage
> [Issue #1842]: Add jest coverage report in PR

- frontend/src/app/layout.tsx
Fixes #1619 
> Added GA to App Router
> Next.js requires a different GA setup for pages using the App Router compared to the page router.
https://nextjs.org/docs/messages/next-script-for-ga
> [Issue #1619] Update Google Analytics to add App Router support

- infra/analytics/metabase/.terraform.lock.hcl
- infra/analytics/metabase/dev.s3.tfbackend
- infra/analytics/metabase/image_tag.tf
- infra/analytics/metabase/main.tf
- infra/analytics/metabase/variables.tf
- infra/modules/metabase-service/access-control.tf
- infra/modules/metabase-service/access-logs.tf
- infra/modules/metabase-service/application-logs.tf
- infra/modules/metabase-service/autoscaling.tf
- infra/modules/metabase-service/database-access.tf
- infra/modules/metabase-service/load-balancer.tf
- infra/modules/metabase-service/main.tf
- infra/modules/metabase-service/networking.tf
- infra/modules/metabase-service/outputs.tf
- infra/modules/metabase-service/s3.tf
- infra/modules/metabase-service/secrets.tf
- infra/modules/metabase-service/variables.tf
- infra/modules/metabase-service/waf.tf
Fixes #1553
The bulk of this code was copied from `infra/analytics/service` and `infra/modules/service`. That's why this PR is so large, it was a copy then modify operation. Some notable aspects are:
- removed the container healthcheck, modified the load balancer healthcheck
- [modified the database configuration](https://github.com/HHS/simpler-grants-gov/pull/1856/commits/3673f50f2d652cf63e407fd631e715aa2ba8b618) for the `MB_DB_` environment variables and secret config
- [modified the linux parameters](https://github.com/HHS/simpler-grants-gov/pull/1856/commits/90c0f96e9636976bdb7d88441b3705a815db523f#diff-97243c73e2e391ffa640cb5bb7d804bd0c71e0ce1f5deddabacc997bfada9832L72-L77), without which the application doesn't deploy 
- the majority of `infra/modules/metabase-service` is the same …
> [Issue #1553] Deploys a Metabase ECS service

- .github/workflows/cd-analytics.yml
- .github/workflows/cd-api.yml
- .github/workflows/cd-frontend.yml
Fixes #{ISSUE}
* update env logic
Deploys were resolving to `[APP] Array` instead of the actual environment which was breaking deploys
[Example](https://github.com/HHS/simpler-grants-gov/actions/runs/8913679992)
> [Patch] Update cd-* scripts to deploy staging pt 2

- analytics/docker-compose.yml
- analytics/local.env
Fixes https://github.com/HHS/simpler-grants-gov/issues/1597
Adds a dockerized postgres database for the analytics service to connect to. Does not yet actually connect to that database, that'll come in future PRs.
```bash
$ docker compose up
```
```bash
$ psql postgresql://app:secret123@localhost:5432/app
```
> [Issue #1597] Add analytics local docker database

- infra/modules/metabase-service/waf.tf
- infra/modules/service/waf.tf
Fixes #1871 
* add policy for cloudwatch logging group
This has been a recurring issue with the `aws_wafv2_web_acl_logging_configuration` resource for quite some time. For context, the WAF service will automatically create its own associated policy (it's called `WAF-LOGS` or something like that).
This policy doesn't appear to get "cleaned up", etc if its created automatically, which means, if the aws account is either:
1. constantly creating new ACLs
2. has a lot of ACLs to begin with
The policy will end up exceeding its maximum size and prevent the resource from being created. This is what's currently breaking deploys related to the frontend and metabase.
[Terraform Docs explaining the workaround](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl_lo …
> [Task 1871] Finish configuring WAF

- analytics/docker-compose.yml
- analytics/local.env
Fixes https://github.com/HHS/simpler-grants-gov/issues/1910
Adds Metabase to the analytics docker compose file
This PR simply configures that local Metabase instance so that it stands up. It doesn't yet do anything with Metabase. Hence the lack of documentation. 
```bash
docker compose up
```
> [Issue #1910] Configure a local Metabase instance

- .github/workflows/cd-frontend.yml
Fixes #{ISSUE}
* temporarily remove "staging" from the frontend deployment matrix to unblock others
> The staging deploy fails because both dev and staging try to release the same tag
See #1919 for more detail
> [Issue #1919] Deploying to (dev, or staging) fails because trying to release the same image tag twice part 1

- frontend/src/components/search/SearchFilterAccordion/SearchFilterAccordion.tsx
- frontend/tests/components/search/SearchFilterAccordion/SearchFilterAccordion.test.tsx
Fixes #1886 
- add the query param key to the end of the accordion id 
- We had duplicate id's for each accordion div - so just append the specific query param key that we use to the id
- the remaining Lighthouse a11y issue is due to the `<span>...</span>` that's in the component (only `<li>` tags are allowed inside `<ul>`) . But this is the USWDS implementation so I'm not sure if we can get around that bug? 
Lighthouse doesn't have this error anymore:
> [Issue #1886]: Fix duplicate id bug in SearchFilterAccordion

- infra/analytics/metabase/main.tf
- infra/api/service/main.tf
- infra/frontend/service/main.tf
- infra/modules/service/database-access.tf
- infra/modules/service/variables.tf
Fixes #1943
Changes `app_access_policy_arn` and `migrator_access_policy_arn` to not be nested under `db_vars`
`terraform plan` now works in the following folders:
- infra/analytics/metabase
- infra/api/service
- infra/frontend/service
> [Issue #1943] Fix variable access

- .github/linters/scripts/close-issues-in-done-col.sh
Updates comment posted to issue to indicate the action was performed automatically by a bot.
Fixes #1932 
Updates the comment posted when automatically closing a ticket.
Here's an example of an [auto-closed ticket with the new comment](https://github.com/HHS/simpler-grants-gov/issues/1531#issuecomment-2100610783)
> [Issue #1932] Updates comment on "Lint - Close done issues"

- api/src/data_migration/__init__.py
- api/src/data_migration/command/__init__.py
- api/src/data_migration/command/load_transform.py
- api/src/task/opportunities/set_current_opportunities_task.py
Fixes #1810
- Add an entrypoint that runs the 3 tasks for load and transform in series.
The regular load and transform job runs 3 tasks in order:
1.  LoadOracleDataTask
2. TransformOracleDataTask
3. SetCurrentOpportunitiesTask
This is implemented as a flask command and can be run locally using
`poetry run flask data-migration load-transform`
Options are available to turn on or off each of the 3 tasks.
```
Options:
--load / --no-load              run LoadOracleDataTask
--transform / --no-transform    run TransformOracleDataTask
--set-current / --no-set-current
run SetCurrentOpportunitiesTask
```
> [Issue #1810] add entrypoint to run load and transform tasks

- frontend/src/app/api/BaseApi.ts
- frontend/src/app/api/SearchOpportunityAPI.ts
- frontend/src/app/search/SearchForm.tsx
- frontend/src/app/search/error.tsx
- frontend/src/errors.ts
- frontend/src/hooks/useSearchFormState.ts
- frontend/src/services/search/FormDataService.ts
- frontend/src/services/search/searchfetcher/APISearchFetcher.ts
- frontend/src/services/search/searchfetcher/SearchFetcher.ts
- frontend/src/utils/search/convertSearchParamsToProperTypes.ts
- frontend/tests/api/SearchOpportunityApi.test.ts
- frontend/tests/errors.test.ts
- frontend/tests/hooks/useSearchFormState.test.ts
Fixes #1680 
- rename `SearchFetcherProps` to `QueryParamData` to more accurately represent this interface
> [Issue #1680]: rename SearchFetcherProps to QueryParamData

- frontend/src/components/search/SearchResultsList.tsx
Fixes #1958 
- Remove "Select at least one status..." from 0 results page
> [Issue #1958]: Remove status message for 0 results

- frontend/src/app/search/page.tsx
- frontend/src/hoc/search/withFeatureFlag.tsx
Fixes #1968
- add `withFeatureFlag` higher order component
- Able to wrap any server component page with this React HOC - helps keep the server page component thin
https://github.com/HHS/simpler-grants-gov/assets/93001277/21c17ff9-a2de-4d75-bd09-7f9fc7456211
> [Issue #1968]: Add withFeatureFlag HOC

- api/src/data_migration/load/load_oracle_data_task.py
- api/src/data_migration/load/sql.py
- api/tests/src/data_migration/load/test_sql.py
Fixes #1978
- Optimize chunked load further by moving chunking logic from database to PostgreSQL.
Instead of using `LIMIT` to carry out chunking in PostgreSQL, read the full set of ids as a first step, then issue a series of INSERT / UPDATE queries.
This is expected to be faster. With the previous method, the PostgreSQL optimizer did not do an ideal plan, and did a full read of all rows and columns from the Oracle database. By splitting the query, we can do a read of only the id columns for the new or updated rows. Then additional queries select only the rows that have changed.
N/A
> [Issue #1978] further optimizations for load chunking

- api/src/data_migration/transformation/transform_util.py
- api/tests/src/data_migration/transformation/test_transform_util.py
- api/tests/src/db/models/factories.py
Fixes #1985
When handling transformations of booleans, allow `Yes` and `No` as valid values in addition to `Y` and `N`.
These new values are immensely uncommon, but there are a few rare occurrences of them. Easier to just support them than work around in any other way.
For example, in `TSYNOPSIS_HIST`, the count of values for the cost_sharing bool:
```
No	971
N	60820
Y	13723
Yes	581
```
The non-history table does not have this value.
> [Issue #1985] Allow yes/no for transformed booleans

- frontend/src/app/search/SearchForm.tsx
- frontend/src/components/search/SearchPagination.tsx
- frontend/src/styles/_uswds-theme.scss
Fixes #1965 
- Reintroduce totalPages
- set max pagination slots to 7
Fixing the size of the pagination and overflow issues around the 600px viewport width will be done in a separate effort
https://github.com/HHS/simpler-grants-gov/assets/93001277/eb13eb29-d91a-4f7d-8c78-bbafe2590fb7
> [Issue #1965]: Reintroduce totalPages to Pagination component

- frontend/src/app/template.tsx
Fixes #1889
> Added a client useEffect that will fire GA4 page change whenever a page is loaded 
> https://github.com/vercel/next.js/issues/58924
> [Issue #1889]: Adding template to nextjs to fix history change with GA4

- frontend/src/app/api/BaseApi.ts
Fixes #1682
- rename search specific references in `BaseApi` file
- There's also `SearchAPIResponse` in this file - but I think we use that more widely so I think we should defer cleaning that up (until maybe we have endpoints other than Search that we need types for)
> [Issue #1682]: remove search specific references in BaseAPI

- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/layout.tsx
- frontend/src/app/template.tsx
- frontend/src/components/search/SearchBar.tsx
Fixes #1889
> Added manual "search" api call for GA4 on search bar click
> Updated template to call GA4 correctly
> Updated @next/third-party to canary to fix issues
> Context in Eng Slack Thread
> [Issue #1889] Updating GA4 for nextjs v2

- api/src/data_migration/load/load_oracle_data_task.py
- api/src/data_migration/load/sql.py
- api/tests/src/data_migration/load/test_sql.py
Fixes #1998
- Change the `WHERE` in the update query to use the source table columns.
- Commit to the database after each chunk, not after each table.
Observing the queries on the PostgreSQL RDS and Oracle sides, we saw that the `WHERE ... IN (...)` was not being pushed down to Oracle. This is an attempt to fix that.
N/A
> [Issue #1998] optimize the WHERE in load updates

- api/local.env
- api/src/app.py
- infra/api/app-config/dev.tf
- infra/api/app-config/prod.tf
- infra/api/app-config/staging.tf
Fixes #1688
Remove the `ENABLE_V_0_1_ENDPOINTS` feature flag as we just want these endpoints enabled everywhere now
This flag was to hide our endpoints while we built them out, we want these enabled everywhere now, so not much reason to keep it.
> [Issue #1688] Remove feature flag for v0.1 endpoints

- .github/renovate.json
- api/.gitignore
Fixes #2175
Adjusted the renovate config to not tell us to upgrade Postgres version in our docker-compose file
Minor fix for something missed in the merge for the .gitignore - otherwise that also gets included by Renovate / anyone who stands up localstack
See for example: https://github.com/HHS/simpler-grants-gov/pull/2023
I'm not certain how we can test Renovate, I need to see if I can make it use this branch when running
> [Issue #2175] Ignore Postgres in Docker for renovate config

- .github/workflows/ci-analytics.yml
- analytics/Dockerfile
- analytics/Makefile
- analytics/docker-compose.yml
- analytics/poetry.lock
- analytics/pyproject.toml
Fixes #2184
Fixed our Python version to 3.12 (dockerfile and pyproject.toml)
Removed usage of `docker-compose` command for `docker compose`
Removed version from docker-compose file (prints a warning - no longer used)
Similar changes have been made recently to the API. Was updating dependencies in the folder earlier and realized these should also happen for analytics and are pretty minimal.
The Python version change doesn't change what version of Python we use, but I've found in past years when new versions of Python come out, a lot of dependencies temporarily break until they've had a chance to build in upstream repositories. This change just makes it so we can manually test that upgrade and take care of it once things are less chaotic (note Python releases occur in October). …
> [Issue #2184] Tidy up python and docker usage in analytics

- api/src/adapters/search/opensearch_client.py
- api/src/adapters/search/opensearch_config.py
- api/tests/src/adapters/search/test_opensearch_client.py
Fixes #2094
Some small adjustments to how we connect to and setup the connection to OpenSearch in preparation to work with AWS
This hasn't quite been tested yet because we don't have anything in AWS to test with, but at least locally it works still as expected.
This is currently just following the recommended approach from the docs: https://opensearch.org/docs/latest/clients/python-low-level/#connecting-to-amazon-opensearch-serverless
> [Issue #2094] Update the way we setup the connection to OpenSearch

- api/src/services/opportunities_v1/search_opportunities.py
- api/tests/src/api/opportunities_v1/test_opportunity_route_search.py
Fixes #2177
Fixed issue with facet count names which was causing the opportunity status to be populated incorrectly
Added a test to prevent issue in the future
These fields aren't used yet - just a minor bug I noticed when setting up the demo the other day
> [Issue #2177] Fix facet count name issue

- frontend/.eslintrc.js
- frontend/.storybook/I18nStoryWrapper.tsx
- frontend/.storybook/preview.tsx
- frontend/src/app/[locale]/opportunity/[id]/page.tsx
- frontend/src/app/api/SearchOpportunityAPI.ts
- frontend/src/app/sitemap.ts
- frontend/src/components/content/FundingContent.tsx
- frontend/src/components/content/IndexGoalContent.tsx
- frontend/src/hoc/search/withFeatureFlag.tsx
- frontend/src/hooks/useFeatureFlags.ts
- frontend/src/services/FeatureFlagManager.ts
- frontend/src/services/search/SearchFilterManager.ts
- frontend/src/services/search/searchfetcher/APISearchFetcher.ts
- frontend/src/services/search/searchfetcher/MockSearchFetcher.ts
- frontend/src/utils/opportunity/isSummary.ts
- frontend/src/utils/search/convertSearchParamsToProperTypes.ts
- frontend/stories/pages/search.stories.tsx
- frontend/tests/api/BaseApi.test.ts
- frontend/tests/api/SearchOpportunityApi.test.ts
- frontend/tests/components/Spinner.test.tsx
- frontend/tests/components/search/SearchFilterAccordion/SearchFilterSection/SectionLinkCount.test.tsx
- frontend/tests/components/search/SearchFilterAccordion/SearchFilterSection/SectionLinkLabel.test.tsx
- frontend/tests/services/FeatureFlagManager.test.ts
- frontend/tests/utils/FeatureFlagTestUtils.ts
- frontend/tests/utils/getRoutes.test.ts
- frontend/tests/utils/isSummary.test.ts
Fixes #1868
Enforces absolute imports outside of the same directory.
> [Issue #1868] Enforce absolute imports outside of the same directory

- frontend/tests/pages/not-found.test.tsx
- frontend/tests/pages/page.test.tsx
- frontend/tests/pages/process/page.test.tsx
- frontend/tests/pages/research/page.test.tsx
- frontend/tests/utils/intlMocks.ts
Fixes #1393
Adding basic page level tests for static pages
Based on previously existing tests that required some reworking due to code drift and support for internationalization: https://github.com/HHS/simpler-grants-gov/blob/2024.5.13-1/frontend/tests/pages/index.test.tsx
1. `npx jest tests/pages/page.test.tsx`
2. `npx jest tests/pages/research/page.test.tsx`
3. `npx jest tests/pages/process/page.test.tsx`
4. `npx jest tests/pages/not-found.test.tsx`
5. _VALIDATE_: all tests pass
> test: basic tests for static pages [1393]

- frontend/src/app/[locale]/search/loading.tsx
- frontend/src/app/[locale]/search/page.tsx
- frontend/src/i18n/messages/en/index.ts
- frontend/stories/pages/loading.stories.tsx
- frontend/tests/e2e/search/search-loading.spec.ts
Fixes #1937
Implemented the translation library for the text on the Search loading spinner
This component is currently under the Search page, but seems like we'd likely reuse it elsewhere. Since file moves are weird to PR and revert I wanted to get more input before moving stuff around.
Tested by implementing Storybook for this component
> [Issue #1937] Translate Loading component text

- frontend/src/app/[locale]/layout.tsx
- frontend/src/app/api/BaseApi.ts
- frontend/src/app/api/OpportunityListingAPI.ts
- frontend/src/app/api/SearchOpportunityAPI.ts
- frontend/src/app/sitemap.ts
- frontend/src/constants/environments.ts
- frontend/src/pages/api/subscribe.ts
- frontend/src/services/search/searchfetcher/SearchFetcherUtil.ts
- frontend/src/utils/assetPath.ts
Fixes ... unticketed
All access to `process.env` moved to a central location, and update any consuming files, in order to:
* allow for easy reference to environment variables used throughout the application
* perform any necessary defaulting or interpretation of environment variables in one place\
* allow for easier testing / mocking of environment variable values
* improve performance (?)
* * based on somewhat anecdotal concerns as referenced here https://github.com/motdotla/dotenv/issues/562
1. `npx run test`
2. _VERIFY_: all tests pass
3. `npm run dev`
4. run through all pages and basic functionality of the app
5. _VERIFY_: all functions as normal
> chore: standardize access to process.env [unticketed]

- frontend/stories/pages/loading.stories.tsx
Follows #1937
Fix import path to not fail new linter rule banning relative paths
> [Issue #1937] Comply with new linter rules about import paths

- api/src/adapters/search/opensearch_config.py
Set defaults for Opensearch params until we have them defined in Terraform
There are a few more ways we could do this that aren't quite so hacky (that don't require terraform), I'll circle back to those tomorrow
> Set defaults to unbreak Opensearch config for the moment

- infra/api/app-config/dev.tf
- infra/api/app-config/env-config/outputs.tf
- infra/api/app-config/env-config/variables.tf
- infra/api/app-config/prod.tf
- infra/api/app-config/staging.tf
- infra/api/service/sfn_load_transform.tf
Fixes https://github.com/HHS/simpler-grants-gov/issues/1809
Activates the load-transform job in every environment. In dev it runs with `--no-*` on everything, so it runs but doesn't do anything.
> [Issue #1809] Add load-transform SFN

- frontend/src/components/search/SearchResultsListItem.tsx
Fixes #2172 
I changed the render logic to pull agency name from the root of the object as specified in the original issue. I chose to leave the agency code lookup as a fallback. Open to removing that fall back if we think that'd make more sense? Thoughts r.e. leaving agency code lookup as a backup @acouch ?
Make sure search results still have agency results where expected locally.
> Change reference location in api object for agency name on search

- .github/workflows/labeler.yml
https://github.com/HHS/simpler-grants-gov/pull/2188 broke it, and I don't feel like fixing it right now
I case someone feel like fixing it, the documentation is here: https://github.com/actions/labeler/tree/main
Bear in mind that renovate bot is going to try to recreate the PR to upgrade this action version again. We'll just have to tell it to skip this one.
> Revert pull request labeler version upgrade

- .github/renovate.json
This allows renovate to create issue(s). Having an open issue to reference will help with enabling open source contributors. The documentation for the dependency dashboard is here:
https://docs.renovatebot.com/key-concepts/dashboard/
This is the kind of thing that you can't test without merging
> Add Renovate "dependency dashboard"

- frontend/src/components/Footer.tsx
Fixes #2099 
Add class to set width to auto to remove browser console warning about aspect ratio and retain max height class.
Load site locally and assure no warning appears in the console r.e. image size
> Add width auto to fix aspect ratio warning but retain max height

- frontend/src/components/Footer.tsx
- frontend/src/constants/routes.ts
- frontend/src/i18n/messages/en/index.ts
- frontend/tests/components/Footer.test.tsx
Fixes #1588 
Update twitter link in footer to 'X': logo, hint/name, and link route itself
> Update footer X/Twitter link

- frontend/src/app/[locale]/opportunity/[id]/page.tsx
- frontend/src/app/api/OpportunityListingAPI.ts
- frontend/src/components/opportunity/OpportunityAwardGridRow.tsx
- frontend/src/components/opportunity/OpportunityAwardInfo.tsx
- frontend/src/components/opportunity/OpportunityDescription.tsx
- frontend/src/components/opportunity/OpportunityIntro.tsx
- frontend/src/components/opportunity/OpportunityStatusWidget.tsx
- frontend/src/components/search/SearchResultsListItem.tsx
- frontend/src/constants/breadcrumbs.ts
- frontend/src/types/opportunity/opportunityResponseTypes.ts
- frontend/tests/api/OpportunityListingApi.test.ts
- frontend/tests/components/opportunity/OpportunityDescription.test.tsx
- frontend/tests/components/opportunity/OpportunityIntro.test.tsx
Fixes #2222
* Account for empty summaries which we can expect from the API
* Fix some of the type definitions for API fields that can be null
* bonus: Add title of the opp to the page
* note that next encourages multiple fetch (only GET) in the same component tree: https://nextjs.org/docs/app/building-your-application/caching
* bonus: Fix lack of gap with the description:
becomes:
* bonus: search breadcrumbs updated to link from `/search` to `/search?status=forecasted,posted`
> [Issue #2222] Account for empty summaries

- .github/workflows/ci-frontend.yml
- .github/workflows/labeler.yml
Summary
Fixes #2231
Time to review: 5 mins
Changes proposed
While the coverage commenting back is what is breaking things, this is the only place the tests are run, so we don't want to just skip the whole action. We instead want it to run the tests, and just not do things that forks don't have permissions to do with the coverage reporting.
Context for reviewers
Found this workaround/fix from the author on this ticket ArtiomTr/jest-coverage-report-action#313 (comment)
> [Issue #2231] Fix Checks failing on forked branches

- api/src/data_migration/transformation/transform_util.py
- api/src/task/opportunities/set_current_opportunities_task.py
- api/tests/src/data_migration/transformation/test_transform_util.py
- api/tests/src/task/opportunities/test_set_current_opportunities_task.py
Fixes #2338
Modified the set-current-opportunities script to remove the opportunity_status + current opportunity from any opportunity where is_draft=True
Minor adjustment to the transformation logic to allow different capitalization for str booleans as the Oracle test DB had a few variations different from prod for some fields
The set-current-opportunities script is the last step of the transformation process which handles calculating both the current opportunity summary (in short - figure out which forecast/non-forecast record is "active") as well as that summaries status.
We don't want to calculate these values if the opportunity is a draft as there is no current summary technically as it isn't "ready" yet. We already filter drafts out of our endpoints, this just keeps the data in the …
> [Issue #2338] Adjust set-current-opportunities script to remove status from drafts

- api/Dockerfile
Fixes #2395
Stop installing some Linux packages that were added previously to "fix a trivy failure"
This started failing randomly, so removing the stuff we added the last time it failed randomly seems to stop the random failures...
> [Issue: #2395] Try not installing packages that were added to fix a prior trivy issue

- api/src/data_migration/load/sql.py
- api/tests/src/data_migration/load/test_load_oracle_data_task.py
- api/tests/src/data_migration/load/test_sql.py
Fixes #2405
Fallback to using `created_date` when `last_upd_date` is null
The legacy Oracle database has a last_upd_date timestamp that we use for finding updates to our system.
This field is always null when a record is first inserted, and only on receiving at least one update will it be populated.
This means that if a record is inserted, we copy over last_upd_date=null and then an update happens, we try to do effectively: where null < {some timestamp} which means we find nothing when trying to update. What we instead should do is fallback to using the created_date timestamp if the update date is null.
Found this when I realized there were cases where we just weren't processing updates. Turns out, the ELT process doesn't handle updates pretty much at all right now (this is the common …
> [Issue #2405] Account for updates when last_upd_date is null

- infra/api/service/main.tf
https://betagrantsgov.slack.com/archives/C05TSL64VUH/p1728501460077109
```
-/+ resource "aws_ecs_task_definition" "app" {
~ arn                      = "arn:aws:ecs:us-east-1:315341936575:task-definition/api-dev:186" -> (known after apply)
~ arn_without_revision     = "arn:aws:ecs:us-east-1:315341936575:task-definition/api-dev" -> (known after apply)
~ container_definitions    = jsonencode(
~ [
~ {
~ environment            = [
{
name  = "DB_USER"
value = "app"
},
+ {
+ name  = "ENVIRONMENT_NAME"         # <===========
+ value = "dev"                      # <===========
},
{
name  = "PORT"
value = "8000"
},
]
~ linuxParameters        = {
~ capabilities       = {
- add  = []
}
}
- mountPoints            = []
name                   = "api-dev"
~ portMappings           = [
~ {
- hostPort …
```
> Add service to environment variables

- .github/workflows/ci-frontend-e2e.yml
- frontend/tests/playwright.config.ts
Fixes #2459
This is a small fix to run the e2e tests against the built version of the frontend. The test for this PR ran a minute slower than the previous PR (3 mins 51 secs vs 4 min 49 secs).
> [Issue #2459] Speed up e2e tests by testing against built frontend

- frontend/tests/e2e/search/search-loading.spec.ts
- frontend/tests/e2e/search/search-no-results.spec.ts
Fixes #2005 
- Remove e2e test skips for webkit, the test appear to pass now, presumably as a result of search refactoring that previously happened.
- Checkout branch locally and run webkit e2e tests to verify they pass.
> Remove selective e2e test skips for webkit

- frontend/src/components/Header.tsx
- frontend/src/components/search/SearchResultsListItem.tsx
- frontend/tests/e2e/search/search-navigate.spec.ts
- frontend/tests/e2e/search/searchSpecUtil.ts
Fixes #2456
Moves from the HTML `<a/>` to Next App routers [`<Link/>`](https://nextjs.org/docs/app/api-reference/components/link) component which enables [client-side navigation](https://nextjs.org/learn-pages-router/basics/navigate-between-pages/client-side) between pages which keeps the navigation from re-render.
The navigation can still flicker upon initial load, so the approach taken in #2427 might still be necessary.
> [Issue #2456] Remove flicker from navigation between pages

- frontend/src/app/[locale]/process/ProcessMilestones.tsx
- frontend/src/i18n/messages/en/index.ts
- frontend/tests/utils/intlMocks.ts
Fixes #1397
* update DOM structure on process page to follow best practices for lists (previously implemented as three invidual lists with one item each, rather than one list with three items)
* update aria labels to make high level roadmap items more readable by screen readers
* a few refactors for better readability of process page code
1. visit localhost:3000/process
2. visit https://simpler.grants.gov/process
3. _VERIFY_: the "high-level roadmap" section of each page matches visually
4. turn on screen reader (cmd + fn + f5 probably)
5. ctrl + opt + cmd + h to cycle through headings until you find "the high level roadmap"
6. ctrl + opt + a to read the content
7. _VERIFY_: roadmap headings are read out as "Step 1: Find" etc.
note that requirement in the ticket specifying removal of …
> [Issue #1397] process roadmap accessibility

- infra/analytics/app-config/env-config/environment-variables.tf
- infra/analytics/app-config/env-config/outputs.tf
- infra/analytics/service/.terraform.lock.hcl
- infra/analytics/service/main.tf
- infra/analytics/service/secrets.tf
- infra/frontend/app-config/env-config/environment-variables.tf
- infra/frontend/app-config/env-config/outputs.tf
- infra/frontend/service/.terraform.lock.hcl
- infra/frontend/service/main.tf
- infra/frontend/service/secrets.tf
Fixes #2485
Fixes secrets stuff for the frontend and analytics modules
Build failure => https://github.com/HHS/simpler-grants-gov/actions/runs/11354826962/job/31583001030
Root cause => https://github.com/HHS/simpler-grants-gov/pull/2341
Testing:
<details>
<summary>frontend terraform plan</summary>
```
terraform plan -var "environment_name=dev"
data.terraform_remote_state.current_image_tag[0]: Reading...
module.app_config.data.external.account_ids_by_name: Reading...
module.app_config.data.external.account_ids_by_name: Read complete after 0s [id=-]
module.service.data.aws_iam_policy_document.ecs_tasks_assume_role_policy: Reading...
module.service.data.aws_caller_identity.current: Reading...
module.service.data.aws_ecr_repository.app[0]: Reading... …
```
> [Issue #2485] Swap everything to new secrets pattern

- .github/workflows/deploy.yml
Right now builds are failing because of a race condition between migrations and build and publish. This fixes that by making the dependency explicit.
> Require build and publish before database migrations

- api/docker-compose.yml
- frontend/.env.development
- frontend/README.md
- frontend/docker-compose.yml
Issue #2497 
In order to get search working in a local dockerized environment, network Next.js and api containers together
This is only necessary for local development, and should have no impact otherwise.
Note that it may take a while for the next to compile the search and home routes - anywhere from 200 to 700 seconds. Not sure if this is normal, or just me, something that is isolated to the local process, or if this is a sign of an actual issue
1. in the api directory `make stop`
2. in the api directory `make start`
3. uncomment line 19 of the frontend/.env.development file, and comment out line 20
4. in the frontend directory `make stop`
5. in the frontend directory `make start`
6. visit localhost:3000/search
7. _VERIFY_: no errors, and search results are displayed
> Screenshots, GIF …
> [Issue 2497] network fronted and api docker containers

- .github/workflows/ci-frontend-e2e.yml
- frontend/package.json
- frontend/src/app/api/BaseApi.ts
- frontend/src/app/api/OpportunityListingAPI.ts
- frontend/src/app/api/SearchOpportunityAPI.ts
- frontend/src/services/search/searchfetcher/APISearchFetcher.ts
- frontend/src/types/apiResponseTypes.ts
- frontend/src/types/opportunity/opportunityResponseTypes.ts
- frontend/src/types/search/searchResponseTypes.ts
- frontend/tests/api/BaseApi.test.ts
- frontend/tests/api/OpportunityListingApi.test.ts
- frontend/tests/api/SearchOpportunityApi.test.ts
- frontend/tests/e2e/newsletter.spec.ts
- frontend/tests/e2e/search/search-loading.spec.ts
- frontend/tests/e2e/search/search-no-results.spec.ts
- frontend/tests/e2e/search/searchSpecUtil.ts
Fixes #2448
**DISCLAIMER**: there is a lot of scope creep in this PR. Feel free to push back on anything you feel goes to far here.
The primary purpose of this change is to change the search API to use the `v1` version of the search endpoint in order to activate the use of Open Search on the backend. This purpose is accomplished in the first commit, which can be split into a separate PR or commit if called for.
The rest of the PR contains refactors to the `API` fetch system that:
* should reduce redundancy and make better use of the classical setup in place here
* makes better use of available TS functionality
* better encapsulates domain specific logic (eg moving search specific functionality out of the base class)
* fixes bugs
1. visit the search page, and perform all manner of searches …
> [Issue 2448] use v1 search endpoint and frontend fetch pattern refactors

- .dockleconfig
- api/Dockerfile
- api/poetry.lock
- api/pyproject.toml
Fixes #{[2385](https://github.com/HHS/simpler-grants-gov/issues/2385)}
Upgrade python version for API to 3.13.0
New version of python(3.13) was recently released.
> [Issue 2385] upgrade to python version 3.13.0

- api/src/data_migration/transformation/subtask/transform_agency.py
- api/src/data_migration/transformation/transform_oracle_data_task.py
- api/tests/src/data_migration/transformation/subtask/test_transform_agency.py
Fixes #2492
Add transform step to Agency transformation
Add tests
As part of our transformation process, we transform agency data from the legacy system, but we want to do a second pass over agency data once in our system in order to make the agency data connect together properly.
In the system, there are agencies and sub-agencies. For example, HHS is a top-level agency, and HHS-NIH11 is a subagency. We want HHS-NIH11 to point to HHS in the top_level_agency_id foreign key we setup in https://github.com/HHS/simpler-grants-gov/issues/2491
Determining whether an agency is a top-level or subagency is simple, a top-level agency will have no dashes, while a sub-agency will have one or more dashes in its agency code with the top-level agency being everything before the first dash. We want to …
> [Issue #2492] Create an agency linking step for the transformation process

- api/openapi.generated.yml
- api/src/api/response.py
- api/src/api/schemas/response_schema.py
- api/src/logging/flask_logger.py
- api/tests/src/api/test_healthcheck.py
Fixes #2521
Return the internal request ID in all error responses
A follow-up from a discussion we had yesterday. This can aid in debugging as a user can just give us the ID and we can easily look up the corresponding logs.
Note `g` in Flask is a request-local global context (ie. each request has their own separate `g`) which we use for storing a few other logging related things already safely. https://flask.palletsprojects.com/en/3.0.x/appcontext/#storing-data
An example of the logs that show the internal ID - note I trimmed out the full error message as it's a very long stack trace.
> [Issue #2521] Have the error response always return an internal request ID

- .github/workflows/vulnerability-scans.yml
- analytics/README.md
Fixes https://github.com/HHS/simpler-grants-gov/issues/2538
Changes the grype output from a table (which redacts critical information) to json output that shows the path the vulnerability is coming from. This, for example, pins down the location of a golang vulnerability inside of the analytics docker image.
I decided to spend some time on this because we burned so much time hunting down the golang vulnerability the other day. Also I'm kind of procrastinating my other work, sorry 😓
https://github.com/HHS/simpler-grants-gov/actions/runs/11467321173/job/31910027111
The analytics vulnerability is in the `gh` CLI
> [Issue #2538] Show the path of a vulnerability

- frontend/src/app/[locale]/opportunity/[id]/page.tsx
Fixes #2337
Return notFound() if opportunity API returns a 404 error code.
See screen capture to demonstrate local env returning 'Oops! Page Not Found' title vs current dev showing 'Opportunity Listing' title:
https://github.com/user-attachments/assets/31a6ba1b-8e9f-4df7-9a79-bd72ac7ca8e1
> Return notFound if opportunity not found

- analytics/Makefile
- analytics/src/analytics/cli.py
- documentation/analytics/development.md
Fixes a bug that was preventing users from running `make gh-data-db-import`
Fixes #2355 
- Removes the step in `export_json_to_database()` that was broken after the structure of our GitHub project changed.
- Updates `documentation/analytics/development.md` with the new installation instructions.
- Set logging level to INFO
1. Follow the new installation instructions in `documentation/analytics/development.md`
2. Run `make gh-data-export`
3. Run `make gh-data-db-import`
> Screenshots, GIF demos, code examples or output to help show the changes working as …
> [Issue #2355] Fix bug in analytics db import

- frontend/package-lock.json
- frontend/package.json
Fixes #2487
Upgrade Trussworks to latest version, upgrade USWDS to latest version supported by Trussworks.
See notes here: https://github.com/HHS/simpler-grants-gov/issues/2487#issuecomment-2432512375
**Note:** it's probably too early to implementing anything, but how do we feel about visual diffing tools like Percy?
These test steps are what I did, in order to allow an easy-ish side by side comparison of main vs this branch, but you could take screenshots of the main branch pages and compare to screenshots of this branch, or there are probably other options as well. The point is, do a visual diff of the site.
1. _VERIFY_ all CI build stuff passes
2. create an alternate simpler repo either by re-cloning into a new directory, or running a `cp` into a new directory
3. ensure that your …
> [Issue 2487] relevant uswds and trussworks upgrades

- .github/workflows/vulnerability-scans.yml
Runs vulnerability scans twice so we can get both the version fixes and CVE locations
This is a patchwork fix for #2580. I would rather fix this upstream, so I'm not making this PR as resolving #2580
> [Issue #2580] Run vulnerability scans twice

- infra/accounts/logs.tf
- infra/modules/search/authentication.tf
- infra/modules/search/main.tf
- infra/modules/service/waf.tf
Fixes https://github.com/HHS/simpler-grants-gov/issues/2327
^ I ran into the resource limit above when deploying prod opensearch
So I have changed it so there is only 1 `aws_cloudwatch_log_resource_policy` resource
I've already deployed this to dev, and to the account level. The diff applied just fine.
> [Issue #2327] Move WAF and Opensearch logs policies to the account level

- api/src/db/migrations/versions/2024_10_28_add_opportunity_table_triggers.py
- api/src/db/models/opportunity_models.py
Fixes #2603
Add migration which adds DB triggers to populate `opportunity_search_index_queue` based on updates made to existing tables:
opportunity
opportunity_assistance_listing
current_opportunity_summary
opportunity_summary
link_opportunity_summary_funding_instrument
link_opportunity_summary_funding_category
link_opportunity_summary_applicant_type
opportunity_attachment
See test SQL below. Created migration will add or update entries in the opportunity_search_index_queue table until a subsequent process handles them.
See attached SQL file for running tests based on these changes:
```
-- Start transaction for all tests
BEGIN;
-- Test 1: Basic opportunity insert
INSERT INTO api.opportunity (opportunity_id, opportunity_title, is_draft)
VALUES (99999, 'Test Opportunity', false);
-- Verify …
```
> [Issue #2603] Setup triggers on our opportunity tables which populate the search queue table

- infra/api/app-config/env-config/scheduled_jobs.tf
Fixes #2528
Modified ELT process to run hourly
Removed the load job for the v0 data
I can't imagine there is much value in the v0 job now that v1 works. Probably will save us a bit as we won't be running a process near constantly that no one uses.
I changed the schedule expression to a cron so that the schedule is a bit more consistent. The `rate(..)` configuration seems to be based on when you turn it on, or last did a deploy. This will keep it from varying every time we deploy and instead make it so it's always at the top of the hour.
https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-scheduled-rule-pattern.html
> [Issue #2528] Change job schedule ELT process to hourly

- .github/workflows/deploy.yml
```
2024-10-30T18:48:37.855Z [INFO]  CLI command args: []string{"version", "-lock-timeout=120s", "--version"}
Usage: terraform [global options] version [options]
Displays the version of Terraform and all installed plugins
Options:
-json       Output the version information as a JSON object.
Error parsing command-line flags: flag provided but not defined: -lock-timeout
```
https://github.com/HHS/simpler-grants-gov/actions/runs/11598939885/job/32298507568
:(
> [no ticket] remove lock timeout stuff

- api/src/adapters/aws/s3_adapter.py
Modified the configuration for our s3 client to use `s3v4` for the signature version
Something with the way encryption works on s3 buckets requires setting a different signature version than the default that botocore uses.
Locally I was getting a URL like: `http://localhost:4566/local-opportunities/test_file_5.pdf?AWSAccessKeyId=NO_CREDS&Signature=Pg9ZyyoIkLKAawtsrCFOTwtjbF4%3D&Expires=1730319613` before and after the change I get `http://localhost:4566/local-opportunities/test_file_5.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=NO_CREDS%2F20241030%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241030T195105Z&X-Amz-Expires=1800&X-Amz-SignedHeaders=host&X-Amz-Signature=1e138f2b39305c711fa152a6504454db11f022c7644775d0b7a52dbeb339f809`
As a quick test, I went to the AWS s3 console and …
> [Unticketed] Change s3 client to use s3v4 signature version

- infra/modules/search/authentication.tf
- infra/modules/search/main.tf
Relates to #2500
@chouinar discovered that the opensearch policy might be "flip flopping" between two versions because we technically define it twice. So this PR removes one of those policies.
> [Issue #2500] Remove duplicate restrictive search access policy

- analytics/Makefile
- analytics/src/analytics/cli.py
- analytics/src/analytics/datasets/issues.py
- analytics/src/analytics/metrics/burndown.py
- analytics/src/analytics/metrics/burnup.py
- analytics/src/analytics/metrics/utils.py
- analytics/tests/conftest.py
- analytics/tests/datasets/test_issues.py
- analytics/tests/metrics/test_burndown.py
- analytics/tests/metrics/test_burnup.py
- analytics/tests/test_cli.py
Stacked PR that builds on #2539 to replace the `SprintBoard` dataset in `SprintBurndown` and `SprintBurnup` with the new `GitHubIssues` dataset. 
Fixes #2471
**Note:** ~Once we merge in #2539 I'll rebase this branch on `main` and change the base for the PR to `main`~ Rebased ✅ 
- Replaces the `SprintBoard` dataset with `GitHubIssues` in the `SprintBurndown` and `SprintBurnup` metrics
- Reuses intermediate steps to calculate burnup/burndown across both `SprintBurnup` and `SprintBurndown`
1. Follow the instructions to run this code natively (in order to view …
> [Issue #2471] Update `SprintBurndown` to use `GitHubIssues` dataset

- api/Makefile
Add a command that fully remakes the API, DB, search index, and populates those with seed data
Just connecting a few commands together that we already have
> [Unticketed] Add a command that fully sets up a working API

- infra/api/app-config/env-config/scheduled_jobs.tf
- infra/api/app-config/prod.tf
Fixes #2630
Schedule the DB -> search index load job to run every hour
Set the shard/replica count for prod as it needs to be higher as we have more nodes.
In the future we may want to coordinate the ELT process with this (put them in the same flow?), but for now I've setup the job to run 30 minutes after the start of the hour. The job in prod takes ~9 minutes at the moment.
The ELT process takes 4-5 minutes and runs at the top of the hour - the jobs overlapping wouldn't be a big deal other than search having staler data.
> [Issue #2630] Enable search load to run hourly

- frontend/src/constants/featureFlags.ts
Fixes #2701
Flipping the search FF to allow anon users to see the search and opp pages.
We should have a follow-up to remove the FF manager implementations ie:
```javascript
export default withFeatureFlag(Search, "showSearchV0");
```
etc
I created an additional PR for this which we can keep until in DRAFT until we are ready.
> [Issue #2701] Set search FF to allow for anon users 

- api/src/data_migration/transformation/subtask/transform_assistance_listing.py
- api/src/data_migration/transformation/transform_constants.py
- api/tests/src/data_migration/transformation/subtask/test_transform_assistance_listing.py
Fixes #2699
Modify `transform_assistance_listings` to skip listings with empty or null values for `programtitle` or `cfdanumber` values.
We want to modify the process that transforms assistance listings from the legacy system to not create a record in our assistance listings table if the program_title/assistance_listing_number are null/empty. The legacy system has these "empty" records to handle connecting other pieces of data in a way that is confusing, and can be implemented differently when we get to it.
See attached unit tests
> [Issue #2699] Skip assistance listing transform processing with empty fields

- api/src/data_migration/load/load_oracle_data_task.py
- api/src/data_migration/transformation/transform_oracle_data_task.py
- api/tests/src/data_migration/transformation/test_transform_oracle_data_task.py
Fixes #2697
Enable the extract-load process on the TGROUPS table (agency data)
Enable the Agency transform steps
I've tested this in the lower environments and prod by manually configuring the job to load the data, so all of the agency data is there already. This just gets updates from here on out.
The extract-load process has a set of tables it is configured to load, and the transformation process has specific classes for transforming tables that are handled via env vars, so the configuration change is minor.
The unit test changes I made show that the agency transforms are happening now when running the "full" job.
> [Issue #2697] Enable agency data load in ELT process

- frontend/src/app/[locale]/search/page.tsx
- frontend/src/components/search/SearchAnalytics.tsx
- frontend/src/types/search/searchRequestTypes.ts
- frontend/tests/components/search/SearchAnalytics.test.tsx
Fixes #1890
Added a GA event beacon "search_attempt" to track each load of the search results page and pass along a list of filters in place.
Note that in React strict mode, which is on for us and by default when running a DEV Next server, components basically mount, unmount, then mount again, in order to test out expected behavior around maintaining state between page loads, or something. This means that out of the box on a local server you may see multiple beacons being fired when the page is first loaded, but if you turn off strict mode here, you should see only one:
https://github.com/HHS/simpler-grants-gov/blob/fa3aabddd9d34feaa0c358888e7c5008970e7033/frontend/next.config.js#L19
For more see https://legacy.reactjs.org/docs/strict-mode.html#ensuring-reusable-state
Also these test …
> [Issue 1890] add GA beacon for filter use on search

- frontend/src/app/[locale]/opportunity/[id]/page.tsx
- frontend/src/components/Breadcrumbs.tsx
- frontend/src/i18n/messages/en/index.ts
Fixes #2709
Added the opportunity number to the end of the breadcrumb text on the opportunity listing page. Also fixed the casing on the search "sort by" label as per request from design (requirement not in the attached ticket)
1. visit the search page
2. _VERIFY_: sort by text reads "Sort by" and not "Sort By"
3. visit an opportunity pate
4. _VERIFY_: the opportunity number is visible at the end of the breadcrumb, ex `Home > Search > Walters PLC 1973 award: ROP-941-FY1996-350`
> [Issue 2709] add opportunity number to breadcrumb

- analytics/Makefile
- analytics/src/analytics/cli.py
- analytics/tests/test_cli.py
Partially Fixes #2665
Minor change to Makefile and CLI to integrate the export work done in #2481 with the import work done in #2482.
Issue #2481 added capability to export data from GitHub to a flat file that can be ingested by the new import capabilities added by issue #2482. However, in testing, I just noticed a filename mismatch in `Makefile` that precludes e2e integration. This PR fixes the filename mismatch. 
> [Issue 2665] Minor fix to Makefile and CLI to integrate GitHub export and import capabilities 

- api/src/adapters/search/opensearch_query_builder.py
- api/src/services/opportunities_v1/search_opportunities.py
- api/tests/src/adapters/search/test_opensearch_query_builder.py
Fixes #2729
Set `track_total_hits` to True when calling OpenSearch
While this field says it has possible performance cost due to needing to count all the records, we also request a count for various facet counts anyways, so I imagine this won't matter at all.
https://opensearch.org/docs/latest/api-reference/search/
I loaded ~16k records into my local search index. Querying it with no filters returns this pagination info now:
```json
{
"order_by": "opportunity_id",
"page_offset": 1,
"page_size": 25,
"sort_direction": "ascending",
"total_pages": 676,
"total_records": 16884
}
```
> [Issue #2729] OpenSearch should return an accurate count of total results

- infra/analytics/app-config/env-config/scheduled_jobs.tf
Fixes #2665 
Added `gh-transform-and-load` command to existing `make gh-data-export` command. I'm not sure if this is sufficient or correct, but I'm taking a guess based on what I see in https://github.com/HHS/simpler-grants-gov/pull/2546 and https://github.com/HHS/simpler-grants-gov/pull/2506.
In the analytics work stream, we have a new CLI command `make gh-transform-and-load` for transforming and loading (some) GitHub data. Per issue #2665, that command should be run daily, after the existing `gh-data-export` command which exports data from Github. 
I …
> [Issue 2665] Add gh-transform-and-load command to scheduled jobs

- infra/analytics/app-config/env-config/scheduled_jobs.tf
Fixes #2665 
Added scheduled job to run `make init-db` 
The GitHub data export, transform, and load job (see https://github.com/HHS/simpler-grants-gov/pull/2759) depends on a certain schema existing in Postgres. This PR creates a job to ensure the schema exists. 
> [Issue 2665] Add new job to initialize EtlDb

- .github/workflows/cd-analytics-infra.yml
- .github/workflows/cd-analytics.yml
- .github/workflows/cd-api-infra.yml
- .github/workflows/cd-api.yml
- .github/workflows/cd-frontend-infra.yml
- .github/workflows/cd-frontend.yml
Platform's assertion is this: whenever a deploy fails for any reason, it cancels the deploy, which locks the other 3 jobs. Those 3 jobs remain locked indefinitely. On the next deploy, every job but 1 is locked, but the other 3 jobs fail because they were locked prior, which causes 1 first job to be canceled, and thusly all 4 jobs are locked. It's an avalanche effect. Whenever 1 deploy fails, all 4 fail that point onwards.
> [no ticket] Fix infinite state locks

- .github/workflows/cd-analytics.yml
- .github/workflows/cd-api.yml
- .github/workflows/cd-frontend.yml
- .github/workflows/ci-analytics-vulnerability-scans.yml
- .github/workflows/ci-analytics.yml
- .github/workflows/ci-api-vulnerability-scans.yml
- .github/workflows/ci-api.yml
- .github/workflows/ci-frontend-vulnerability-scans.yml
- .github/workflows/ci-frontend.yml
Fixes #2781
- PRs only run vuln scans if relevant files have changed
- Deploys still run vuln scans
I tried to sneak "skip vuln scans for dev deploys" but that's a little bit more involved so it'll come in another package
I haven't! So hopefully it's not fully of typos
> [Issue #2781] Only run vuln scans if the relevant files have changed

- .github/labeler.yml
Followup to https://github.com/HHS/simpler-grants-gov/pull/2769
The labeler was still broken, unfortunately
> [no ticket] fix labeler

- .github/workflows/ci-frontend-e2e.yml
- frontend/docker-compose-release.yml
- frontend/tests/playwright.config.ts
Fixes #2798
Update e2e tests so they are sharded across 3 processes that run in parallel. Time per test reduced by a couple of mins. More importantly the tests seem less flaky. This not as big a deal now but the tests should scale as we grow.
> [Issue ##2798] Break up e2e tests

- frontend/src/components/search/SearchPaginationFetch.tsx
- frontend/src/components/search/SearchResults.tsx
- frontend/src/components/search/SearchResultsHeaderFetch.tsx
- frontend/src/components/search/SearchResultsListFetch.tsx
- frontend/tests/components/search/SearchResults.test.tsx
- frontend/tests/pages/search/page.test.tsx
Fixes #2770
The task here was to fix the current situation in which the search page is making 4 identical requests to the API on each page load.
To do this, instead of making individual requests in each of the search components that require search result data, we make one request in the top level component, and pass the unresolved Promise down to each child component, where it can resolve and provide data upon resolution.
Note that Next / React's request memoization does not work in this case because our search call is "POST" request and memoization only works on "GET"s.
1. visit an search page on main while tailing API docker logs `docker logs grants-api -f`
2. _VERIFY_: 4 separate "start request" logs are visible
1. visit a search page on this branch while tailing API docker logs …
> [Issue #2770] deduplicate search requests

- api/tests/src/data_migration/transformation/test_transform_oracle_data_task.py
Fixes <Unticketed>
Fixes unit tests that broke after a recent rename of agency fields
Changed the name in one PR, and adjusted tests in a separate, but forgot to reconcile them before merging both to main.
> [Unticketed] Fix test that was using incorrect name for agency field after rename

- analytics/config.py
- analytics/src/analytics/integrations/db.py
Partially Fixes #2665
Added `sslmode` to Postgres connection string. Also added some temporary logging to help troubleshoot db connection failures from analytics code. I will remove the logging in a future PR, as soon as I find the cause of the db connection failures.  
Analytics step functions have been deployed but when they execute their attempted connections to Postgres always fail. 
> [Issue 2665] Add temp logging to help troubleshoot db connection failures 

- analytics/config.py
- analytics/src/analytics/integrations/db.py
Partially Fixes #2665 
Adds db name to Postgres connection url; removes logging
> [Issue 2665] Add db name to connection url and remove logging

- frontend/src/components/opportunity/OpportunityDescription.tsx
- frontend/src/utils/generalUtils.ts
- frontend/tests/components/opportunity/OpportunityDescription.test.tsx
- frontend/tests/utils/generalUtils.test.ts
Fixes #2776
A bug exists in the markup parsing functionality that splits opportunity description strings, such that when content is provided that contains forward slashes within a tag that are not closing tag indicators, the parsing breaks. This means anything with a link tag likely will break, ex. `<a href="http://google.com">`.
This adds functionality to the parsing to ignore anything that is contained in quotes within a tag.
Along with this, the example opportunities that exhibited the bug also exhibited cases where the majority of the description is wrapped in a single tag, creating a case where the parser is essentially unable to split the content without breaking the markup. In this case, I'm assuming we'd want to hide the "show more" link, as it doesn't do anything, so I …
> [Issue #2776] fix broken markup parsing when links are present

- .github/workflows/vulnerability-scans.yml
Very nearly fixes #2496
I'm not committing to this 100% solving #2496 because the daily cronjob can fail (on trivy rate limits) which would just mean we are back in the same situation we have always been in. So I want to add tries on this stuff because I can call the issue fully solved.
90% of the meat is this PR is pulled from Trivy's docs, I don't know anything about the `oras` stuff
> [Issue #2496] cache trivy

- api/openapi.generated.yml
- api/src/api/opportunities_v0/opportunity_blueprint.py
- api/src/api/opportunities_v0_1/opportunity_blueprint.py
Fixes #2847
Hide the v0/v0.1 endpoints from the OpenAPI docs
The endpoints will continue to function, we just tell the processes that APIFlask uses to generate the OpenAPI spec to skip these endpoints. The endpoints continue to work uneventfully.
Note: we use these already for a few things, as we also use blueprints to define backend API tasks with this flag set.
What things look like now:
> [Issue #2847] Hide v0/v0.1 opportunity endpoints from swagger

- .github/linters/scripts/set-points-and-sprint.sh
- .github/workflows/lint-set-points-and-sprint.yml
Removes the step in which a comment is posted to an issue that is closed without a sprint or story points. This was per @coilysiren and @mxk0 request to help reduce noise on tickets.
Fixes #2833 
- Removes comment step - details are still being written to the action log
- Limits concurrency to 1 - which prevents this linter from running multiple times on the same issue when it's closed
This is hard to test until we merge it, but once we do issue #2833 should get the sprint and points value set, without a comment being posted.
> Screenshots, GIF demos, code …
> [Issue #2833] Turn off comment in sprint reporting linter

- frontend/package.json
- frontend/src/components/Header.tsx
- frontend/src/components/search/SearchBar.tsx
- frontend/src/hooks/useSearchParamUpdater.ts
- frontend/tests/components/Header.test.tsx
- frontend/tests/components/search/SearchBar.test.tsx
- frontend/tests/pages/search/page.test.tsx
Fixes #2732
Fixes a bug where the search bar does not clear when clicking "search" on the nav while on the search page.
The solution I came up with was to append a query param to the search nav item when on the search page, whose presence is a signal to the page to clear the search bar.
The approach is not ideal, but a fix requires knowing when a navigation has occurred, and Next does not provide a simple way to know that without relying on something like global state.
1. on this branch, visit the search page
2. enter text in the search bar
3. click the "search" nav item
4. _VERIFY_ the search bar is cleared when the page refreshes
> [Issue #2732] clear search input when clicking search nav link

- .dockleconfig
- .github/workflows/ci-analytics.yml
- analytics/Dockerfile
- analytics/poetry.lock
- analytics/pyproject.toml
Upgrade Analytics to Python 3.13
The API has already done this upgrade, Python 3.13 has very few impactful changes (mostly experimental features you need to enable). Doing this to try to resolve some build issues I'm seeing in CI/CD, especially regarding the renovate upgrades that are being attempted: https://github.com/HHS/simpler-grants-gov/pull/1994
> [Unticketed] Upgrade Analytics code to Python 3.13

- frontend/src/components/Header.tsx
- frontend/tests/e2e/index.spec.ts
- frontend/tests/e2e/playwrightUtils.ts
- frontend/tests/e2e/search/search-loading.spec.ts
- frontend/tests/e2e/search/search.spec.ts
Fixes #2619
Handles 4 conditions where we are not currently hiding the mobile nav but should be
1. on this branch, open up the app in a tablet or mobile sized viewport (less than 1024px wide)
2. open the mobile menu by clicking "menu"
3. click a menu option
4. _VERIFY_: the menu closes
5. reopen the menu
6. click somewhere in the app other than the menu
4. _VERIFY_: the menu closes
5. reopen the menu
6. press the escape key on your keyboard
4. _VERIFY_: the menu closes
5. reopen the menu
6. resize your viewport above 1024px
4. _VERIFY_: the menu closes
9. resize your menu back below 1024px
10. _VERIFY_: the menu automatically reopens (since it was not explicitly closed - not sure if this is desired behavior but it's what we've got right now without introducing JS media queries, which I …
> [Issue #2619] hide mobile nav under correct conditions

- frontend/src/components/Header.tsx
- frontend/tests/components/Header.test.tsx
Fixes #2440
Add link to site name in the header. Removes link if you are on the homepage. I don't love the user experience of sites that don't do that with their logo.
I looked at testing the link change but couldn't get it working timeboxing myself https://github.com/vercel/next.js/discussions/42527 .
> [Issue #2440] Update Header.tsx for index link

- infra/api/service/main.tf
- infra/modules/service/draft_documents.tf
- infra/modules/service/main.tf
I really should have caught this in code review TBH ... but the s3 bucket needs to be defined inside of the module, because it uses variables only present inside of the module.
https://github.com/HHS/simpler-grants-gov/actions/runs/11898376420/job/33154738145
```
-/+ resource "aws_ecs_task_definition" "app" {
~ arn                      = "arn:aws:ecs:us-east-1:315341936575:task-definition/api-dev:272" -> (known after apply)
~ arn_without_revision     = "arn:aws:ecs:us-east-1:315341936575:task-definition/api-dev" -> (known after apply)
~ container_definitions    = jsonencode(
~ [
~ {
~ environment            = [
{
name  = "DB_USER"
value = "app"
},
+ {
+ name  = "DRAFTS_S3_BUCKET_ARN"
+ value = "arn:aws:s3:::api-dev-documents-draft20241118182345535400000001"
},
{
name  = "ENVIRONMENT" …
```
> [no ticket] move drafts s3 bucket location

- infra/api/app-config/staging.tf
- infra/frontend/app-config/staging.tf
Relates to #2475
I would like to do the load test in staging, a) because it should be more stable than dev and b) because I don't want to mess up our prod analytics
> [Issue #2475] Scale staging to the same numbers as prod

- infra/analytics/metabase/main.tf
Fixes #2938 
Switch to Metabase Enterprise image
We need to run the Enterprise image to enter the details for our Pro license
> [Issue #2938] Switch to Metabase Enterprise to allow us to enter a License

- OPERATIONS.md
- infra/api/app-config/env-config/outputs.tf
- infra/api/app-config/env-config/variables.tf
- infra/api/service/main.tf
- infra/frontend/app-config/env-config/outputs.tf
- infra/frontend/app-config/env-config/variables.tf
- infra/frontend/app-config/prod.tf
- infra/frontend/service/main.tf
Relates to https://github.com/HHS/simpler-grants-gov/issues/2475
- Makes CPU and memory a variable
- Bumps the frontend's CPU and memory up to the numbers the API is using (they just seemed like a good set of numbers to use 🤷🏼‍♀️)
This will help the frontend be more resilient!
> [Issue #2475] Rescale frontend CPU and memory

- infra/modules/service/autoscaling.tf
Fixes #2475
- Changes the ASGs to evaluate scale-out potential every 5 seconds
- Changes to ASGs to target 50% maximum CPU and memory when performing scaling actions
During load tests, I found that the frontend wasn't scaling up quickly enough to meet demand. I'm hoping that this auto-scaling configuration will help alleviate that.
> [Issue #2475] Scale Out the ASGs more aggresively

- infra/api/app-config/env-config/scheduled_jobs.tf
Turns out the ELT process in dev was running while doing nothing - noticed when looking at some data there that nothing had updated recently (since I last manually ran in dev).
> [Unticketed] Enable ELT process in dev

- .github/workflows/ci-cron-vulnerability-scans.yml
- api/src/api/users/user_routes.py
- api/src/api/users/user_schemas.py
- api/tests/src/api/users/test_user_route_token.py
Fixes #{[2648](https://github.com/HHS/simpler-grants-gov/issues/2648)}
Added `/token/logout` endpoint 
Added `LogoutResponseSchema` response schema
Added success and invalid token tests
> [Issue 2648] Add signout endpoint

- analytics/src/analytics/integrations/etldb/etldb.py
- analytics/src/analytics/integrations/etldb/main.py
Fixes #918
Replaced `print` with `logger.info` in `analytics/integrations/etldb`
> [Issue 918] Replace analytics print statements with logger.info

- .gitignore
- api/artillery-load-test.yml
- frontend/Makefile
- frontend/artillery-load-test.yml
Relates to #1884
Scales the artillery config up to "the site falls down" numbers, so that we can see exactly what the failure cases are for our website.
Unless we are testing for DDOS protection, we should never need to test artillery with higher numbers than this. These numbers are _**very**_ high.
We tested this already in staging, and it does in fact break the site. Or at least, it does with 4 people running it.
> [Issue #1884] make artillery very aggressive

- api/tests/lib/seed_local_db.py
- api/tests/src/db/models/factories.py
- frontend/src/utils/generalUtils.ts
Fixes #2943
Fixes a bug in the markup split logic that could result in markup containing quotation marks to not be properly evaluated
1. `make db-seed` on this branch
2. visit the opportunity page for a seeded record containing markup in the description
3. _VALIDATE_: description content is collapsed at the correct point and markup is not broken
> [Issue #2943] markup split typo bugfix

- .grype.yml
- api/Dockerfile
Fixes #3017
I figured this out overnight. If you uninstall first, it removes all the files, then a re-install is totally fresh. This fixes our postgres vuln problem.
The vuln scans are still failing... on two totally totally different problems (libc and tornado)
> [Issue #3017] fix the postgres vulnerability

- api/tests/src/data_migration/test_copy_oracle_data.py
Fixes #3050 
Make sure we're escaping single quotes in our DB strings
Tests started failing due to a string with "children's" in it
All tests are now passing locally
> [Issue #3050] Make sure we escape single quotes

- infra/modules/service/autoscaling.tf
At 50% memory, the frontend hits that memory cap easily and immediately gets cycled out. I wasn't really expecting this behavior, but you live and you learn.
Increases the memory target to 99%, so nextjs only spins up new containers when after containers max out their cache. This won't meaningfully impact the backend, because the because the backend doesn't have an infinitely* scaling cache.
\* There's not significant indication that the nextjs cache is infinitely scaling. It might just scale higher than our current memory numbers.
I also increased the CPU target to 75%, which may come back to bite me I dunno. We'll see.
> [no ticket] Use higher ASG targets

- .github/workflows/ci-cron-vulnerability-scans.yml
Changes the vuln scan cronjob to both:
- have an explicit `needs` keyword
- always run every vuln scan on every app
Right now the setup for the cron vuln scans is nonideal, this is shown here:
There are two problems here:
- the matrix fails fast, which means that if one scan fails, the other scans won't get a chance to cache
- there is a `needs` statement missing on the slack job, so it doesn't wait for the vuln scans to complete before it alerts slack. In practice this means that it will never alert slack (and in my experience, it never has)
> [no ticket] fix cron vuln scan logic (hopefully)

- .github/workflows/build-and-publish.yml
- .github/workflows/cd-analytics-infra.yml
- .github/workflows/cd-api-infra.yml
- .github/workflows/cd-frontend-infra.yml
- .github/workflows/cd-storybook.yml
- .github/workflows/check-infra-auth.yml
- .github/workflows/ci-analytics.yml
- .github/workflows/ci-api.yml
- .github/workflows/ci-frontend-a11y.yml
- .github/workflows/ci-frontend-e2e.yml
- .github/workflows/ci-frontend.yml
- .github/workflows/ci-infra.yml
- .github/workflows/ci-openapi.yml
- .github/workflows/ci-project-linters.yml
- .github/workflows/ci-wiki-links.yml
- .github/workflows/database-migrations.yml
- .github/workflows/deploy-metabase.yml
- .github/workflows/deploy.yml
- .github/workflows/infra-service.yml
- .github/workflows/lint-set-points-and-sprint.yml
- .github/workflows/send-slack-notification.yml
- .github/workflows/vulnerability-scans.yml
> [Issue #3031] install ubuntu 22 LTS, instead of latest

- frontend/src/components/opportunity/OpportunityCTA.tsx
Fixes #2851
Adds styling to ensure cta button sits beneath text at all viewport sizes
1. load an opportunity detail page on this branch
2. resize viewport from desktop to mobile size
3. _VERIFY_: at all viewport sizes the cta button sits beneath the cta text 
Compare to screenshot in the ticket
> [Issue #2851] always display cta button beneath text

- infra/api/app-config/staging.tf
- infra/frontend/app-config/staging.tf
Sets staging scaling back down to devs numbers, rather than prods. This means that the absolute load test numbers are no longer useful to test in staging with.
> [no ticket] Scales staging costs back down

- .github/workflows/deploy.yml
- Makefile
- bin/deploy-release.sh
- infra/analytics/service/variables.tf
- infra/api/service/main.tf
- infra/api/service/variables.tf
- infra/frontend/service/variables.tf
Relates #3003
Adds the following environment variables to API deployments:
- DEPLOY_GITHUB_REF
- DEPLOY_GITHUB_SHA
- DEPLOY_TIMESTAMP
You can find the definitions for these values here: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables
https://us-east-1.console.aws.amazon.com/ecs/v2/task-definitions/api-dev/288/json?region=us-east-1
^ note that terraform doesn't provide a UNIX timestamp, which I'm a bit bummed about. But maybe we only put the timestamp into the healthcheck, and keep it as is?
> [Issue #3003] Add deployment info

- analytics/Dockerfile
- analytics/pyproject.toml
Exposes the `analytics` CLI entry point for the Docker image that allows us to run `docker run <image> etl db_migrate` as part of the CI/CD pipeline. 
Fixes #3066 
- Edits the `poetry run pip install` to use `--no-cache-dir` and use a wildcard for the `dist/*.whl` so that users don't have to change that line if we bump the version.
To prove that the entry point is available to run from the Docker container (without `poetry run`) do the following steps:
1. Checkout the current PR
2. Run `make release-build` from the root of the `/analytics/` sub-directory …
> [Issue #3066] Expose analytics CLI entry point in Docker

- api/local.env
- api/openapi.generated.yml
- api/src/api/healthcheck.py
- api/src/logging/decodelog.py
- api/src/logging/flask_logger.py
- api/src/util/deploy_metadata.py
- api/tests/src/api/test_healthcheck.py
- api/tests/src/util/test_deploy_metadata.py
Fixes #3003
Add release info to logs & healthcheck response.
To aid in answering "when did we last deploy" we've added info to the healthcheck endpoint.
Also to aid in debugging, the logs also contain some of the same info.
Logs (human-readable locally before I filtered them out as they're static/not useful locally):
Healthcheck response:
> [Issue #3003] Add release info to logs and healthcheck endpoint

- frontend/package.json
- frontend/src/app/[locale]/research/ResearchMethodology.tsx
- frontend/src/i18n/messages/en/index.ts
- frontend/tests/e2e/research.spec.ts
Fixes #773
Adds a button linking to ethnio form for potential research participants, as matching the figma here:
https://www.figma.com/design/FGxWtAgToKhehLJCiuy1zL/Simpler.Grants.gov-Project?node-id=67-15381&node-type=frame&t=xufn7BqnxbENUmXq-0
1. open the research page on this branch
2. _VERIFY_: compare to figma, make sure it looks right
3. click on the "sign up to join a usability study" link
4. _VERIFY_: the ethnio link opens up in a new tab
> [Issue #773] add research participant cta

- frontend/next.config.js
- frontend/package.json
Fixes #2625
Explicitly set the headers for different parts of the app so they are cached by clients and the CDN appropriately.
> [Issue #2625] set max-ages for app pages

- infra/api/app-config/env-config/scheduled_jobs.tf
Fixes #3134
Add a scheduler to run this task.
Last bit of work for the export to run nightly.
> [Issue #3134] Add schedule for `export-opportunity-data`

- infra/modules/service/cdn.tf
`default_root_object` does the following:
> [default_root_object](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#default_root_object-1) (Optional) - Object that you want CloudFront to return (for example, index.html) when an end user requests the root URL.
It sends the user somewhere when they request `/`, like for example to the literal route `index.html`. Well we don't have an `index.html`. So I figured, `/` should just go to `/`, right? Wrong. When you tell `/` to go to `/` what you end up with is an infinite redirect loop. This me an undue amount of time to debug 😅 
I have no idea why AWS allows you to shoot yourself in the foot like this. Pointing `default_root_object` to `/` should return a validation error on AWS's end...
> [no ticket] fix silly infinite redirect issue

- frontend/src/app/[locale]/layout.tsx
Fixes #3121 
To gain access to Google Search Console Tools we need to verify we control the simpler.grants.gov site
The Google Tools in question allow us to see the crawl data from Google for our site, be alerted to and troubleshoot problems with our site's content, structured metadata, and crawlability. It will also let us better understand the Google Search queries that include us as a result as well as what gets us clicked on.
> [Issue #3121] Verify site ownership with Google

- api/src/util/deploy_metadata.py
- api/tests/src/util/test_deploy_metadata.py
For our deploy metadata, allow the value to be null (however unlikely) to avoid breaking our jobs
This shouldn't ever be null, but we did hit a weird case where it was due to manual testing which broke our ECS tasks in dev for a few days. This just makes a non-required field, actually non-required. Very useful, but not required.
> [Unticketed] Allow for null deploy metadata

- .github/workflows/deploy.yml
- Makefile
- bin/deploy-release.sh
- infra/analytics/service/variables.tf
- infra/api/service/main.tf
- infra/api/service/variables.tf
- infra/frontend/service/variables.tf
- infra/modules/service/main.tf
- infra/modules/service/variables.tf
Relates to #3003, followup from https://github.com/HHS/simpler-grants-gov/pull/3072
Completes 50% of https://github.com/HHS/simpler-grants-gov/issues/3149
- adds DEPLOY_WHOAMI to the deploy metadata environment variables
- adds them to the module layer so they're present on every service we deploy
- removes from the CLI inputs because they're being input by terraform shell commands now (which is something I should have thought about sooner!)
From Github actions:
Locally:
> [Issue #3003] Get deploy metabase from shell commande

- documentation/frontend/analytics.md
- documentation/frontend/environments.md
- frontend/src/app/[locale]/layout.tsx
- frontend/src/constants/environments.ts
- infra/frontend/app-config/env-config/environment-variables.tf
Fixes #3033
Cleans up after bug introduced in https://github.com/HHS/simpler-grants-gov/pull/3001/files and fixed in https://github.com/HHS/simpler-grants-gov/pull/3013
Adds some more detail to the documentation and adds a diagram as well.
1. start up the app locally
2. in dev tools, search the dom for "tagman"
3. _VERIFY_: two different script tags are found, one of which points to the GTM id found in the code, the other of which points to a placeholder / dummy id "G-GGGGGGG"
This should also be verified in DEV after merge
** PLEASE REVIEW THE DIAGRAM AS WELL **
> [Unticketed] clean up messy GA env var situation

- .github/linters/queries/getItemMetadata.graphql
- .github/linters/scripts/set-points-and-sprint.sh
- .github/workflows/ci-project-linters.yml
Updates issue linter to only update assignee, story points, and sprint values if the issue is closed by a PR.
- Fixes #2834 
- Fixes #2561 
- Adds linked PR details to GraphQL query
- Skips updates if issue has no linked PR
- Assigns PR author to issue
1. Checkout PR
2. Find an issue that _wasn't_ closed by a PR
3. Unset that issues Story Points or Sprint value in project HHS/13 (Simpler.Grants.gov product backlog)
4. Run the following command from the command line:
```
./scripts/set-points-and-sprint.sh \
--url "<issue-url>" \
--org "HHS" \
--project 13 \ …
```
> [Issues #2834 and #2561] Only lint issues closed by PR

- frontend/artillery-load-test.yml
Fixes https://github.com/HHS/simpler-grants-gov/issues/1884
Adds durations to all the artillery stages. I added durations before, and it didn't seem like they were being respected. But I added these ones, and now they are, I think? I dunno. I hate Artillery's documentation.
```
--------------------------------
Summary report @ 00:05:09(-0800)
--------------------------------
apdex.frustrated: .............................................................. 537
apdex.satisfied: ............................................................... 1087
apdex.tolerated: ............................................................... 853
errors.ETIMEDOUT: .............................................................. 45428
http.codes.200: ............................................................... …
```
> [Issue #1884] Finishes a load test (finally)

- infra/modules/service/main.tf
Changes the s3 bucket ARNs to URLs, because our libraries want URLs
This will merge conflict with https://github.com/HHS/simpler-grants-gov/pull/3068
> [no ticket] Use s3 bucket URLs instead of ARNs

- api/src/logging/config.py
- api/tests/conftest.py
Add the ability to adjust log level in env var
Use that env var to make a log message from New Relic stop appearing in unit tests
You can configure the log level of any logger, which we already have static defaults for many in our logging config. In this case, I didn't want a default as there was an errant log message propagating from New Relic every time we ran our unit tests.
Easiest fix was just to hide the log message, and figured I'd add some flexibility for it while I was at it, borrowing some code from past projects.
Before this change, if you ran `make test` it would run successfully, but always dump out this annoying error message.
The error is likely just the app closing before New Relic does and while we could try to rework something to make that not happen, it's happening when …
> [Unticketed] Fix a noisy log from New Relic in tests

- frontend/next.config.js
Fixes #2625
Keeps /subcribe from being cached so form still works with the CDN.
> [#2625] Update next.config.js for /subcribe caching

- api/src/app.py
Fixes #3191
Change local env bool flag to enable auth to instead use `ENABLE_AUTH_ENDPOINT` env var.
We used to key this off local env but swapping out for the preferred approach.
> [Issue #3191] Adjust auth logic initialization to be configured by env var

- api/local.env
- api/src/task/__init__.py
- api/src/task/analytics/__init__.py
- api/src/task/analytics/create_analytics_db_csvs.py
- api/tests/src/task/analytics/test_create_analytics_db_csvs.py
Fixes #3148
Create a task we can run that will generate CSV extracts for a given set of tables
This dataset will be a sort of input to an analytics process being written. We'll pull these extract files and load them into the analytics database.
This uses pretty routine `copy` commands from Postgres which is very very efficient at reading/writing from CSV files.
https://www.postgresql.org/docs/current/sql-copy.html
Running `make cmd args="task create-analytics-db-csvs"` locally to get the script going with ~35k opportunities in my DB takes about 2 seconds for these 5 tables:
Example files generated:
```csv
opportunity_id,opportunity_number,opportunity_title,agency_code,opportunity_category_id,category_explanation,is_draft,revision_number,modified_comments,publisher_user_id,publisher_profile …
```
> [Issue #3148] Generate extracts of tables for opportunity data

- frontend/src/styles/_uswds-theme.scss
Fixes #3217 
This change updates the USWDS theme file to use the brand color palette prescribed in the [Figma](https://www.figma.com/design/FGxWtAgToKhehLJCiuy1zL/Simpler.Grants.gov-Project?node-id=1503-695&node-type=frame&t=InZzQfGYsDVKfze4-0). 
It's not easy to preview all these changes, as we're not using all the colors yet. But all the variables are defined to work with the brand colors now. You can view the site to confirm that the theme is applying the colors to the links, buttons, and background elements. 
#3227 should be merged into this before merging into `feature/brand`
Note the following in this before and after: 
- Link color changed from blue to green in the "An official website" banner at the top
- Visited link color changed to the right violet in the beta alert
- Hero …
> [Issue #3217] update color settings to match brand

- frontend/src/styles/_uswds-theme-custom-styles.scss
- frontend/src/styles/_uswds-theme.scss
Fixes #3218
Adds custom CSS for all the button styles
This is done w/ custom styles, not settings, because USWDS assume that you want to use specific colors from your theme palette. We also need to ad the custom bottom border. 
This should be merged into #3226 before it's merged into `feature/brand`
Here's a temp change (not committed) of the Subscribe page to include all the button variants:
> [Issue #3218] add custom button styles

- api/src/api/users/user_routes.py
- api/src/auth/login_gov_jwt_auth.py
- api/src/services/users/login_gov_callback_handler.py
- api/tests/src/api/users/test_user_route_login.py
- api/tests/src/auth/test_login_gov_jwt_auth.py
Fixes #3129
Validate the nonce value when receiving the token back from login.gov
Delete the login gov state value after we've used it once
Some restructuring to handle the multi-commit approach required here
We delete the state object after processing a response that uses it to prevent any sort of replay attack (ie. that state should be used for a single session of logging in, it shouldn't ever be used again). If a user navigates to the login page again later, we'd make a new state anyways, so the data isn't needed anyways.
As for the nonce, this is a UUID we generated when we first redirected someone to login.gov - login.gov doesn't echo it back to us until we are parsing the response from the token endpoint. In short, by checking for this, we protect ourselves from replay attacks.
See: …
> [Issue #3129] Validate that the nonce matches in login gov token response

- api/src/auth/api_jwt_auth.py
- api/tests/src/auth/test_api_jwt_auth.py
Fixes #3199
Adds `user_id` to token. Updates tests.
> [Issue #3199] Add the user_id to the token returned by our login flow

- api/src/search/backend/load_opportunities_to_index.py
- api/tests/src/search/backend/test_load_opportunities_to_index.py
Fixes #3204 
If an opportunity is connected to a test agency, do not load it into the search index
Fixed a bug with how incremental updates/deletes worked that was deleting everything if it wasn't in an update
Certain agencies are marked as test agencies, and will be excluded from appearing in the left-hand navigation already. However, that doesn't stop you from finding them in search results by other means. Even though the number of test records appearing in search is small (5 at the time of writing), we'll be cautious and just filter them all out, which lets us potentially do more in the future as well.
We also handle deleting anything that already exists in the incremental job - that likely won't matter in most cases, but if an agency is ever marked as a test that wasn't previously, …
> [Issue #3204] Remove opportunities connected to test agencies from search results

- frontend/src/styles/_uswds-theme-custom-styles.scss
- frontend/src/styles/_uswds-theme.scss
Fixes #3124 
This change adds the Newsreader font from the Google Fonts hosting service, sets the sans serf font to Public Sans, defines a USWDS type token for Newsreader, and sets the serif font to Newsreader (with the fallback set to Georgia, per brand guidelines). 
When you view the site, all type should be Public Sans or Newsreader. You should no longer see Source Sans Pro or Merriweather. This change just changes the fonts. There will be subsequent PRs to use the right fonts in the right places so that the design looks better. 
Before (left) & after (right)
> [Issue #3214] update fonts to Public Sans, Newsreader

- infra/frontend/service/main.tf
- infra/frontend/service/variables.tf
- infra/modules/service/cdn-logs.tf
- infra/modules/service/cdn.tf
Fixes #680
- Uncomments the CDN
- Adds a TLS policy
- Fixes adding the cert to the CDN when applicable
I deployed this to both dev (without the cert) and staging (with the cert) to test
> [Issue #680] Adds the CDN back

- api/src/auth/api_jwt_auth.py
- api/src/services/users/login_gov_callback_handler.py
- api/tests/src/auth/test_api_jwt_auth.py
Fixes #3246
Add email address to JWT token if exists.
A user can have multiple linked external user records, but for now we'll assume they have a single one (the Login.gov one) where the email is stored.
See addition to unit test covering scenarios where emails exists and does not exist.
> [Issue #3246] Put the users email address in the token returned by our auth logic

- api/src/services/opportunities_v1/search_opportunities.py
Fixes #3183
Modify the search facet count logic to allow up to 1000 unique agencies in response
By default we configured the size to be 25 arbitrarily. There are about 700 agencies with opportunities in prod, so configured a number a bit above that for now.
We might want to consider allowing the user of the API to specify the facets they want in the future.
I loaded a lot of opportunities into the search index, and the response for facet counts now has all of the agencies we have configured locally with is about 80.
> [Issue #3183] Make search facets for agencies return more than 25 agencies

- frontend/src/app/[locale]/user/LogoutButton.tsx
- frontend/src/app/[locale]/user/page.tsx
- frontend/src/app/api/auth/logout/route.ts
- frontend/src/app/api/clientUserFetcher.ts
- frontend/src/app/api/endpointConfigs.ts
- frontend/src/app/api/fetchers.ts
- frontend/src/app/api/userFetcher.ts
- frontend/src/hoc/withFeatureFlag.tsx
- frontend/src/services/auth/UserProvider.tsx
- frontend/tests/api/auth/callback/route.test.ts
- frontend/tests/api/auth/logout/route.test.ts
- frontend/tests/services/auth/useUser.test.tsx
Fixes #2656
Creates a Node route that can be used to log out a user
* calls the API logout endpoint
* removes client side cookie
Also adds fetch function to use to call the API logout route and a dummy logout button to use for testing
1. set `LOGIN_FINAL_DESTINATION` in api env to "localhost:3000/api/auth/callback"
2. run `make setup-env-override-file` in api
3. in new private window visit http://localhost:8080/v1/users/login
4. enter something and click the button
5. _VALIDATE_: user page loads with "session created" message
6. _VALIDATE_: entries are created in the local user and user_token_session DB tables
7. _VALIDATE_: client side "session" cookie is present in browser
8. click logout button
9. _VALIDATE_: page shows "logged out" message
6. _VALIDATE_: entries are removed in the …
> [Issue #2656] logout route

- .grype.yml
Ignore [GHSA-v778-237x-gjrc](https://github.com/advisories/GHSA-v778-237x-gjrc)
Cleaned up old ignores that _should_ be fixed by now
This vulnerability is in a dependency pulled in by the Github CLI. A [fix was made](https://github.com/cli/cli/commit/1af421012e5e7a648577e091e5a094a80b75d720) but no new release has occurred, likely due to the holidays. https://github.com/cli/cli/releases
As this vulnerability already would exist in our image, ignoring it for now seems uneventful, and the issue shouldn't persist beyond the holidays.
> [Unticketed] Ignore vulnerability for issue with pending fix

- api/tests/src/db/models/factories.py
Remove ID setting in factories for agency to avoid issue where tests tried to create an ID that already was created by factory
When our code runs and creates a record with an integer ID it uses a DB sequence to get the next value. However, the factory was managing its own sequence which meant that if a test tried to create an agency, it ran into an issue.
We don't need this sequence logic for anything and can rely on the DB to avoid any conflicts
> [Unticketed] Fix a flaky test due to agency ID conflict

- api/src/api/users/README.md
- api/src/auth/README.md
- api/src/services/users/README.md
- api/tests/src/api/users/test_user_route_login.py
- documentation/api/authentication.md
Fixes #3240
Added documentation for the authentication logic
Hopefully covered most of the useful auth details, please let me know if anything isn't clear or should have more detail
> [Issue #3240] Write docs for API authentication logic

- analytics/poetry.lock
- analytics/pyproject.toml
- api/poetry.lock
- api/pyproject.toml
Fixes #3356 
Upgrade Jinja2 to 3.1.5 in API and Analytics projects
The currently installed Jinja version was flagged for a medium vulnerability in CI
More info on the run here: https://github.com/HHS/simpler-grants-gov/actions/runs/12481427243/job/34833926210#step:6:17
> [Issue #3356] Upgrade Jinja2 to 3.1.5

- frontend/src/components/search/SearchFilterAccordion/SearchFilterAccordion.tsx
- frontend/src/components/search/SearchFilterAccordion/SearchFilterSection/SearchFilterSection.tsx
- frontend/tests/components/search/SearchFilterAccordion/SearchFilterAccordion.test.tsx
- frontend/tests/e2e/search/search-no-results.spec.ts
- frontend/tests/e2e/search/search.spec.ts
- frontend/tests/e2e/search/searchSpecUtil.ts
- frontend/tests/e2e/search/searchUtil.ts
- frontend/tests/utils/generalUtils.test.ts
Fixes #2144
* adds e2e tests for "select all" and "clear all" filter functionality, including for agencies / nested filters
* fixes bugs with nested filters that showed incorrect selected filter counts and did not correctly clear selected filters
1. start the app on main
2. from the search page, click "select all" at the top level of the agencies filter
3. _VALIDATE_: the ui suggests that 39 items are selected, when only 21 are
4. open an expander to show nested filter options
5. click "select all" for the nested options
6. _VALIDATE_: top level search options are cleared when nested ones are selected
7. select a top level option
8. click "clear all" under nested section
9. _VALIDATE_: all options are cleared, not just nested ones
1. start the app on this branch
2. from the search page, …
> [Issue #2144] e2e tests for clear/select all filters and fix nested filter bug

- frontend/tests/e2e/search/search.spec.ts
Unticketed issue
Fixes to agency filter E2E test which were intermittently failing in deployed envs and locally
1. run e2e tests locally
2. agency filter test passes
> fix bugs in agency filters e2e test

- frontend/src/components/opportunity/OpportunityDescription.tsx
- frontend/src/i18n/messages/en/index.ts
- frontend/tests/components/opportunity/OpportunityDescription.test.tsx
Issue #3387
Removes grantor phone info from opportunity listing
Requested by Julius
1. start server on this branch and visit an opportunity detail
2. _VERIFY_: no phone information is shown on the page
> [Issue #3387] remove opportunity contact telephone number

- .github/renovate.json
Fixes #2515
Update Renovate's config to use CodeOwners to assign reviewers and ignore Python releases since we need to evaluate those releases more deeply before allowing.
[Renovate Config Docs](https://docs.renovatebot.com/configuration-options/#matchpackagenames)
> [Issue #2515] use CodeOwners to assign reviewers and don't try to upgrade Python

- infra/analytics/service/transfer_access.tf
- infra/modules/service/outputs.tf
- infra/modules/service/s3_buckets.tf
Relates to #3160
- Writes the iterative s3 bucket ids and arns to ssm params
- Reads the api's variants of those ssm params into the analytics application
- Gives the analytics application access to the api's s3 buckets
This creates a dependency between the API infra and Analytics infra. Because of this, there will be a race condition between the two deployments. If a deploy is broken, then the fix is just to deploy again.
> [Issue #3160] Give analytic access to the transfer bucket

- api/openapi.generated.yml
- api/src/api/opportunities_v1/opportunity_schemas.py
- api/tests/src/api/opportunities_v1/conftest.py
- api/tests/src/api/opportunities_v1/test_opportunity_route_search.py
Fixes #3390 
Remove `agency_phone_number` from opportunity GET and search API responses.
Additional context in #3390 and associated ticket.
See updated unit tests.
> [Issue #3390] Remove agency_phone_number from Opportunity/Search API responses

- frontend/src/app/[locale]/process/page.tsx
- frontend/src/app/[locale]/research/page.tsx
Fixes #3401 
- Use the `.bg-base-lightest` utility class (which is the brand's `gray-warm-5`) instead of `. bg-gray-5` 
This is a very subtle color difference that might be hard for some to notice
> [Issue #3401] Use brand color for page section backgrounds

- frontend/src/app/[locale]/process/ProcessProgress.tsx
Fixes #3404
- Switch the utility class of the green checkmark icons in the IconList component on the process page 
This uses a brand green instead of the default `green` token
> [Issue #3404] use brand green for process page icons

- frontend/tests/utils/dateUtil.test.ts
There is currently a use case in the `dateUtil` module that is preventing full unit test coverage. This pull requests covers that use case to get this module to 100% coverage.
The use case is when a date string is passed into `formatDate` and does not have 3 parts delimited by a `-`. When this use case occurs, we expect to log a warning in the console and is tested by this pr.
> Add a unit test case in the dateUtil.test.ts test module to cover the use case mentioned above.
> This change can be tested and verified by running `npm run test` within the ~/frontend directory of this repository.
> You should see the following results of the unit tests.
> [External] Increase test coverage for dateUtil module in frontend.

- infra/modules/service/main.tf
Recently, Doug and Michael observed an issue where database migrations failed because a new task definition needed to update its IAM permissions. This happens because the database migrations deploy "targets" the task definition during the deployment and try to update just that. Then that task definition crashes on startup because it doesn't have the proper permissions.
My theoretical solve for that is: to require the task definition to depend on the IAM roles being updated first. That should prevent an updated task definition from rolling out without its associated permissions.
I just tested this that deploys, setting up a real thorough test case would take too much time I think.
> [no ticket] Update IAM roles before running database migrations

- .github/workflows/ci-frontend-a11y.yml
- .github/workflows/ci-frontend-e2e.yml
Unticketed
Remove linting from e2e and pa11y tests, as that's duplicative with linting already happening in a separate part of ci process
1. _VERIFY_: output for e2e and pa11y runs on this branch do not include the output `Linting and checking validity of types ...`
> [Unticketed] do not lint during e2e tests

- api/tests/lib/seed_local_db.py
A recent change removed the transfer topportunity table, but an import in a utility script wasn't cleaned up. Fixing that here
> [Unticketed] Remove import that is no longer necessary

- api/src/app.py
Fixes #3405 
Add a very high level robots.txt implementation for the API side.
Content provided by the route passes validation and enforces correct crawling restrictions:
> [Issue #3405] Setup API to respond to robots.txt requests

- frontend/src/components/Header.tsx
- frontend/src/components/user/UserControl.tsx
- frontend/src/styles/_uswds-theme-custom-styles.scss
- frontend/tests/components/Header.test.tsx
Fixes #3247
- fix bug where mobile login dropdown appeared on top of mobile menu
- improve spacing on mobile login dropdown
1. run the app on main
2. visit http://localhost:3000 on mobile
3. _VERIFY_: looks like "before" screenshots below
4. restart app on this branch and refresh
3. _VERIFY_: looks like "after" screenshots below
> [Issue #3247] login header follow up fixes

- api/poetry.lock
- api/pyproject.toml
Add dependency on crypto library so other digital signature approaches are available
We use RS256 encryption which requires crypto to be installed: https://pyjwt.readthedocs.io/en/latest/installation.html
Locally this wasn't an issue, but getting an error non-locally. We setup dependencies differently locally, so some test dependency probably brings the library in.
> [Unticketed] Add cryptopgraphy dependency so RS256 is available

- .github/workflows/ci-frontend-a11y.yml
- .github/workflows/ci-frontend-e2e.yml
- .github/workflows/ci-frontend.yml
- frontend/Dockerfile
- frontend/next.config.js
- frontend/package-lock.json
- frontend/package.json
Fixes #2871
All usages of Node in the application upgraded to latest 22 minor version (22.13). This includes:
- github actions
- Dockerfile base image
- package.json engine (this will require local developers to be using the 22.13 <= in order to run npm installs)
- node types package (upgraded to latest available, the versions for this package do not seem to be totally in line with actual node versions)
This also:
- moves linting behavior into the next config from the package script (just for cleanliness)
- upgrades the release Dockerfile base to bookworm from bullseye. This was already done for the build image, I think it was just an oversight that the release image was not upgraded as well.
1. `npm run dev` and do a basic regression test
2. _VERIFY_: app works as normal
3. `npm run …
> [Issue #2871] upgrade to node 22.13

- frontend/src/components/LoginButtonModal.tsx
- frontend/src/components/user/UserControl.tsx
- frontend/src/i18n/messages/en/index.ts
- frontend/tests/components/LoginButtonModal.test.tsx
Fixes #2962
Couple of follow-up items
> [Issue #2962] modal followup

- infra/analytics/app-config/env-config/scheduled_jobs.tf
Fixes #3487
Update scheduled jobs to remove daily generation of sprint and delivery reports. Those reports are now generated in Metabase.
> [Issue 3487] Remove legacy sprint reports from scheduled jobs

- frontend/package.json
- frontend/src/services/auth/session.ts
- frontend/src/services/auth/sessionUtils.ts
- frontend/src/utils/generalUtils.ts
- frontend/tests/services/auth/session.test.ts
Unticketed
* Only set the "secure" parameter on the session cookie to `true` in prod for now, as our lower environments are not set up with SSL yet
* Also adds some logging for future debugging
1. deploy to DEV if necessary 
2. log in
3. _VERIFY_: logged in header state is reflected after successful login
It's pretty clear we need better logging on the NextJS app, creating tickets to deal with that now.
> [Unticketed] fix auth bug - allow non ssl cookies in non-prod

- frontend/src/components/Breadcrumbs.tsx
Fixes #3184 
Use Microdata syntax within the Breadcrumb component
RDFa style metadata was being flagged as missing by Google (position field, specifically). In testing, that seems to be because `<meta property` tags are stripped out by Next's page metadata handling to ensure that the more typical page level header meta tags work as expected via Next's layer for controlling them.
You could see in the existing code that we were setting `<meta property="position" content="{i+1}"/>` however but Google was flagging that property as missing on our Breadcrumbs. In testing, those tags were not showing in the Element Inspector nor when curling the pages directly. So something between our JSX code and the client was stripping the necessary tag. Microdata uses `itemprop` instead of `property` and …
> [Issue #3184] Switch from RDFa to Microdata as meta property tags weren't making it to the client

- frontend/src/app/[locale]/subscribe/actions.tsx
- frontend/src/components/subscribe/SubscriptionForm.tsx
- frontend/src/i18n/messages/en/index.ts
Fixes #3084
Update text for error message on subscribe page
All other changes were made in support of this change, but some notes are potentially helpful here:
- since we're introducing JSX into the actions file it now needs a tsx extension
- it seems like the actions file was not being linted before? There were some typos and linting errors to clean up that were unrelated to the change
- in testing the change it looks like an API key is actually not necessary to get a successful request through to Sendy, which is troubling.
1. start a server with `npm run build && npm start`, and make sure that the `SENDY_API_KEY`, `SENDY_API_URL`, and `SENDY_LIST_ID` env vars are not set anywhere in your system
2. visit http://localhost:3000/subscribe
3. attempt to subscribe
4. _VERIFY_: since you …
> [Issue #3084] update email subscription error message (and related fixes and changes)

- api/src/task/analytics/create_analytics_db_csvs.py
Add `@ecs_background_task` to the analytics export job
Noticed it was missing when I went to check the logs this morning and didn't find everything I expected to
> [Unticketed] Add ecs_background_task to analytics export job

- api/openapi.generated.yml
- api/src/api/users/user_routes.py
- api/src/api/users/user_schemas.py
- api/src/services/users/get_saved_searches.py
- api/tests/src/api/users/test_user_get_saved_searches.py
- api/tests/src/db/models/factories.py
Fixes #3447
Create GET endpoint to return saved searched, accounting for enum values
Add unit tests
This is the final API required for saving user searches in this iteration.
See unit tests
> [Issue #3447] Create API endpoint for GET /users/:userID/save-searches

- frontend/src/app/[locale]/process/page.tsx
- frontend/src/app/[locale]/research/page.tsx
- frontend/src/app/[locale]/search/page.tsx
- frontend/src/app/[locale]/subscribe/page.tsx
- frontend/src/i18n/messages/en/index.ts
Fixes #3510
Updating page meta description text as per ticket requirements
These tests involve checking meta descriptions, which you an either do by inspecting the meta tags in the head of the page's HTML, or with a browser extension of some sort.
2. visit http://localhost:3000
3. _VERIFY_: meta description reads: "Simpler.Grants.gov is improving how you discover, post, and apply for federal discretionary funding on Grants.gov."
3. _VERIFY_: meta description reads: "Search for and discover relevant opportunities using our improved search."
2. visit http://localhost:3000/process
3. _VERIFY_: meta description reads: "Simpler.Grants.gov is improving how you discover, post, and apply for federal …
> [Issue #3510] update page meta descriptions

- infra/api/service/main.tf
- infra/frontend/service/main.tf
- infra/modules/service/cdn-logs.tf
- infra/modules/service/cdn.tf
- infra/modules/service/main.tf
- infra/modules/service/variables.tf
Probably finishes #3097
Adds configuration to the CDN that allows it to operate in 4 modes:
1. With no fronting domain name, and an ALB origin (eg. frontend dev)
2. With a fronting domain name, and an ALB origin (eg. frontend prod)
3. With no fronting domain name, and a S3 origin (eg. API dev)
4. With a fronting domain name, and a S3 origin (eg. API prod)
It's complicated in here 😅 
I tested by deploying to API dev and frontend dev
> [Issue #3097] Adds configuration for S3 CDN

- infra/modules/service/cdn.tf
Fixes https://github.com/HHS/simpler-grants-gov/actions/runs/12815925972/job/35736051716
When deploying from scratch, as opposed to the iterative deploy you would do during testing, you often find small quirks where the order to operations for the deploy are slightly incorrect. This is one of those cases.
> [no ticket] Fix ordering of CDN deploy operations

- api/src/search/backend/load_opportunities_to_index.py
Tell processor to allow the record even if attachments are missing
https://www.elastic.co/guide/en/elasticsearch/reference/current/foreach-processor.html
ignore_missing is defaulted to False. This means if the record has no attachments, it just drops it and moves on. This fix makes it not drop it, and just allow it.
Set `ENABLE_OPPORTUNITY_ATTACHMENT_PIPELINE=false` in the local.env
Run `make db-seed-local` and `make populate-search-opportunities`, without this fix, nothing ends up in the search index.
> [Unticketed] Fix issue where opportunities aren't loaded to search index

- analytics/src/analytics/integrations/github/main.py
- analytics/src/analytics/integrations/github/validation.py
- analytics/tests/integrations/github/test_validation.py
Changes how we validate the response data from the GitHub API.
Fixes #3203 
- Adds new schemas to validate the GitHub output
- Uses those schemas to modify the `transform_project_data()` method
This PR is stacked on top of #3393 
> [Issue #3203] Update GitHub API validation

- api/src/data_migration/transformation/subtask/transform_opportunity_attachment.py
- api/tests/src/data_migration/transformation/subtask/test_transform_opportunity_attachment.py
- api/tests/src/db/models/factories.py
Handle case (by erroring) if an opportunity attachment is null from legacy data
Note that by erroring like this, processing on other attachments will continue.
Hit this issue when testing in dev, forgot that the `file_lob` column that contains the opportunity attachments from the legacy data is a nullable field. Easy enough fix to throw a value error so processing continues and we skip that record.
> [Unticketed] Fix scenario where opp attachment is null

- infra/modules/service/cdn.tf
Accidentally caused by work on #3097
Gaurds against the cause where a given service doesn't have a CDN to deploy _(which is only analytics right now)_
Analytics deploy was broken before this change, and now it's not. I haven't tested API and frontend, but I'm hoping this doesn't break them.
> [Issue #3097] Fix analytics deploy not having a CDN

- api/newrelic.ini
Enable https://docs.newrelic.com/docs/apm/agents/python-agent/configuration/python-agent-configuration/#application_logging.forwarding.context_data.enabled
If I'm reading docs right, this should make it so New Relic automatically includes the `extra` we add to our logs. It already is getting the logs from the API and backend tasks successfully, but only includes the message. This should fix that?
> [Unticketed] Enable context data logging in New Relic

- bin/run-step-function.sh
Functionally procrastination on my part, I wrote this so I could test step functions without having to drop into / out of the AWS console
```bash
$ ./bin/run-step-function.sh analytics prod opportunity-load-csvs
aws stepfunctions start-execution
--state-machine-arn arn:aws:states:us-east-1:315341936575:stateMachine:analytics-prod-opportunity-load-csvs
--name kai-1737665796
View the step function execution in the AWS console:
https://us-east-1.console.aws.amazon.com/states/home?region=us-east-1#/v2/executions/details/arn:aws:states:us-east-1:315341936575:execution:analytics-prod-opportunity-load-csvs:kai-1737665796
```
> [no ticket] Adds a command for running step functions

- infra/analytics/service/main.tf
The prod analytics container is currently OOM'ing on the load csvs job
> [no ticket] Double analytics memory

- .github/CODEOWNERS
Fixes #{ISSUE}
Inspired by PRs like https://github.com/HHS/simpler-grants-gov/pull/3604, which ping everyone for a change that's only relevant to the
The diff is rough, but the functional change is to group the codeowners file by teams, and make the individual `documentation` folders be codeowned by their respective teams.
> [no ticket] Add codeowners to documentation folder

- api/src/data_migration/transformation/subtask/transform_agency.py
Adds a filter to the transform agency task to skip a new field
grants.gov added a new type of field to the TGroups table (the key-value table that stores agency info) which is causing the following error: `Unknown tgroups agency field AllowSubmitWithExpSAM`.
While I'm not sure what this field does exactly (something to do with allowing users to submit even if their SAM validation isn't done), I know we don't need to worry about it for a while as we don't yet handle anything with apply. So for now, ignoring the field so we stop erroring on these fields. We can always pick it back up later.
> [Unticketed] Modify agency transform to ignore a new field

- frontend/src/app/[locale]/search/error.tsx
- frontend/src/hooks/usePrevious.ts
- frontend/src/types/uiTypes.ts
- frontend/tests/e2e/search/search-error.spec.ts
- frontend/tests/hooks/usePrevious.test.ts
Fixes #3628
Fixes bug where search error page had an unusable UI
Also introduces a usePrevious hook as pulled from https://www.developerway.com/posts/implementing-advanced-use-previous-hook (I think this hook implementation used to be in the React docs themselves, but I don't see it there anymore)
This was fixed by correctly using NextJs's `reset` method which is not well documented https://nextjs.org/docs/app/api-reference/file-conventions/error#reset
Because NextJS's error handling uses React error boundaries under the hood, which are basically designed to set an error state and take action based on that state, it makes sense that something explicit must be done to tell the error boundary that the app is no longer in an error state. That's what reset is for, so by calling reset whenever …
> [Issue #3628] allow error page to be interactive without refresh

- api/openapi.generated.yml
- api/src/pagination/pagination_schema.py
- api/src/services/opportunities_v1/opportunity_to_csv.py
- api/tests/src/api/opportunities_v1/test_opportunity_route_search.py
Fixes #3579
Remove a few columns from the opportunity CSV extract that shouldn't be used (bad data / duplicative)
For the search endpoint, add a maximum to the page size to prevent someone from using it to fetch everything (if they want that, we have extract files which will be better).
Slight adjustment to CSV writing logic
Cleaned up some old unused pagination code from an earlier implementation
For fields removed:
* Agency == agency code, but been moving us to only use agency code for clarity on what the field actually is, so removing the extra duplicate
* Agency phone number has bad data and we already removed it from the search API itself
The small adjustment to the CSV writing logic is to have one less iteration over opportunities in the endpoint. No idea if it'll add much …
> [Issue #3579] Update opportunity CSV generation

- analytics/src/analytics/integrations/github/validation.py
- analytics/tests/integrations/github/test_validation.py
Fixes the type in the `IssueType` pydantic model that was causing `issueType` to be parsed incorrectly.
Fixes #3730 
- Fixes typo in `IssueType` field alias (it was incorrectly aliased as `"type"` instead of `"issueType"`)
- Replaces the string literal field aliases with module level constants to make it easier to update and monitor field aliases.
1. Checkout the PR locally
2. Run `make gh-data-export` to export the data from GitHub
3. Run the following command to check the percentage of issues that have `null` value for issue type:
```bash
jq '[.[] | …
```
> [Issue #3730] Fix parsing `issueType` bug

- api/src/db/models/user_models.py
- api/src/services/agencies_v1/get_agencies.py
Fixes #3696
Cleanup the way we setup get agencies queries to remove extra/unused logic
It looks like two separate queries were setup to do the same thing, but only one is used, trim out the extra one that might actually cause issues because it's setting the top level agency in its loop.
> [Issue #3696] Update get agencies endpoint to remove extra queries

- analytics/README.md
Fixes #2937 
Link to our new Operational Data Dashboard from our Analytics README
> [Issue #2937] Add link to the Operational Data Dashboard

- infra/modules/service/cdn.tf
Adjusts the `dynamic "origin" {...}` terraform configurations so that S3 CDN and the ALB CDN are more distinct.
https://d20lnyycqwjw31.cloudfront.net/
https://d3e8vod9uic4zv.cloudfront.net/bg.svg
> [Issue #3097] Fixes the two CDNs messing with each other's settings

- frontend/src/app/[locale]/opportunity/[id]/page.tsx
- frontend/src/components/opportunity/OpportunityDocuments.tsx
- frontend/stories/components/opportunity/OpportunityDocuments.stories.tsx
- frontend/tests/components/opportunity/OpportunityDocuments.test.tsx
Fixes #3584
Remove references to the attachment_type which is depreciated on the backend. 
Testing is limited locally, so I was able to verify that some of this works, but real test will be in Dev:
✅ One attachment: http://localhost:3000/opportunity/155
✅ Two attachments: http://localhost:3000/opportunity/152
> [Issue #3584] Remove references to the attachment type that we're no longer using

- frontend/src/services/fetch/fetchers/clientSearchResultsDownloadFetcher.ts
- frontend/src/utils/generalUtils.ts
- frontend/tests/e2e/search/search-download.spec.ts
- frontend/tests/services/fetch/fetchers/clientSearchResultsDownloadFetcher.test.ts
Unticketed
https://github.com/HHS/simpler-grants-gov/pull/3689 introduced search results csv downloads but on all browsers other than Firefox, the files were not downloading with the proper file names. This fix is a bit of a hack, but one that was used by FileSaver.js, which people probably still use! https://github.com/eligrey/FileSaver.js/blob/master/src/FileSaver.js
The new function here is not covered by unit tests, but I did improve the e2e test around the functionality.
1. `npm run dev` in this branch
3. click "export results"
4. _VERIFY_: file downloads with filename matching `grants-search-<timestamp>.csv`
5. repeat steps 2 - 4 for every browser you have available
> Screenshots, GIF demos, code examples or output to help show the changes …
> [unticketed] fix webkit / chrome error with csv download filename

- frontend/src/app/[locale]/search/layout.tsx
- frontend/src/components/BetaAlert.tsx
- frontend/src/components/search/SearchCallToAction.tsx
- frontend/src/i18n/messages/en/index.ts
- frontend/tests/components/BetaAlert.test.tsx
Fixes #3585
Updates the beta alert copy for only the search page. Since the beta alert messaging was previously static across the app this includes functionality to allow passing in override values.
2. visit http://localhost:3000
3. _VERIFY_: home page beta alert still matches prod
4. visit http://localhost:3000/search
5. _VERIFY_: beta alert content matches requirements
> [Issue #3585] update search beta alert messaging

- api/src/data_migration/transformation/subtask/transform_opportunity_attachment.py
Change the opportunity attachment job to process 100 attachments at a time
This means we'll fetch 100 attachments at a time into memory - instead of 1000+ like we were previously doing
Doing this because I hit an out-of-memory error on the ECS task when running - not 100% certain this will work (depends on how the ORM cache works?) but want to test it.
> [Unticketed] Adjust the batch size of the attachment job to be 100

- infra/modules/service/main.tf
Fixes #3788 
The links in the API need to include the protocol, at the terraform level we transition from domain name to URL without adding the protocol, so injecting it there seems like the most logical place.
URLs were missing a protocol, so the browser interprets them as a relative URL in the FE and other API consumers would have needed to know to add an https://
> [Issue #3788] Include protocol when defining CDN_URL

- frontend/README.md
Fixes N/A
As a new contributor, I noticed during my frontend dev setup that I missed the "step" for copying over the `.env.development` to `.env.local`. I believe this happened due to a small typo in the original documentation (`/frontend/env.development` instead of `/frontend/.env.development` - notice the **dot** in front of env). So I just created the actual step of copying the environment variable file in the numbered list of steps.
I wanted to get some thoughts about this change. I'm hoping it can optimize the speed of the local environment setup for new contributors. Thank you!
N/A
> docs: small updates to docs to optimize dev setup

- .github/CODEOWNERS
Recently I've noticed that too many people have been getting tagged on documentation PRs. I wondered why this is. Well! Turns out codeowners files are evaluated top to bottom. So the more generic paths should come first.
> [no ticket] Fix codeowners ordering probably

- api/openapi.generated.yml
- api/src/api/opportunities_v1/opportunity_schemas.py
- api/src/db/models/agency_models.py
- api/src/db/models/opportunity_models.py
- api/src/services/opportunities_v1/search_opportunities.py
- frontend/src/components/search/SearchResultsListItem.tsx
- frontend/src/services/fetch/fetchers/searchFetcher.ts
- frontend/src/types/search/searchRequestTypes.ts
- frontend/src/types/search/searchResponseTypes.ts
- frontend/tests/services/fetch/fetchers/SearchFetcher.test.ts
Fixes #3464 
🚨🚨🚨 Diffing against Michael's API change branch for now to highlight the further changes I made, but we will probably merge direct to main not into his branch to go to main.
Added support for the API change that takes an array of sort criteria instead of individual arguments for filed and direction
With some logging in the API layer I was able to demonstrate we were getting the correct format passed in from the FE and results sorted as expected:
Default/relevancy sort:
``` sort_order: [SortOrderParams(order_by='relevancy', sort_direction=<SortDirection.DESCENDING: 'descending'>), SortOrderParams(order_by='post_date', sort_direction=<SortDirection.DESCENDING: 'descending'>)]```
Agency sort:
``` sort_order: [SortOrderParams(order_by='top_level_agency_name', …
```
> [Issue #3464] Better agency display/sort in search

- api/src/logging/pii.py
- api/tests/src/logging/test_pii.py
Fixes #3822 
Modify our PII logging mask
Add unit test
We've encountered an odd bug that causes random errors with our logic to mask PII from logs: https://github.com/HHS/simpler-grants-gov/actions/runs/13246291300/job/36973529031
The error is ultimately due to our process that masks PII information replacing a float/timestamp with ********* and then the formatting in the logger breaking.
https://github.com/HHS/simpler-grants-gov/blob/main/api/src/logging/pii.py
This masking process happens on every log record, and it checks every part of the log message if it contains a certain regex that looks like an SSN (9 digits in a row, optionally separated by dashes) and replaces it with *********. There are already some rules built into this to not replace if we think it's a floating point …
> [Issue #3822] Modify our PII logging mask to allow long floats

- api/src/task/task.py
- api/tests/src/task/test_task.py
Fixes #3773
Update task runner to handle SQLAlchemy db errors, including rolling back if needed before committing the `JobLog` record.
When we hit an error in one of our tasks, if the error is due to a database issue (let's say a unique constraint being violated) an error will be thrown, but the transaction is still active. When we go to update the job table, we run into an issue as the transaction is still "begun" and we get an error saying we can't start a new transaction.
See unit test to cover db failing scenario
> [Issue #3773] Fix task logic when an error occurs when attempting to write to the DB

- infra/frontend/app-config/main.tf
- infra/frontend/service/main.tf
followup from: https://github.com/HHS/simpler-grants-gov/commit/9eca4df4f71f403c07165a5a3e71b02888daa529
The infra template changed the default value of "has database" from false to true, which resulted in the frontend trying to deploy a database
> [no ticket] frontend has no database

- api/src/data_migration/transformation/subtask/transform_funding_instrument.py
- api/tests/src/data_migration/transformation/subtask/test_transform_funding_instrument.py
Partially fixes #3849
Modify funding instrument transforms and tests to remove legacy history table processing.
This is PR 3/4
See updated unit tests
> [Issue #3849] Remove historical transforms from funding instrument [3/4] 

- bin/run-command
Change the run-command script we use for running ECS tasks to filter the log stream using `--log-stream-name-prefix` instead of `--query`
We were seeing two issues that this hopefully resolves:
* This command was taking 7+ minutes to resolve
* This command frequently was getting rate limited and failing deployments (likely due to a lot of internal queries)
Testing this change to run an ECS task locally, it takes 1~2 seconds to run now
Was able to successfully use the script to run the transform script (setup to no-op), and did not need to wait long for logs to start flowing.
> [Unticketed] Adjust describe-log-streams command to not use query

- analytics/src/analytics/cli.py
Fixes #2968 
Adds a few simple execution timers so we can easily measure and inspect how long the ETL workflow takes to execute.
It was suggested that we optimize the ETL workflow insert pattern. A precursor to any optimization is measuring the baseline performance. This PR introduces simple execution timers to measure baseline performance. 
> [Issue 2968] Add execution timers to ETL workflow logging

- analytics/src/analytics/integrations/github/main.py
- analytics/tests/dataquality/inputs/roadmap.py
- analytics/tests/integrations/github/test_validation.py
Fixes #3775 
A check in the validation step to avoid empty objects since they were causing errors in the process.
If an item from is added from a project to one of the ETL sprint boards that the GitHub token doesn't have access to the ETL process will fail instead of just omitting the bad data.
> [#3775] ETL Fix for broken project objects from private repos

- frontend/src/components/Header.tsx
Fixes #{ISSUE}
Moves "saved grants" to end of header links:
1. Login locally
2. See "Saved Grants" is to the far right, same as the screenshot above.
> Move "Saved grants" to far right of the header links

- infra/api/service/main.tf
- infra/frontend/service/main.tf
I accidentally removed the cert arn inputs here: https://github.com/HHS/simpler-grants-gov/commit/9eca4df4f71f403c07165a5a3e71b02888daa529#diff-cab9e585e98c92c0a043f3c83f786a614183055ee52f403d90634a6287cd0f74L134
The terraform deploy will probably deploy (safely) because the HTTPS ingress already exists. I'll do a safe update to fix that issue once it happens.
> [no ticket] Adds cert arn back

- analytics/src/analytics/cli.py
Fixes #2968
Adds a cast to a float value to avoid type mismatch. 
Last sprint I added a simple timer to measure and log process duration. Whereas the logging statement worked as intended locally on my MBP, today I noticed that when running in an AWS step function container the log statement throws a type mismatch error, because the float is being interpreted as a string.  
> [Issue 2968] Fix minor bug in process duration logging

- frontend/src/app/[locale]/login/page.tsx
- frontend/src/app/api/auth/callback/route.ts
- frontend/src/components/LoginModal.tsx
- frontend/src/utils/sessionStorage.ts
- frontend/tests/api/auth/callback/route.test.ts
- frontend/tests/utils/getRoutes.test.ts
Fixes #3504 
* When the user clicks "Sign in," before sending them to the API to redirect the user on to Login.gov we record the current path and query string to session storage.
* Upon returning from Login.gov we have the Nest Server page that gets redirected to by the API in turn send the user to /login a client side route where we can read the session storage and redirect the user to their original page where they clicked to "Sign in"
1. Sign out if Signed in
2. You can go to any page on the site, and click Sign in
3. After returning from Login.gov you should find yourself back on the original page
4. Sign out again
5. Add some query params to the URL
6. Click Sign in
7. After returning from Login.gov you should find yourself back on the original page with the query params intact.
> [Issue #3504] Return user to their original page after login

- api/src/data_migration/transformation/subtask/transform_opportunity_attachment.py
- api/tests/src/data_migration/transformation/subtask/test_transform_opportunity_attachment.py
Fixes #3973
Guard against null mime_type. Add test
Discovered while loading / transforming attachment data in dev.
See attached unit test
> [Issue #3973] Fix null mime_type while transforming opportunity attachment

- api/src/data_migration/transformation/subtask/transform_agency.py
- api/tests/src/data_migration/transformation/subtask/test_transform_agency.py
- api/tests/src/task/test_task.py
Fixes #3994
Modified the way we determine an agency is a test agency to be based on a prefix rather than exact match (eg. if we configure `ABC`, `ABC-123` would now be a test agency as well)
Modified the transform hierachy task to be able to unset top level agency if it doesn't match anything (fixes some weird data issues we're seeing)
Modified the transform hierachy to also update `is_test_agency` so that everything always gets reprocessed each run
The transform agency logic happens in two passes, first we look at all of the agency changes from the `TGROUPS` table and apply updates / create new agencies.
We then have a `TransformAgencyHierarchy` task that runs to do some post-processing on all agencies. I mostly put these fixes in the latter bit so that any of the weird issues we've …
> [Issue #3994] Fix agency data during transforms

- frontend/src/errors.ts
Fixes #3955 
Earlier changes had restructured the error object but the parsing function wasn't updated to adjust
Steps to test:
1. Open Dev Tools
2. Ensure the Network tab is active
3. Go to any Opportunity page that doesn't exist, like: http://localhost:3000/1000000
4. Ensure that the page is returning a 404 status not a 500 status
5. Confirm there is no message about malformed error object in the NextJS console logs server side.
6. It is expected there will be NextJS console logs server side noting `Failed to render page title due to API error Error: Not Found` and the associated callstack.
> [Issue #3955] Opportunity page returning 500 not 404 errors when Opp is not found

- frontend/src/components/search/SearchResultListItemStatus.tsx
unticketed
adds padding after color, before date on first date item in search results. I think this is a recent regression.
1. run `npm run dev` on this branch
2. visit a search page
3. compare to prod
4. _VALIDATE_: the date isn't scrunched. Also compare screenshots below
> [unticketed] add padding on first date in search result

- analytics/src/analytics/integrations/github/main.py
Fixes #3867
Removed noise from analytics logging that occurs during the extract phase of the ETL workflow. This PR makes logs statements more concise, removing the noise, and moving the details of each exception to debug level logging.
This PR also add calculation and logging of validation failure rate that occurs when marshaling data from GraphQL response payload to internal data structures. 
In the extract phase of the ETL workflow, some rows fail validation, and the logs are much too noisy about that. Also, there is no clear indication of the ratio of …
> [Issue 3867] Cleanup logging during extract and add failure rate logging

- api/src/data_migration/transformation/subtask/abstract_transform_subtask.py
- api/src/data_migration/transformation/subtask/transform_applicant_type.py
- api/src/data_migration/transformation/subtask/transform_funding_category.py
- api/src/data_migration/transformation/subtask/transform_funding_instrument.py
- api/tests/src/data_migration/transformation/subtask/test_transform_applicant_type.py
- api/tests/src/data_migration/transformation/subtask/test_transform_funding_category.py
- api/tests/src/data_migration/transformation/subtask/test_transform_funding_instrument.py
Fixes #4004
Modify the transformations for the applicant type, funding category, and funding instrument transformations to process all deletes separate from inserts/updates
This fixes a bug where if we received both a delete + insert for one of these tables at the same time, we'd delete, but be unable to insert. This happens anytime an opportunity summary is updated in the old system due to how it handles versioning.
For a much more in-depth description of the bug, see https://github.com/HHS/simpler-grants-gov/issues/4004#issuecomment-2682991160
By separating the deletes and inserts, we don't hit the weird delete-not-yet-processed caching issue.
> [Issue #4004] Fix transform problem with simulatenous delete + insert

- frontend/src/app/api/auth/logout/route.ts
- frontend/src/errors.ts
- frontend/tests/api/auth/logout/route.test.ts
Fixes #3953
Logs out user if expired. Updates `parseError()` so that message can be inspected separately if desired.
1. start the API and frontend locally
2. login
3. click logout, see that the logout works correctly
4. login again
5. wait until the session has expired while you are still logged in
6. click logout, see that the logout works correctly
> [Issue #3953] Logout user if session is expired

- documentation/frontend/analytics.md
- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/[locale]/layout.tsx
- frontend/src/app/[locale]/search/page.tsx
- frontend/src/components/search/SearchAnalytics.tsx
- frontend/src/components/search/SearchFilterAccordion/SearchFilterAccordion.tsx
- frontend/src/constants/environments.ts
- frontend/src/services/search/SearchFilterManager.ts
- frontend/src/types/newRelic.ts
- frontend/src/types/search/searchResponseTypes.ts
- frontend/src/utils/analyticsUtil.ts
- frontend/tests/components/search/SearchAnalytics.test.tsx
- frontend/tests/utils/analyticsUtils.test.ts
- infra/frontend/app-config/staging.tf
Fixes #3764 
* sends search page query params to new relic. This data is not collected out of the box by new relic because of security concerns.
* adds a typing package for the new relic client side object
* some moving around of new relic and query param related typing
* enables new relic in staging
Note that custom attributes are being cleared when navigating away from the search page, but not quickly enough for them to not show up on the route transition events on navigation. Not sure if this is a deal breaker.
Also note that I've discovered that trying to run the app with new relic enabled but without an app name or license key results in the application hanging indefinitely. We should fix this in a future ticket.
Further note that given the somewhat vague requirements in the ticket …
> [Issue #3764] add search query params to new relic

- frontend/tests/pages/subscribe/SubscriptionForm.test.tsx
- frontend/tests/pages/subscribe/page.test.tsx
Fixes #1936 ... kind of
The ticket in question refers to fixing tests that no longer exist in the form that they were written about. However, there is some adjustment to be made to other tests that are still referencing the deprecated and no longer used `useFormState` function. This change updates these subscription tests and makes an attempt to expand them where possible.
Note that I ran into issues with fully unit testing the server actions being used in the subscription form. We can return to that another day when perhaps the Next / React server actions implementation is a bit more stable.
1. _VERIFY_: tests pass CI
> [Issue #1936] fix subscription tests somewhat

- api/src/data_migration/transformation/subtask/transform_agency.py
- api/src/data_migration/transformation/transform_oracle_data_task.py
- api/tests/conftest.py
- api/tests/src/data_migration/transformation/subtask/test_transform_agency.py
Fixes #4021
Created a task that validates agency data for a few known scenarios we've encountered
This work is a follow-up to a discussion we had about oddities we've seen with agency data, and mainly aims for us to better be aware of data ending up in a weird state. While we've fixed some issues with the data, and fixed processes that build it, we know there are a few issues still present somewhere in the logic, and want to use this as a mechanism to help detect it.
> [Issue #4021] Create a task that validates agency data

- frontend/package-lock.json
- frontend/package.json
unticketed
* updates new relic security agent to latest version
* includes Axios as explicit dependency at latest version in order to remediate vulnerability
CVE-2025-27152 appeared recently, and is causing our frontend code to (sometimes) not pass vulnerability scans
https://osv.dev/vulnerability/GHSA-jr5f-v2jv-69x6
Axios is a subdependency of the New Relic Node security agent package, but the package has not been updated to bring in the latest version of Axios yet. See https://github.com/newrelic/node-newrelic/releases
As a result this update includes a bump to the New Relic security agent, as well as an explicit bump to Axios, which we can remove from our package.json once New Relic updates to the latest Axios. See this ticket for that work …
> [unticketed] frontend package updates to work around axios vulnerability

- infra/analytics/app-config/env-config/scheduled_jobs.tf
Fixes #4100 
This PR increases the frequency of the automated ETL workflow from 1x to 3x per day.
The analytics ETL workflow currently runs once every 24 hours, which means stakeholders are often times viewing stale data (i.e. "yesterday's data").
> [Issue 4100] Increase analytics ETL frequency 

- frontend/src/app/api/user/saved-opportunities/route.ts
- frontend/src/components/user/OpportunitySaveUserControl.tsx
- frontend/tests/api/user/saved-opportunities/route.test.ts
unticketed
For consistency, change client side request to save opportunity to use POST body rather than header
1. see https://github.com/HHS/simpler-grants-gov/pull/3677
> [unticketed] send opportunity id in body of post request

- frontend/src/components/search/SearchQueryCopyButton.tsx
- frontend/src/components/user/SaveSearchPanel.tsx
- frontend/src/hooks/useCopyToClipboard.ts
Fixes #3828
The clipboard property of the Navigator interface [requires https](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard) or localhost, which was not discovered until testing in dev.
This PR fixes that, throws an error in the clipboard component so the tooltip is not shown if it fails, and updates the content URL.
1. Run `npm run dev` on `main`. 
```bash
▲ Next.js 15.1.4
- Local:        http://localhost:3000
- Network:      http://192.168.1.66:3000
- Environments: .env.local, .env.development
```  
Use the `Network` URL, go to /search and see that the copy function errors.
2. Checkout this branch. Repeat the process, see that it works.
> [Issue #3828] Update copy button to support non-https

- infra/modules/service/waf.tf
Fixes #3644 
Stop blocking on long query strings, count instead
Manually changed this setting in Dev and verified the search page no longer 403'd
> [Issue #3644] Allow longer querystring since our FE relies on that for search filters

- api/poetry.lock
- api/pyproject.toml
- api/src/form_schema/jsonschema_builder.py
- api/tests/src/form_schema/test_jsonschema_builder.py
Fixes #4178
Created a rough utility for building JsonSchema
The idea here is that this will later get used by a process that parses the PDFs/XML of the forms and uses this builder to convert to JsonSchema. This does not include all terms supported by JsonSchema, I mostly aimed at getting all the types + validation rules setup. Additional fields (like titles, descriptions, comments) aren't included here yet.
Additional context from research - I looked into a tool that just directly converts XSD to Json and while a few exist, they largely don't appear to work - the only one I got sorta working was a plugin to PyCharm, and it only vaguely worked. Most of them were written 10 years ago and not maintained, and JsonSchema has gone through several revisions in the past few years.
I also looked …
> [Issue #4178] Create a rough utility for building JsonSchema

- frontend/src/components/TooltipWrapper.tsx
- frontend/src/components/search/SaveSearchPanel.tsx
- frontend/src/i18n/messages/en/index.ts
unticketed
Adding aria-label attribute to tooltip button to fix accessibility issue flagged in pa11y testing.
Note that this is covering for a seeming deficiency in the Truss Tooltip component, as it uses a button under the hood but does not account for adding labeling or text to satisfy this axe rule:
https://dequeuniversity.com/rules/axe/4.2/button-name?application=axeAPI
1. `npm run dev` on this branch
2. `npm run test:pa11y-desktop`
3. _VERIFY_: all tests pass
> [unticketed] add aria label to fix broken tooltip accessibility test

- api/openapi.generated.yml
- api/src/api/users/user_routes.py
- api/src/api/users/user_schemas.py
Support for issue #3830 
Send id of saved search down in payload on successful save request
This id will be used by the frontend to trigger a refetch of a user's saved search list
See https://github.com/HHS/simpler-grants-gov/pull/4170
> [Issue #3830] send saved search id down in response payload

- api/src/task/task.py
Fix the timer for our ECS tasks to actually wrap the code that they run in
The actual implementation of a task is in the `run_task` method, the timer somehow got moved to be after the job ran, so all the metrics were 0 seconds. This fixes that
> [Unticketed] Fix backend task timer

- api/tests/conftest.py
- api/tests/lib/db_testing.py
- api/tests/src/api/agencies_v1/test_agencies_routes.py
- api/tests/src/api/applications/test_application_routes.py
- api/tests/src/search/backend/test_load_opportunities_to_index.py
Fixes #{ISSUE}
Adjust the way we cleanup tables between unit tests
A recent test failure prompted this change: https://github.com/HHS/simpler-grants-gov/actions/runs/13930349741/job/38985691135 - likely this was just a random failure, but it meant it was worth looking into how we do cleanup between individual unit tests. I made it so all deletes now use the same utility which does two things:
* Does everything in a no_autoflush block to prevent any weird flush in the middle of a delete
* Adds `selectinload` to fetch all relationships up front to improve performance (locally I got things to run in about 75% of the previous time).
> [Unticketed] Adjust how cascade-deletes are done in tests

- analytics/src/analytics/datasets/acceptance_criteria.py
- analytics/src/analytics/integrations/etldb/deliverable_model.py
- analytics/src/analytics/integrations/etldb/main.py
- analytics/src/analytics/integrations/etldb/migrations/versions/0009_add_accept_metrics_to_deliv_hist.sql
- analytics/tests/datasets/test_acceptance_criteria.py
Fixes #3063 
Extend ETL workflow to write 2 acceptance criteria metrics to DB instead of 1:
* percent of acceptance criteria done
* percent of acceptance metrics done
> [Isssue 3060] Split acceptance criteria metric into 2 metrics

- frontend/stories/brand/tone.mdx
Fixes #4000
> Adding the content from [Tone and Voice Guide](https://wiki.simpler.grants.gov/design-and-research/content-guidelines/voice-and-tone-guide) into Storybook
> The Gitbook styling of the wiki page wasn't the most straightforward thing to replicate without creating custom components, which seemed like overkill for something that would only exist to service Storybook. Instead, I opted to utilize the [USWDS components](https://designsystem.digital.gov/components/overview/) directly since it is already a dependency of the project.
> [Issue #4000]: Add new tone and voice page content for storybook

- api/src/services/users/get_saved_opportunities.py
- api/tests/src/api/users/test_user_saved_opportunities_get.py
Fixes #4260
Update query to join on `user_id`
Previously this was not added, resulting in a bug showing all user saved opportunities.
See attached unit test (which fails in `main`), passes here.
> [Issue #4260] Fix GET saved opportunity filter by user ID 

- bin/run-command
- infra/api/app-config/.terraform.lock.hcl
- infra/modules/service/main.tf
Currently the migrations run in the first container in the list, instead of trying to get the primary application container
> [no ticket] Dont run migrations inside of the sidecar

- api/Makefile
- api/poetry.lock
- api/pyproject.toml
Removed pytest-watch which hadn't been updated since 2018 and was causing issues building due to a recent change in setuptools
This just removes the ability to watch tests and have it constantly run tests everytime your code changes. If we really want that functionality, we can look into https://pypi.org/project/pytest-watcher/ which seems to be the spiritual successor to pytest-watch and is still maintained.
> [Unticketed] Remove dependency on pytest-watch

- analytics/README.md
Prior link was to dashboard URL that required the user be logged in. Switched to the public link.
> [Unticketed] Link to public version of dashboard

- api/newrelic.ini
- api/src/logging/flask_logger.py
Fixes #4273
Removed configuration that emits logs to New Relic directly from our API - we'll rely on the new fluentbit sidecar to forward them
Added metadata to our logs that New Relic wants for tracing/etc.
An example of this working locally - note that we actually hide these fields from our local log messages, you'll have to comment out these fields from https://github.com/HHS/simpler-grants-gov/blob/main/api/src/logging/decodelog.py#L121 in order to see them (which I did for this screenshot).
> [Issue #4273] Stop APM New Relic logs, add New Relic metadata to logs manually

- api/src/task/ecs_background_task.py
Remove ECS metadata that no longer exists and was causing errors when we tried to fetch it
This is due to recent changes in how we route our logs
> [Unticketed] Remove ECS logging regarding aws log groups/streams

- infra/api/app-config/env-config/environment_variables.tf
Fixes #4263
I'm inferring that var.enable_https is if the local container server should be running HTTPS (false in our apps). So I think I might have found the right higher level config that we should really be checking local.service_config.enable_https
Check the correct enable_https
> [Issue #4263] Need to know if the service is HTTPS not the local container

- api/src/task/task.py
Adds `task_class` to the logs wherever we log the task metrics
During various backend tasks we collect metrics (counts of various scenarios) that at the end we log out. These are really useful for making dashboards and/or alerts (here's how many records we processed each hour).
There isn't a good way in the current data to target a specific tasks log statement, this just adds an easy `where task_class = 'LoadOracleDataTask'` to those queries in New Relic. Note that the `cls_name` function resolves to the actual instantiated class, not `Task` - we already use that in log messages and a few other places.
Running locally, that value now appears where I expect:
> [Unticketed] Add the task class to the final completion log

- frontend/src/services/fetch/fetchers/agenciesFetcher.ts
- frontend/tests/e2e/search/search.spec.ts
- frontend/tests/services/fetch/fetchers/agenciesFetcher.test.ts
Fixes #4317
Dependent on https://github.com/HHS/simpler-grants-gov/pull/4321
Adds filter to agencies fetch request body to get only active agencies. This allows the filter UI to display only agencies that have opportunities with "posted" or "forecasted" statuses.
The real proof of this won't happen until we deploy to DEV or PROD, but...
1. start a local server on main with `npm run dev`
4. note list of agencies in the filter ui
3. visit http://localhost:3000/search
4. _VERIFY_: agency list is smaller
> [Issue #4317] filter out inactive agencies from filter list

- analytics/src/analytics/integrations/metabase/sql/data-availability/newest.sql
- analytics/src/analytics/integrations/metabase/sql/delivery-metrics/Bespoke-Burndowns/bespoke-burndown-by-issue.sql
- analytics/src/analytics/integrations/metabase/sql/delivery-metrics/Bespoke-Burndowns/bespoke-burndown-by-points.sql
- analytics/src/analytics/integrations/metabase/sql/delivery-metrics/all-deliverables-titles-excluding-done.sql
- analytics/src/analytics/integrations/metabase/sql/delivery-metrics/all-deliverables-titles-including-done-only.sql
- analytics/src/analytics/integrations/metabase/sql/delivery-metrics/all-deliverables-titles-including-done.sql
- analytics/src/analytics/integrations/metabase/sql/sprint-metrics/sprint-issues-pointed.sql
- analytics/src/analytics/integrations/metabase/sql/sprint-metrics/sprints-with-scd-data.sql
Fixes #4348
Changes to sprint, deliverable, and burndown queries to (1) exclude future sprints from sprint filter, (2) exclude issues that changed type from deliverable to epic or issue, and (3) include url in result set to enable click behavior on dashboards.
We do not have automated backups or source control for queries in Metabase. So every time we change a query in Metabase, we have to manually update these backups  :( 
> [Issue 4348] Update metabase query backups

- api/src/auth/api_jwt_auth.py
- frontend/src/services/auth/types.tsx
- infra/api/app-config/env-config/environment_variables.tf
Fixes #4368
Set a default session timeout for all deployed environments that meets HHS' 15 minute requirement.
Pass the active session duration to the FE via the JWT so it can behave in concert with the BE
> [Issue #4368] Respect HHS session timeout requirements

- api/src/search/backend/load_opportunities_to_index.py
Adjust the processor that handles file attachments in OpenSearch to also delete the raw file contents
Trying out different performance ideas, at the very least this'll save us a lot of space on the index, even if it doesn't help with the performance.
Before this change, the attachments section of the search data looks like:
```json
"attachments": [
{
"filename": "idea.pdf",
"data": "UHJvcGVydHkgaXQgbGl0dGxlIGFub3RoZXIgbXVzdCBEZW1vY3JhdCBiZWF0LiBGaWd1cmUgcmVtYWluIGJpbGxpb24gc2l0ZSBtZWV0aW5nIHNtaWxlIGNhcGl0YWwuIElkZW50aWZ5IHRodXMgaW4uIEZlYXIgc2l0dWF0aW9uIHN0YXIgaW5jcmVhc2Ugc3RhdGUuIExvdyBkaW5uZXIgc3RhdGlvbiBzZW5pb3IgcmVzcG9uZCB5YXJkIHZhbHVlLiBDYWxsIGZlYXIgdHVybiBpbnZlc3RtZW50LiBUYXggb3VyIHNraW4gYXJ0aWNsZSBSZXB1YmxpY2FuIHByb2R1Y3QgaWRlbnRpZnkuIFNvIGFydGljbGUgcmVwcmVzZW50Lg==",
"attachment": …
```
> [Unticketed] Don't keep the raw base64 value in search index

- api/Makefile
- api/src/data_migration/load/load_oracle_data_task.py
- api/tests/src/data_migration/load/test_load_oracle_data_task.py
Fixes #4355
Updated logging in LoadOracleDataTask to not put it all in metrics / log everything at once
New Relic has a limit of ~255 key/value pairs in a log statement. Right now we're putting about 200+ values into the metric object just for this one task - which is causing it to break when combined with the ~50 or so we always add. To work around this, instead of adding all these values as we go, just log a bunch of them as we go. Only keep metrics for the overall counts, and just log insert/update/delete metrics when we calculate them. Still have all the same info, just spread out a bit.
> [Issue #4355] Adjust logging in LoadOracleDataTask to use less metrics

- api/src/db/models/legacy_mixin/user_mixin.py
Fixes an issue discovered while setting up foreign tables in dev schema. `last_auth_date` was in an incorrect order.
Reorder column to match Oracle schema.
> [Unticketed] Update column order for `user_account_mapper` in legacy schema

- api/src/data_migration/transformation/subtask/transform_agency.py
- api/tests/src/data_migration/transformation/subtask/test_transform_agency.py
Modify the transform agency job to not error when trying to transform a row that is deleted that we also don't want to process
Before this change, the job would fail to update/insert an agency if there was a row marked as `is_deleted=True` that also was one that we didn't even care to map. This fixes that by doing the mapping check first before any other processing, not at the end.
> [Unticketed] Fix agency transform to not break for is_deleted rows

- .github/workflows/ci-frontend-a11y.yml
- .github/workflows/ci-frontend-e2e.yml
- api/Makefile
- api/tests/lib/seed_local_db.py
- frontend/tests/e2e/search/search.spec.ts
unticketed, fixes e2e tests that were skipped for convenience in https://github.com/HHS/simpler-grants-gov/pull/4359
Adds option to seed an open opportunity associated with each seeded agency.
This should ease some manual testing scenarios, as well as making e2e tests more robust when dealing with agencies.
1. tests pass in ci
> Agency e2e test flakiness

- api/src/logging/flask_logger.py
Make run_mode calculation based on the raw query rather than individual parts
The argv non-locally is actually `"/api/.venv/bin/gunicorn src.app:create_app()"` so need to find gunicorn slightly differently.
Verified running in gunicorn mode:
> [Unticketed] Fix run_mode in logs to find gunicorn

- analytics/src/analytics/integrations/metabase/sql/delivery-metrics/Bespoke-Burndowns/bespoke-burndown-by-issue.sql
- analytics/src/analytics/integrations/metabase/sql/delivery-metrics/Bespoke-Burndowns/bespoke-burndown-by-points.sql
- analytics/src/analytics/integrations/metabase/sql/delivery-metrics/all-deliverables-percent-done-by-issue-count.sql
- analytics/src/analytics/integrations/metabase/sql/delivery-metrics/all-deliverables-percent-done-by-points.sql
- analytics/src/analytics/integrations/metabase/sql/delivery-metrics/all-deliverables-percent-pointed.sql
- analytics/src/analytics/integrations/metabase/sql/delivery-metrics/deliverable-burndown-issue-count.sql
- analytics/src/analytics/integrations/metabase/sql/delivery-metrics/deliverable-burndown-points.sql
- analytics/src/analytics/integrations/metabase/sql/delivery-metrics/deliverable-burnup-issue-count.sql
- analytics/src/analytics/integrations/metabase/sql/delivery-metrics/deliverable-burnup-points.sql
- analytics/src/analytics/integrations/metabase/sql/delivery-metrics/deliverable-issues-done.sql
- analytics/src/analytics/integrations/metabase/sql/delivery-metrics/deliverable-issues-open.sql
- analytics/src/analytics/integrations/metabase/sql/delivery-metrics/deliverable-percent-done-by-issue-count.sql
- analytics/src/analytics/integrations/metabase/sql/delivery-metrics/deliverable-percent-done-by-points.sql
- analytics/src/analytics/integrations/metabase/sql/delivery-metrics/deliverable-percent-pointed.sql
- analytics/src/analytics/integrations/metabase/sql/delivery-metrics/epics-in-deliverable.sql
Fixes #{4394}
Refactored queries (open issues, burnup, burndown, pct pointed, pct done, etc) to ensure consistent deliverable->epic->issue hierarchy traversal and mapping.
We do not have automated backups or source control for queries in Metabase. So every time we change a query in Metabase, we have to manually update these backups.
> [Issue 4394] Update Metabase query backups

- api/newrelic.ini
Disable developer mode so New Relic stops trying to trace in tests which has a small chance to cause tests to fail due to our test setup
> [Unticketed] Disable developer mode for New Relic

- frontend/src/app/[locale]/opportunity/[id]/page.tsx
- frontend/src/components/opportunity/OpportunityDescription.tsx
- frontend/src/components/opportunity/OpportunityDocuments.tsx
- frontend/src/components/opportunity/OpportunityDownload.tsx
- frontend/src/i18n/messages/en/index.ts
- frontend/src/types/opportunity/opportunityResponseTypes.ts
- frontend/src/utils/testing/fixtures.ts
- frontend/tests/components/opportunity/OpportunityDescription.test.tsx
- frontend/tests/components/opportunity/OpportunityDownload.test.tsx
Fixes #4060
* remove "nofo download" button
* add description column in opportunity detail page documents table
* make documents table full width
2. visit an opportunity page with 1 attachment (should be 7) http://localhost:3000/opportunity/7
3. _VERIFY_: there is no download nofo button
4. _VERIFY_: documents table contains a description column
> [Issue #4060] documents UI tuning

- frontend/src/app/[locale]/saved-grants/page.tsx
- frontend/src/app/[locale]/saved-search-queries/page.tsx
Fixes #4452
Ensure that the user "saved" pages aren't subject to caching within next/browser so the data is always up to date.
This seems to work both in npm run dev and npm start modes locally, but it's super tough to test definitively, so we're somewhat rolling the dice here to see how it behaves in the lower environments.
> [Issue #4452] Avoid caching Saved Search and Saved Opportunities page

- infra/modules/network/vpc_endpoints.tf
I was looking for things that cost too much money, and we don't use evidently at all. In fact, its deprecated.
> [no ticket] Remove evidently vpc endpoints

- analytics/Dockerfile
Fixes #4490
Force install the two failing packages which should get latest patches that update command doesn't get (because they're super new and not vetted yet?)
> [Issue #4490] Address anchore flagged libs

- frontend/next.config.js
Fixes #4452
Use NextJS config to prevent pages we want to always re-render from caching. You don't see the effect of this in npm run dev have to build & start.
Context for reviewers
This is really tough to test, but the Cache-Control headers are better behaved under build & start following this change so 🤞🏻
> [Issue #4452] Further attempts to prevent saved items caching 

- api/src/api/agencies_v1/agency_schema.py
- api/src/app.py
Make it so passing in a specific header causes a 5xx
We make sure to initialize this after logging before_request stuff is done so the route metadata is still attached.
Tested locally with the healthcheck endpoint:
```sh
curl -X 'GET' \
'http://localhost:8080/health' \
-H 'accept: application/json' -H 'newrelic-failure-header: FAIL'
```
Produced a few logs, most notably the end request log has a 500:
```
grants-api  | 16:59:57.977  src.logging.flask_logger             _log_end_request             INFO     end request                                        response.status_code=500 response.content_length=158 response.content_type=application/json response.mimetype=application/json response.time_ms=6.371625000610948 app.name=src.app app_name=api run_mode=service environment=local …
```
> [Unticketed] Temporary modification to let user force 5xx for Newrelic testing

- infra/analytics/service/main.tf
I accidentally removed these env vars from the container while working on other things
> [no ticket] Adds back API analytics env vars

- frontend/src/app/[locale]/formPrototype/[applicationId]/[formId]/page.tsx
- frontend/src/app/[locale]/formPrototype/[applicationId]/page.tsx
- frontend/src/app/[locale]/formPrototype/success/page.tsx
- frontend/src/components/applyForm/ApplyForm.tsx
- frontend/src/components/applyForm/ApplyFormErrorMessage.tsx
- frontend/src/components/applyForm/ApplyFormNav.tsx
- frontend/src/components/applyForm/ApplyFormSuccessMessage.tsx
- frontend/src/components/applyForm/actions.ts
- frontend/src/components/applyForm/utils.tsx
- frontend/src/services/fetch/endpointConfigs.ts
- frontend/src/services/fetch/fetchers/applicationFetcher.ts
- frontend/src/services/fetch/fetchers/formsFetcher.ts
- frontend/src/types/applicationResponseTypes.ts
- frontend/src/types/formResponseTypes.ts
- frontend/tests/components/applyForm/ApplyForm.test.tsx
- frontend/tests/components/applyForm/widgets/TextWidget.test.tsx
Fixes #4342
This change adds the save ability to the apply form.
The desired flow is that a user:
1. Starts at /formProtype
2. Clicks "Create new application"
3. Is directed to the "Application" page that has a list of forms (currently one)
4. *Change in this PR*
There is now a "save" button. A user can enter form info and save their place by clicking "Save":
Clicking "Submit" sends the user to the temporary success page. If you go back after clicking submit you should see values last entered.
Remember this is a demo with no designs.
> [Isssue #4342] Add save to form prototype

- api/openapi.generated.yml
- api/src/adapters/search/opensearch_query_builder.py
- api/src/api/agencies_v1/agency_schema.py
- api/src/api/opportunities_v1/opportunity_schemas.py
- api/src/pagination/pagination_models.py
- api/src/services/agencies_v1/search_agencies.py
- api/src/services/opportunities_v1/search_opportunities.py
- api/tests/src/adapters/search/test_opensearch_query_builder.py
- api/tests/src/pagination/test_pagination_models.py
Fixes #4546
Modified the logic around parsing the search response to cap the total results at 10k
Modified the logic around creating a request to the search index to prevent a user from asking for anything past 10k
If you try to query a search index for any record past 10k, it will error.
For example, if we tried to do this following query against the search index, it would error saying you tried to ask for record 10005, which is more than 10k. There is no way around this limit in a way that still supports pagination (there is a scroll API, but you have to iterate one page at a time).
```
GET opportunity-index-alias/_search
{
"size": 10,
"from": 9995
}
```
To work around this issue, we changed two things:
1. Even if the search index says it has more than 10k results, cap it to 10k (note …
> [Issue #4546] Modify search logic to avoid querying for more than 10k records

- infra/api/app-config/env-config/scheduled_jobs.tf
Fixes #{[4529](https://github.com/HHS/simpler-grants-gov/issues/4529)}
Enable opportunity versioning task in all env
Tested in dev, staging and prod. All non-draft opportunities have version records in opportunity_version table
> [Issue #4529] Enable opportunity versioning[2/2]

- .dockleconfig
- analytics/local.env
- analytics/newrelic.ini
- analytics/poetry.lock
- analytics/pyproject.toml
- analytics/src/analytics/cli.py
- analytics/src/analytics/logs/app_logger.py
- analytics/src/analytics/logs/config.py
- analytics/src/analytics/logs/ecs_background_task.py
- analytics/src/analytics/newrelic/__init__.py
- infra/analytics/app-config/env-config/environment_variables.tf
Fixes #4555
Add NewRelic setup to Analytics code including:
* ini file
* Initializing New Relic at startup with that ini file
* Marking the tasks with the Background task designation
* Adding New Relic metadata to all log messages
Non-locally disable the pretty-print error messages
Make all tasks also be wrapped by ecs_background_task
A lot of this is copied from the API code, just without some of the API-specific things configured (ie. we don't need certain New Relic features if it's not an API serving requests).
Perhaps the most important thing here is the `@ecs_background_task` added to each of the tasks, this accomplishes a few things:
* When a process errors, it makes it so it will **ALWAYS** emit at least one error level log. (It adds a try-except around the entire function and logs …
> [Issue #4555] Add New Relic support to Analytics code

- infra/analytics/service/main.tf
1. Having a writeable root filesystem is a security concern
2. As of https://github.com/HHS/simpler-grants-gov/pull/3799 we don't need one anymore
> [no ticket] enable readonly root filesystem for analytics

- infra/api/app-config/env-config/scheduled_jobs.tf
- infra/modules/service/main.tf
- infra/modules/service/scheduled_jobs.tf
Infrastructure will always have a set of concerns regarding scheduled jobs that are slightly different than application layer concerns. Specifically, infrastructure will want to know if any of their changes have broken scheduled jobs in the recent past, via a view that displays all the scheduled jobs at once. In this view, all the jobs should have the same name on the application layer as they do on the infrastructure layer. There can be a different key that the application layer uses (`task_name` or whatever else) but the infrastructure layer dashboards are gonna look for this now, eg. `SCHEDULED_JOB_NAME` / `scheduled_job_name`
> [no ticket] Improves step function consistency

- infra/api/app-config/env-config/scheduled_jobs.tf
- infra/api/app-config/prod.tf
Fixes #{[4551](https://github.com/HHS/simpler-grants-gov/issues/4551)}
Override values for shard count and replica count in prod
Set Job to run every morning 8:00 AM EST top of the hour 9:00 AM non-dst
> [Issue #4551] Enable load agency cron job

- infra/modules/service/cdn.tf
The `aws_cloudfront_distribution` resource has a terraform diff on it every single time we deploy. It's confusing and wastes time. Also it's unclear if the changes are even applying... since we try to apply them on every single deploy.
There's only a terraform diff on the resource when you actually change it!!!
I change every attribute that had a permanent diff to the value of the attribute that terraform keeps changing it to. So that there's no more diff when you deploy the CDN resource back to back. I'm slightly worried that these changes make it so that caching is disabled by default, but we should be setting cache headers on all our objects, to ensure that the CDN is actually being utilized.
These routes are still accessible:
- https://d20lnyycqwjw31.cloudfront.net/
- …
> [no ticket] Fix permanent CDN diffs

- infra/modules/service/cdn.tf
The prod deploy - and only the prod deploy - is broken because of the CDN configuration. Specifically because prod is the only environment with a cert.
> Fix CDN viewer_certificate block

- .github/ISSUE_TEMPLATE/config.yml
Allow (at least temporarily) the ability to create blank issues and not use one of our templates.
I've been dealing with some sort of bug in GitHub that refuses to allow me to create an issue with an issue type. I have an open bug report with GitHub to try and figure out the problem, but this unblocks my ability to create tickets. We can revert this later if we don't want to keep this.
> [Unticketed] Allow blank issues to be created

- frontend/src/components/Header.tsx
- frontend/src/components/user/UserControl.tsx
- frontend/tests/components/Header.test.tsx
Fixes #4454
The workspace and user dropdowns in the nav are currently not closing unless you specifically click on them to close them. With this change they will close on any click after they are opened.
2. visit http://localhost:3000?_ff=authOn:true;savedSearchesOn:true
3. log in
4. click the workspace nav
5. click anywhere (you should probably test clicking a bunch of different places)
6. _VERIFY_: subnav closes
7. repeat 4 - 6 for the user dropdown nav
> [Issue #4454] auto close nav sub menus

- frontend/package.json
- frontend/src/app/[locale]/saved-grants/page.tsx
- frontend/src/components/search/SearchResults.tsx
- frontend/src/components/search/SearchResultsList.tsx
- frontend/src/components/search/SearchResultsListItem.tsx
- frontend/tests/components/search/SearchResultsList.test.tsx
- frontend/tests/components/search/SearchResultsListItem.test.tsx
Fixes #1532
Adds an id containing the index and page number of each search result to each search result item link that will allow new relic to track clicks.
1. start a local server on this branch with `npm run build -- --no-lint && NEW_RELIC_APP_NAME="frontend-dev" NEW_RELIC_LICENSE_KEY="<dev new relic license key from 1pass>" npm run start:nr`
3. click a few search results
4. navigate to a different page of results
5. click a few search results
6. go to the new relic query builder from https://one.newrelic.com/
7. enter the following query 
```
FROM UserAction
SELECT targetId WHERE action = 'click'
WHERE appName IN ('frontend-dev')
SINCE 10 minutes AGO
```
8. _VERIFY_: you see targetIds coming up that match the page and index of the search results …
> [Issue #1532] track search item click position

- frontend/src/components/search/SearchFilterAccordion/AgencyFilterAccordion.tsx
- frontend/src/components/search/SearchFilterAccordion/AnyOptionCheckbox.tsx
- frontend/src/components/search/SearchFilterAccordion/SearchFilterAccordion.tsx
- frontend/src/hooks/useSearchParamUpdater.ts
- frontend/src/i18n/messages/en/index.ts
- frontend/tests/components/search/SearchFilterAccordion/AnyOptionCheckbox.test.tsx
- frontend/tests/e2e/search/search.spec.ts
- frontend/tests/e2e/search/searchSpecUtil.ts
- frontend/tests/hooks/useSearchParamUpdater.test.ts
Fixes #3915
Adds "any" check boxes to all filter accordions except for agency. This checkbox effectively does the same thing as the "clear all" link, removing any currently selected options for a given filter. The box should be checked automatically if no other options are checked for a given filter, and will be unchecked as soon as any option for the filter is selected.
3. _VERIFY_: "any" checkboxes are available for all filter accordions except agency
4. _VERIFY_: "any" checkboxes are selected by default for all filters except status and agency
5. click an already checked any checkbox
6. _VERIFY_: nothing happens
7. click a non-any filter option in eligibility
8. _VERIFY_: any checkbox is no longer …
> [Issue #3915] add "any" filter option

- frontend/src/components/InfoTooltip.tsx
- frontend/src/components/TooltipWrapper.tsx
- frontend/tests/components/InfoTooltip.test.tsx
Fixes #4800
Fixes bug
2. visit localhost:3000/search
3. _VERIFY_: tooltip looks normal
> [Issue #4800] fix tooltip styling

- frontend/src/components/applyForm/ApplyForm.tsx
Fixes #4599
Before this commit, the form submission triggered [client-side form validation by the browser](https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Forms/Form_validation) for certain fields, which provides a different UI for some form fields:
After this change, the form is able to submit and provide the same validation for fields that were picked up by the HTML5 validation:
This will be easier to test after: https://github.com/HHS/simpler-grants-gov/pull/4563 is pulled in as an email field as added to the test form.
> [Issue #4599] Update ApplyForm.tsx to turn off html validation

- frontend/src/components/opportunity/OpportunityDescription.tsx
- frontend/src/components/opportunity/OpportunityStatusWidget.tsx
- frontend/tests/e2e/opportunity.spec.ts
- frontend/tests/e2e/search/search-copy-url.spec.ts
unticketed
due to some changes in the wording on the opportunity page that were not taken into account with tests introduced in https://github.com/HHS/simpler-grants-gov/pull/4837 there are some failing tests. This fixes the tests
1. _VERIFY_: all opportunity page e2e tests pass locally and in CI
> [unticketed] fix issue with opportunity page content display toggle e2e tests

- infra/modules/service/load_balancer.tf
Fixes #4892
Make it so the API LBs will passthrough the client certificate that was given to them (which will be present if it's a SOAP Proxy request)
Untested, would see how it worked when applied to Dev.
> [Issue #4892] Passthrough Client Certificates at the LB 

- .github/workflows/cd-analytics.yml
- .github/workflows/cd-api.yml
- .github/workflows/cd-frontend.yml
Fixes #4919
We have shared module code in terraform that may/can affect any of our services. But we don't redeploy those services automatically when changes are made there. This rectifies that and will trigger deploys to all Platform services when a change is made to any of the shared modules.
> [Issue #4919] Add shared modules terraform to changes that will deploy services

- .github/workflows/ci-nofos.yml
https://github.com/HHS/simpler-grants-gov/issues/4912
I won't actually be able to test this until after I merge, because Github Actions can only be run once they have been merged to main at least once. (As far as I know!)
> [Issue #4912] Adds CI for nofos

- .github/workflows/ci-nofos.yml
> Allow nofos tests to be run manually

- infra/modules/service/load_balancer.tf
Doesn't really fix anything, just a temporary hold while we sort more things out for #4892 
Roll back our client auth for now since we don't want to be prompting browser users about sending a client certificate when it's really just a thing for SOAP Proxy clients.
> [Issue #4892] Client cert passthrough

- frontend/src/app/api/auth/callback/route.ts
- frontend/src/app/api/auth/session/route.ts
- frontend/src/constants/auth.ts
- frontend/src/hooks/useClientFetch.ts
- frontend/src/services/auth/UserProvider.tsx
- frontend/src/services/auth/session.ts
- frontend/src/services/auth/sessionUtils.ts
- frontend/src/services/fetch/endpointConfigs.ts
- frontend/src/services/fetch/fetchers/fetchers.ts
- frontend/src/types/authTypes.ts
- frontend/src/utils/dateUtil.ts
- frontend/tests/hooks/useClientFetch.test.ts
- frontend/tests/services/auth/session.test.ts
- frontend/tests/services/auth/useUser.test.tsx
- frontend/tests/utils/dateUtil.test.ts
Fixes #4380
Adds call to refresh auth token if necessary on each client side request to the Next API.
If a user is logged in and has a token expiring within 10 minutes, on an API request, a call will be made to the python API to refresh the token on that side, and then re-encrypt the login.gov token with a new expiration.
* Refactors `createSession` to take in the expiration date for the session in order to make the function more reusable.
* Adds constants to track timing on expiration and refresh intervals
1. to make testing this easier, set the client token refresh interval to the same value as the token expiration interval. This way the app will always try to refresh your token on API requests once you're logged in. Change line 2 of src/constants/auth.ts to
```
export const …
```
> [Issue #4380] auth token refresh on request

- frontend/src/services/featureFlags/FeatureFlagManager.ts
- frontend/tests/services/featureFlags/FeatureFlagManager.test.ts
unticketed
Temporary change to disable non-environment variable feature flag values in prod
Users that had used the site without any feature flags prior to turning on the auth flag in prod reported not being able to see the sign in button.
This is because the client side cookie is a high priority determinator of the feature flag values. The cookie overrides env var based values, has a 3 month expiration, and cannot easily be removed with a hard refresh. This change will allow prod users to fall back to the intended default feature flags to fix this issue temporarily while we work on a longer term fix for the problem.
1. rebase this branch against dschrashun/4903-feature-flags-default
2. start a local server on this branch
3. visit http://localhost:3000
4. _VERIFY_: you see the login …
> disable reading client side feature flag cookie in prod

- infra/nofos/app-config/env-config/database.tf
- infra/nofos/database/.terraform.lock.hcl
This one line change (and the lockfile, I guess) were required to deploy the nofos database. The nofos dev / staging / prod databases have now been deployed.
This is half of #4976
> [Issue #4976] Changes to support deploying NOFOs database

- frontend/tests/components/search/SaveSearchSelector.test.tsx
unticketed
Fixes flaky SaveSearchSelector tests that broke for good with the latest React version
Just timing adjustments
1. _VERIFY_: ci passes
> [unticketed] fix broken saveSearchSelector tests

- frontend/src/components/opportunity/OpportunityDocuments.tsx
- frontend/src/styles/_uswds-theme-custom-styles.scss
Fixes #4413
`
.usa-table {
&.overflow-wrap {
max-width: 0;
word-wrap: break-word;
}
}
`
I've added some styles to the  newly added `.overflow-wrap` class to allow for word breakage on overflow.
`max-width: 0;`
is a fix for tables inside of flex
checked in firefox, chrome and safari
> fix: fixes tables that blow out when columns are very wide

- frontend/src/components/LoadingButton.tsx
- frontend/src/components/search/SaveSearchModal.tsx
- frontend/src/components/subscribe/SubscriptionForm.tsx
- frontend/src/components/workspace/DeleteSavedSearchModal.tsx
- frontend/src/components/workspace/EditSavedSearchModal.tsx
- frontend/src/components/workspace/SavedSearchesList.tsx
- frontend/src/i18n/messages/en/index.ts
- frontend/tests/components/LoadingButton.test.tsx
- frontend/tests/components/workspace/DeleteSavedSearchModal.test.tsx
- frontend/tests/components/workspace/EditSavedSearchModal.test.tsx
Fixes #4226
Makes a number of updates to saved search related modals for post launch fixes. See the ticket for the full list
Figma! https://www.figma.com/design/FGxWtAgToKhehLJCiuy1zL/Simpler.Grants.gov-Project?node-id=1809-14763&p=f&t=IkaY3oNbF6gkpCqT-0
1. to test loading state, slow down queries by adding this at line 59 of fetchers.ts - `await new Promise((resolve) => setTimeout(resolve, 3000));`
2. start a local server on this branch with `npm run dev`
3. visit http://localhost:3000/search?_ff=authOn:true;savedSearchesOn:true
4. log in
5. click "save" to save a search
6. _VERIFY_: "required" text appears as in the designs
7. enter a name and click save
8. _VERIFY_: loading state matches designs (spinner within the button)
9. _VERIFY_: success message matches designs
10. go to …
> [Issue #4226] save search modal cleanup

- api/src/services/applications/create_application.py
- api/src/validation/validation_constants.py
- api/tests/src/api/applications/test_application_routes.py
Fixes #4701
Implements validation logic to prevent users from starting applications outside a competition's open/close window.
Add tests to cover multiple scenarios
The competition table has an opening+closing date. We shouldn't let a user start an application if it is outside these dates.
The scenarios covered include ifthe opening_date is null - reject anyone. If the closing_date is null, allow it as long as it is on/after the opening date.
Run new unit tests.
> [Issue #4701] Add validation rules for opening_date, grace_period, closing_date

- frontend/src/components/search/SearchFilterAccordion/AgencyFilterAccordion.tsx
- frontend/src/components/search/SearchFilterAccordion/AllOptionCheckbox.tsx
- frontend/src/components/search/SearchFilterAccordion/AnyOptionCheckbox.tsx
- frontend/src/components/search/SearchFilterAccordion/SearchFilterAccordion.tsx
- frontend/src/components/search/SearchFilterAccordion/SearchFilterSection/SearchFilterSection.tsx
- frontend/src/constants/environments.ts
- frontend/src/hooks/useSearchParamUpdater.ts
- frontend/src/i18n/messages/en/index.ts
- frontend/src/utils/generalUtils.ts
- frontend/src/utils/middlewareSafeUtils.ts
- frontend/src/utils/search/searchUtils.ts
- frontend/src/utils/testing/fixtures.ts
- frontend/tests/components/search/SearchFilterAccordion/AllOptionCheckbox.test.tsx
- frontend/tests/components/search/SearchFilterAccordion/AnyOptionCheckbox.test.tsx
- frontend/tests/components/search/SearchFilterAccordion/SearchFilterAccordion.test.tsx
- frontend/tests/components/search/SearchFilterAccordion/SearchFilterSection/SearchFilterSection.test.tsx
- frontend/tests/e2e/search/search-copy-url.spec.ts
- frontend/tests/e2e/search/search.spec.ts
- frontend/tests/hooks/useSearchParamUpdater.test.ts
- frontend/tests/playwright.config.ts
- frontend/tests/utils/search/searchUtils.test.ts
Fixes #4889
The first part of an agency filter refactor as per designs and requirements in the ticket
* removes accordion behavior for top level agencies in the agency filter
* creates "all" button and adds it to each top level agency in filter
* adds "any" option to agency filter
* adds the ability for a filter accordion contents to scroll (and enables this on agency filter)
https://github.com/HHS/simpler-grants-gov/pull/4981 depends on this PR and should be rebased and opened once this is merged.
* moves some utils around to working around Next JS's middleware / lodash incompatibility)
* refactors path formatting utilities
* pre-emptively removes e2e tests that are not broken and related to the "clear all / select all" behavior that will be deprecated in …
> [Issue #4889] agency filter refactor

- api/src/api/application_alpha/application_route.py
- api/src/api/competition_alpha/competition_route.py
- api/src/api/form_alpha/form_route.py
- api/src/api/opportunities_v1/opportunity_routes.py
- api/src/api/users/user_routes.py
- api/src/auth/api_jwt_auth.py
- api/src/logging/formatters.py
- api/tests/src/logging/test_formatters.py
Fixes #4806
Adjust the API logs to have a more consistent naming structure for common fields (ie. prefer `opportunity_id` instead of `opportunity.opportunity.opportunity_id` or `opportunity.id`)
Adjust the JSON logger to output the message field with a different name to work around a New Relic issue with renaming our fields
Main motivator is so we can easily query for something like an opportunity across all of our logs. For example, if we wanted to see everything that interacted with a particular opportunity whether that's in the API, a backend script, or whatever, it's all the same field name now.
> [Issue #4806] Cleanup API logs for consistency

- .github/workflows/ci-frontend-e2e.yml
- frontend/next.config.js
- frontend/tests/playwright.config.ts
Fixes #4519
This adds the following headers to improve security:
* [X-Content-Type-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/X-Content-Type-Options) set to `no-sniff` to to avoid [MIME type sniffing](https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/MIME_types#mime_sniffing)
* [Strict-Transport-Security](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Strict-Transport-Security), aka [HSTS](https://developer.mozilla.org/en-US/docs/Glossary/HSTS), lets browsers know to always use HTTPS for the site instead of trying to make an initial request that is insecure
* [Content-Security-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Content-Security-Policy) helps stop cross-site scripting by regulating what …
> [Issue #4519] Update headers for security

- frontend/src/components/search/SearchFilterAccordion/SearchFilterAccordion.tsx
- frontend/tests/components/search/SearchFilterAccordion/SearchFilterAccordion.test.tsx
- frontend/tests/e2e/search/search.spec.ts
unticketed
Fixes issue with agency filter scroll behavior that added a bunch of empty space to the bottom of the page when the filter was expanded
1. start a local server on main with `npm run dev`
3. open the agency filter and scroll to the bottom of the page
4. _VERIFY_: you see a lot of unnecessary white space
5. repeat 1 - 3 on this branch
6. _VERIFY_: you do not see a lot of unnecessary white space
> fix whitespace bug by adding max height to filter content

- api/src/adapters/db/clients/postgres_client.py
- api/src/auth/api_jwt_auth.py
- api/src/services/opportunities_v1/get_opportunity.py
- api/src/services/users/login_gov_callback_handler.py
Fixes #4924
Adjust queries in the GET /opportunity endpoint and user auth logic to not automatically load as many relationships
https://docs.sqlalchemy.org/en/20/orm/queryguide/relationships.html
SQLAlchemy relationships allow you to configure how they load. By default, all relationships are lazy loaded which means that if you do `opportunity.current_opportunity_summary` it will emit a select statement to the DB to fetch the current opportunity summary record unless it already has fetched it. There are several loading strategies that you can set (see the above link), but besides lazy loading, `selectinload` tends to work the best. It works by emitting several select statements alongside your primary select statement all in one query to improve performance.
When we do a `selectinload("*")` …
> [Issue #4924] Adjust API queries for opps and users to select less

- frontend/src/components/search/SearchFilterAccordion/AgencyFilterAccordion.tsx
- frontend/src/components/search/SearchFilters.tsx
- frontend/tests/components/search/SearchFilterAccordion/AgencyFilterAccordion.test.tsx
Fixes part of #4889 
Depends on https://github.com/HHS/simpler-grants-gov/pull/4980
Adds facet counts to agency filter options
* refactors the agency accordion to depend on calls to fetch both search results and agency options list
3. _VERIFY_: agency filter options have proper facet counts
4. select some agency filter options
3. _VERIFY_: agency filter options have proper facet counts
> [Issue #4889] add facet counts to agency filter

- infra/nofos/app-config/env-config/environment_variables.tf
This is part of #5065 
Right now, the `ALLOWED_HOSTS` var is causing Django to throw a 500 error.
Until we figure that out, let's add this wildcard.
> [Issue #5065] Add 2 static env vars to the nofos app

- api/openapi.generated.yml
- api/src/api/application_alpha/application_route.py
- api/src/api/application_alpha/application_schemas.py
- api/src/services/applications/create_application.py
- api/tests/src/api/applications/test_application_routes.py
Fixes #4983
Add optional application name to start application endpoint. Updated API schema, added validation, and included tests for both custom name and default name scenarios.
This change allows users to specify a custom name when creating applications, with the opportunity number used as the default when no name is provided. 
See modified existing and new unit tests.
> [Issue #4983] Take in an optional application name to start application endpoint

- .github/workflows/ci-nofos.yml
- .github/workflows/deploy-nofos.yml
We are seeing the same container deployed on new runs and we think that the cache name is not unique enough.
> Make the nofos github workflow cache id more specific

- .github/workflows/deploy-nofos.yml
⚠️  [PR 338](https://github.com/HHS/simpler-grants-pdf-builder/pull/338) in simpler-nofos needs to go in first, otherwise this workflow will fail ⚠️ 
Fixes #5090 
Adds a database migration step as part of booting up the container. 
If we don't run this initially, the app doesn't even boot. 
If we don't run it continuously, our data model will corrode.
Note that this PR depends on [PR 338 in simpler-grants-pdf-builder](https://github.com/HHS/simpler-grants-pdf-builder/pull/338) to go in first, which adds the `db-migrate` command to the Dockerfile.
Once that one is merged, I'm confident this one will work because [I've run them both using their respective branches already](https://github.com/HHS/simpler-grants-gov/actions/runs/15121098983).
> [#5090] Add database migrations step to Nofos deploy workflow

- infra/nofos/app-config/env-config/environment_variables.tf
Makes progress on #5065 
Adds the `DOCRAPTOR_API_KEY` variable. 
This key is needed in order for us to print off un-watermarked PDF NOFO documents.
> [#5065] Add our first secret env var for the Nofos app: DOCRAPTOR_API_KEY

- api/src/api/application_alpha/application_route.py
- api/src/db/models/competition_models.py
- api/src/services/applications/auth_utils.py
- api/src/services/applications/get_application.py
- api/src/services/applications/get_application_form.py
- api/src/services/applications/submit_application.py
- api/src/services/applications/update_application_form.py
- api/src/validation/validation_constants.py
- api/tests/src/api/applications/test_application_routes.py
- api/tests/src/db/models/factories.py
- api/tests/src/services/applications/test_auth_utils.py
- api/tests/src/services/applications/test_submit_application.py
Fixes #4970 
Add `auth_utils` file that checks user authorized access to an application
Add `ApplicationUser` factory
Update existing and add new tests
Adjusted SQLAlchemy relationship cascade rules to prevent primary key errors when associating users with applications
After this is merged, other new tickets (e.g. 4984) may need to be updated to account for these changes.
See updated and new unit tests
> [Issue #4970] Set apply endpoints to only allow the owner of an application to interact

- infra/modules/service/main.tf
Makes progress on #5065 
If there is a load balancer resource, add its `dns_name` as an env var under: `LOAD_BALANCER_DNS_NAME`
The reason we are doing this is that some (Django) apps require [a list of domains to be whitelisted as "allowed hosts"](https://docs.djangoproject.com/en/5.2/ref/settings/#allowed-hosts), otherwise the app will refuse to run in production.
So, adding this to the environment will allow us to add the load balancer DNS name to our ALLOWED_HOSTS so that the app will boot up and not throw a 500 error.
> [#5065] Add load balancer name to task definition (if load balancer exists)

- .github/workflows/cd-nofos.yml
- .github/workflows/ci-nofos.yml
- .github/workflows/deploy-nofos.yml
- .github/workflows/vulnerability-scans-nofos.yml
Adds a vulnerability scan workflow to the NOFOs deployment process. Currently it's optional.
We have an obligation to vuln scan the apps that run within our infrastructure. 
CI outputs:
https://github.com/HHS/simpler-grants-gov/actions/runs/15147743231/job/42587548429?pr=5113
https://github.com/HHS/simpler-grants-gov/actions/runs/15147743231/job/42587548461?pr=5113
https://github.com/HHS/simpler-grants-gov/actions/runs/15147743231/job/42587548416?pr=5113
The scans are working, but all 3 are failing
> NOFOs vuln scans

- .github/workflows/lint-sprint-rollover.yml
Rolls over open tickets from the previous sprint into the current sprint. It runs on a schedule by default but can be triggered manually. @margaretspring and @chrisw-nava requested this along with other proposed changes to how we use  GitHub in [this document](https://docs.google.com/document/d/1B04xDeg_9PnMu_4COVo7O6bnhnDE_QvD5uCf2rke9Ik/edit?tab=t.0#heading=h.sl8i9r9yex9j).
Fixes #5109 
Adds `lint-sprint-rollover.yml` which uses the [move-to-next-iteration](https://github.com/marketplace/actions/move-to-next-iteration) GH action.
- This runs on a schedule or can be triggered manually.
- It only moves tickets from the previous sprint into the current sprint, so tickets left from earlier sprints won't be automatically moved over. This shouldn't be an issue though, once we have this …
> [Issue #5109] Adds GH action to rollover open sprint tix

- .github/workflows/vulnerability-scans-nofos.yml
Addresses #5141, but doesn't solve it.
This PR updates our Trivy configuration in the workflow to ignore a METADATA file in PyJWT. 
This file only contains documentation but Trivy is incorrectly flagging it as code.
The error message we are seeing is:
```
/app/.venv/lib/python3.13/site-packages/PyJWT-2.10.1.dist-info/METADATA (secrets)
=================================================================================
Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 1, HIGH: 0, CRITICAL: 0)
MEDIUM: JWT (jwt-token)
════════════════════════════════════════
JWT token
────────────────────────────────────────
/app/.venv/lib/python3.13/site-packages/PyJWT-2.10.1.dist-info/METADATA:89 (added by 'RUN |2 IS_PROD_ARG=0 GITHUB_SHA_ARG= /bi')
────────────────────────────────────────
87       >>> encoded = …
```
> [#5141] Ignore PyJWT METADATA file in nofos container trivy vuln scan

- api/src/api/schemas/extension/schema_fields.py
- api/tests/src/schemas/extension/test_schema_fields.py
- api/tests/src/schemas/schema_validation_utils.py
Fixes an issue where if a non-string is passed in a request body for something that is a str enum, it would cause a 500 error when failing to hash the value
We have a custom handler for str enums in our Marshmallow schema definitions. Internally we setup a dict that is a mapping of strings to enum values. If the value a user passes in is not hashable (like `{}`), it would break and return a 500 error. This fix adds a guardrail to shortcut the check to not break when a non-string is passed in.
Calling the opportunity search endpoint, a request like:
```json
{
"format": {},
"pagination": {
"page_offset": 1,
"page_size": 25,
"sort_order": [
{
"order_by": "opportunity_id",
"sort_direction": "ascending"
}
]
}
}
```
Would cause the error before because the format value which is a str enum would …
> [Unticketed] Fix error when a non-string is passed for an enum

- api/openapi.generated.yml
- api/src/api/competition_alpha/competition_schema.py
- api/src/api/opportunities_v1/opportunity_schemas.py
- api/src/api/schemas/shared_schema.py
- api/src/db/models/competition_models.py
- api/src/services/applications/application_validation.py
- api/src/services/applications/create_application.py
- api/src/services/applications/submit_application.py
- api/src/services/competition_alpha/get_competition.py
- api/src/validation/validation_constants.py
- api/tests/src/api/applications/test_application_routes.py
- api/tests/src/api/competition_alpha/test_competition_route_get.py
- api/tests/src/db/models/factories.py
- api/tests/src/services/applications/test_application_validation.py
- api/tests/src/services/applications/test_submit_application.py
Fixes #5080 and #5131
Adds additional fields to the competition response schema, most notably an `is_open` flag
Refactor some validation logic around how we determine if a competition is open to be more centralized on the DB model itself
Most of the fields come straight from the competition and are uneventful. The `is_open` flag is a calculated field that checks the competition open + close dates (and optionally grace period) to see if a competition is open. We already had implemented validations to check this field to block users from starting/submitting an application, but now the field is calculated in one central location that those validations now check instead. This required slightly rewording the error message, but its behavior is the same.
Running `make db-seed-local` will create …
> [Issue #5080] Add more fields to the competition response schema

- .github/workflows/vulnerability-scans-nofos.yml
Fixes #5141 
This is the last issue raised by the vuln scanners, but for this one we do want to keep the `:latest` tag.
Also, this is a `warning` level message, not a `FATAL` message.
Create a temporary .dockleignore file so that we can pass in this one rule.
The `:latest` tag is part of our CI/CD workflow, so removing it would not be good for us.
> [#5141] Ignore warning about ":latest" tags in NOFO docker images

- .github/linters/README.md
- .github/linters/scripts/inherit-parent-milestone.sh
- .github/linters/scripts/propagate-milestone-to-sub-issues.sh
- .github/workflows/ci-project-linters.yml
- .github/workflows/lint-inherit-parent-milestone.yml
- .github/workflows/lint-propagate-milestone-to-sub-issues.yml
Sets up linters to propagate milestones from parent issues (e.g. Epics) to their sub issues (e.g. tasks) per the request in [this document](https://docs.google.com/document/d/1B04xDeg_9PnMu_4COVo7O6bnhnDE_QvD5uCf2rke9Ik/edit?tab=t.0#heading=h.sl8i9r9yex9j).
Fixes #5144 
1. Adds script and GH action to inherit the parent issue's milestone when a new sub-issue is created
2. Adds script and GH action to update all sub-issues when a parent issue's milestone is changed
3. Adds these scripts to the README in the `.github/linter/` sub-directory
In the future there is a desire to propagate other values (e.g. fields from the product backlog board), but we're starting with milestone because that is the most commonly used and the easiest to implement.
This was tested in a sandbox repo and here's a …
> [Issue #5144] Propagate milestones to sub issues

- frontend/src/app/[locale]/dev/feature-flags/page.tsx
- frontend/tests/pages/dev/feature-flags/page.test.tsx
Fixes #4862 
Builds on prior work by Austin
Adds a button on the Feature Flag page that uses an a tag link to fully refresh the app while reseting the Feature Flags back to defaults.
Do a vanilla a tag so that we get the full app reload after reseting the feature flags cookie, since the flags can adjust nav, etc.
1. Checkout the branch
2. Run using `npm run dev`
3. Go to http://localhost:3000/dev/feature-flags
4. Try enabling and disabling things to get out of sync with the current default settings
5. Use the Reset button to verify they go back to defaults.
> [Issue #4862] Add a button that resets the feature flags cookie

- infra/nofos/app-config/env-config/variables.tf
This is to help us migrate our data to the NOFOs environments. Once the data is migrated, we can bring this back down to 2048 where it was originally.
> Double the RAM of nofo app containers to 4096 MB

- frontend/src/components/search/SearchDrawerFilters.tsx
- frontend/src/components/search/SearchFilterAccordion/AgencyFilterAccordion.tsx
- frontend/tests/components/search/SearchDrawerFilters.test.tsx
Fixes #5100
Adds status and agency filters to filter drawer
2. visit http://localhost:3000/search?_ff=filterDrawerOn:true
3. open the filter drawer
4. _VERIFY_: status and agency filters are present in the drawer and work just like they would in the sidebar
> [Issue #5100] status and agency filters in drawer

- frontend/src/app/[locale]/subscribe/actions.tsx
- frontend/tests/pages/subscribe/SubscriptionForm.test.tsx
- frontend/tests/pages/subscribe/subscribeEmailAction.test.tsx
Fixes #5183
Log more information in the NextJS server side logs (which will flow to NewRelic) when we have an error communicating with Sendy
Sendy had been timing out but nothing in the logs made that easy to discover
Examples of the 2 new errors that will log when we fail to reach Sendy or the Sendy call returns an error message:
> [Issue #5183] Better error logging when we have trouble talking to Sendy

- .github/workflows/build-and-publish.yml
- bin/is-image-published
Fixes #5188
This change attempts to locate the most recent git commit hash within each app folder (which is not the same as the top level commit for 2 of 3 apps) and use that to check if the container already exists and can just be deployed as already built.
Currently the deploy steps attempt to re-use already built containers (built for the lower environment). But due to it checking by the top level git hash associated with the merge/release, we will only ever find an existing container for the app that had the most recent git commit.
Previously, the build and deploy steps would have checked if the top level repo HEAD existed as a frontend container. But c60e4a2a0b113fd5d91551b1ae676a7a7930844a was created by my commits working on the deploy scripts, so there wouldn't be a FE container …
> [Issue #5188] Lookup the app folder specific most recent hash (no later than the current ref being deployed)

- frontend/src/app/[locale]/search/page.tsx
- frontend/src/constants/defaultFeatureFlags.ts
unticketed
fixes another bug with the search drawer feature flag (see https://github.com/HHS/simpler-grants-gov/pull/5196)
1. start a local server on this branch with `FEATURE_SEARCH_DRAWER_ON=true npm run dev`
3. _VERIFY_: search drawer experience is shown
2. visit http://localhost:3000/search?_ff=searchDrawerOn:false
3. _VERIFY_: search drawer experience is not shown
> [unticketed] fix another bug with filter drawer feature flag

- frontend/src/components/Footer.tsx
- frontend/src/components/drawer/Drawer.tsx
- frontend/src/components/drawer/DrawerUnit.tsx
- frontend/src/components/search/ClearSearchButton.tsx
- frontend/src/components/search/SearchDrawerHeading.tsx
- frontend/src/components/search/SearchVersionTwo.tsx
- frontend/src/hooks/useSearchParamUpdater.ts
- frontend/src/i18n/messages/en/index.ts
- frontend/src/styles/_uswds-theme-custom-styles.scss
- frontend/tests/components/search/ClearSearchButton.test.tsx
- frontend/tests/hooks/useSearchParamUpdater.test.ts
Fixes #4716
**NOTE** this functionality all lives behind the `filterDrawerOn` feature flag
* creates button that will clear out query params from URL
* adds this button to the filter drawer
* adjusts some drawer styling to be more in line with designs
This does not add a clear button outside the drawer as requirements on that implementation are still TBD
2. visit http://localhost:3000/search?_ff=filterDrawerOn:true
3. open filter drawer and apply filters
5. click "view results"
5. _VERIFY_: results have updated to reflect filter selection
6. click "clear filters" button
7. _VERIFY_: status filter returns to default state
8. click "view results"
9.  _VERIFY_: results have updated to reflect filter selection
10. enter a search term …
> [Issue #4716] add clear all filters button

- analytics/Dockerfile
- api/Dockerfile
- frontend/Dockerfile
Fixes #5216
Force upgrade for systemd to get the fixed version
Failed the daily vulnerability scan, so trying to pick up the fixed version that's not being picked up automatically yet.
https://github.com/HHS/simpler-grants-gov/actions/runs/15374800798/job/43258335513
> [Issue #5216] Update systemd for vuln failure

- bin/run-command
- infra/nofos/service/.terraform.lock.hcl
When we ran ECS tasks from the command line by calling `./bin/run-command ...`, it wasn't actually setting the environment correctly. In fact, it wasn't using the environment variable for anything.
This PR makes sure we call `terraform init` before we do the run command, so that it executes in the right environment.
It also updates the lockfile under nofos/service.
@coilysiren and I discussed this yesterday.
For me, I ran this against both nofo environments to test this:
- `./bin/run-command nofos dev '["ls"]'`
- `./bin/run-command nofos prod '["ls"]'`
Before this change, it would only ever run tasks in `nofos-dev`.
> Make sure we `terraform-init` inside of `run-command` 

- api/openapi.generated.yml
- api/src/api/application_alpha/application_schemas.py
- api/src/services/applications/create_application.py
- api/tests/src/api/applications/test_application_routes.py
Fixes #5265
When creating an application, create the `ApplicationUser` with is_application_owner set to `True`, include in schema.
This is a precursor to eventual work for roles.
See modified unit tests.
> [Issue #5265] Create application sets is_application_owner on ApplicationUser

- api/openapi.generated.yml
- api/src/api/application_alpha/application_schemas.py
- api/src/services/applications/get_application.py
- api/tests/src/api/applications/test_application_routes.py
Fixes #5259
Add new schemas
Add select for sam gov entity
Add tests
If the application has no organization, the value will be null. This data structure should mean that any org already on the app will just be passed through uneventfully.
See new unit tests
> [Issue #5259] Modify the GET /application endpoint to return organization info

- .github/workflows/build-and-publish.yml
- Makefile
The Release Publish step tags the Docker image that was built. It was using git rev-parse to figure out the hash to tag with, but the caller already knows a better hash, so utilize that if it's passed in
Allow caller to tell us the git hash for tagging purposes, if not supplied calculate it as it was already being figured out.
Causes the image to publish with the wrong tag if the change made that triggered the built happens outside the service folder (such as a change to our shared Terraform).
Tested locally
When passed in
When not passed in
> [Unticketed] Fix HASH passing to Release Publish

- .github/workflows/build-and-publish.yml
- Makefile
Fix follow up build problem 
I thought publish applied the tags, but publish pushes the existing tags, so caller of build needs to pass in the correct tags too
> [Unticketed] Need same hash on build as we use on Release

- frontend/src/components/search/Filters/RadioButtonFilter.tsx
- frontend/src/components/search/SearchDrawerFilters.tsx
- frontend/src/components/search/SearchFilterAccordion/SearchFilterCheckbox.tsx
- frontend/src/components/search/SearchFilterAccordion/SearchFilterOptions.ts
- frontend/src/components/search/SearchFilterRadio.tsx
- frontend/src/components/workspace/SavedSearchesList.tsx
- frontend/src/errors.ts
- frontend/src/i18n/messages/en/index.ts
- frontend/src/types/search/searchFilterTypes.ts
- frontend/src/types/search/searchQueryTypes.ts
- frontend/src/types/search/searchRequestTypes.ts
- frontend/src/utils/search/searchFormatUtils.ts
- frontend/src/utils/search/searchUtils.ts
- frontend/src/utils/testing/fixtures.ts
- frontend/tests/api/search/export/route.test.ts
- frontend/tests/components/search/Filters/RadioButtonFilter.test.tsx
- frontend/tests/components/search/SearchFilterRadio.test.tsx
- frontend/tests/components/search/SearchResults.test.tsx
- frontend/tests/components/workspace/SavedSearchesList.test.tsx
- frontend/tests/errors.test.ts
- frontend/tests/utils/Search/searchFormatUtils.test.ts
- frontend/tests/utils/search/searchUtils.test.ts
Fixes #4720
* adds a filter for opportunity close date to the filter drawer (behind the searchDrawerOn feature flag)
* refactors search filter helper functions to allow support for date range filters
* creates radio button filter components to support the new filter
Most of the fun here is in the changes to the functionality to:
* build the filters for the search request
* translate the saved search payload into query params
* support radio buttons
The hope is that these functions should now be flexible enough to pretty easily handle other filter types in the future
2. visit http://localhost:3000/search?_ff=searchDrawerOn:true
3. open the filter drawer
4. _VERIFY_: there is a close date filter using radio buttons to filter for …
> [Issue #4720] closing date filter

- frontend/src/components/search/SearchBar.tsx
- frontend/src/i18n/messages/en/index.ts
Fixes #4933
update search input label for drawer experience with keyword exclusion hint
This change is only visible with the `searchDrawerOn` filter flag active
2. visit http://localhost:3000/search?_ff=searchDrawerOn:true
3. _VERIFY_: label above search input shows keyword exclusion hint text
> [Issue #4933] add search keyword exclusion hint label

- api/src/adapters/aws/pinpoint_adapter.py
- api/src/task/notifications/base_notification.py
We're getting log messages that we "successfully" sent the message to Pinpoint, but Pinpoint doesn't send any emails. Adding logging of Pinpoint response values to help understand what's happening.
Fixes #5280 
Add one additional Pinpoint response field to the model and log all 4 response values to what we include in the success log.
> [Issue #5280] Add logging of Pinpoint response to aid troubleshooting 

- api/src/adapters/aws/pinpoint_adapter.py
- api/src/task/notifications/base_notification.py
- infra/frontend/service/main.tf
- infra/modules/service/access_control.tf
Get corrected permissions committed. Add more logging for troubleshooting why emails still aren't getting out even once permissions are manually applied to Dev.
- Fix the role we're applying the permissions to so that they apply when the Task runs, not when it gets kicked off.
- MessageId is not set on the Responses we're getting back 
- Adding TraceId to try to track these failing requests since they don't get MessageIds
We had the permissions on the wrong role. Fixing that and when manually applied now we get additional failures because the way our messages are failing to send seems to mean they don't have MessageIds. 
```
"[\"<class 'pydantic_core._pydantic_core.ValidationError'>\",\"1 validation error for PinpointResponse\\nResult.`<emailAddress>`.MessageId\\n  Field required …
```
> [Issue #5280] Pinpoint permissions and logging fixes

- .github/workflows/ci-nofos.yml
The NOFO app container we use to run tests is not the one we should deploy.
We have an [`IS_PROD`](https://github.com/HHS/simpler-grants-pdf-builder/blob/main/Dockerfile#L6) variable that sets up our prod configuration, but if we turn it on from the get go, some of our tests fail.
Previously, we would do this:
- Build container
- Run tests
- Cache image
- Another workflow deploys cached image
Now, we do this:
- Build container
- Run tests
- Build PROD container
- Cache prod image
- Another workflow deploys cached image
It works!
https://github.com/HHS/simpler-grants-gov/actions/runs/15619933756
> NOFOs: Build a "prod" image after tests pass

- frontend/next-env.d.ts
- frontend/src/app/[locale]/opportunity/[id]/page.tsx
- frontend/src/components/application/OpportunityCard.tsx
- frontend/src/components/opportunity/OpportunityHistory.tsx
- frontend/src/components/search/SearchFilterAccordion/SearchFilterOptions.ts
- frontend/src/components/search/SearchResultsListItem.tsx
- frontend/src/i18n/messages/en/index.ts
- frontend/src/types/opportunity/opportunityResponseTypes.ts
- frontend/tests/components/opportunity/OpportunityHistory.test.tsx
- frontend/tests/e2e/search/search-navigate.spec.ts
- frontend/tests/e2e/search/search.spec.ts
Fixes #4723
User facing terminology updates in various opportunity related locations
* "award ceiling" -> "award maximum"
* "award floor" -> "award minimum"
* for opportunity status values: "posted" -> "open"
* for expressing the value of an opportunity's "post_date": 
* if the opportunity is in a "forecasted" status: "forecast posted date"
* otherwise: "posted date"
3. _VERIFY_: status filter option displays "Open"
4. _VERIFY_: search results for "posted" opportunities display "Posted date"
5. _VERIFY_: search results for "forecasted" opportunities display "Forecast posted date"
6. _VERIFY_: search results display "Award maximum" and "minimum"
7. open both a forecasted and posted opportunity …
> [Issue #4723] update opportunity terminology

- Makefile
Fixes #5352
Update the way the Makefile grabs "current git hash" so it's per App aware. 
This failed in the cron run vulnerability scans because unlike calls from push or release GitHub events, the cron job doesn't have the context of the current git hash it's running under so it was falling back to the old style of picking a hash. We had tried to avoid changing this, to preserve any backward compatibility and minimize delta from the template but this is a necessary code path we need to support.
> [Issue #5352] Follow up for per App image hashes

- api/openapi.generated.yml
- api/src/api/application_alpha/application_schemas.py
- api/src/db/models/competition_models.py
- api/src/services/applications/get_application.py
- api/src/services/applications/get_application_form.py
- api/tests/src/api/applications/test_application_routes.py
Fixes #5087
Add `application_attachments` property to `ApplicationForm`
Add `application_attachments ` to `ApplicationFormGetResponseDataSchema` 
Update / add tests
Update the GET /application/../application_form endpoint to return application attachments.
See unit tests
> [Issue #5087] Update GET application form to return attachment info

- api/openapi.generated.yml
- api/src/api/application_alpha/application_route.py
- api/src/api/application_alpha/application_schemas.py
- api/src/services/applications/create_application_attachment.py
- api/src/services/applications/update_application_attachment.py
- api/tests/src/api/applications/test_application_attachment_routes.py
- api/tests/src/services/applications/test_update_application_attachment.py
Fixes #5085
Add route and associated service.
Add `ApplicationAttachmentUpdateRequestSchema` and `ApplicationAttachmentUpdateResponseSchema` to handle request/response.
Add tests covering multiple scenarios.
Much of this has been reused from other existing routes / services.
Route updates an attachment. It should effectively be the same as the other one, but will handle "updating" the file for the given attachment ID. Deletes old attachment path if new path is provided. Uses secure_filename to regenerate a file name, if needed.
See added unit tests.
> [Issue #5085] Create PUT `/applications/:application_id/attachments/:attachment_id` endpoint

- api/src/services/users/login_gov_callback_handler.py
- api/src/services/users/organization_from_ebiz_poc.py
- api/src/task/sam_extracts/create_orgs_from_sam_entity.py
- api/src/util/sam_gov_utils.py
- api/tests/src/services/users/test_login_gov_callback_handler_ebiz_poc.py
- api/tests/src/services/users/test_organization_from_ebiz_poc.py
Fixes #5248
For new users, link to organization as organization owner if applicable
Refactor `link_sam_gov_entity_if_not_exists` to be reused with optional metrics.
Add tests
Heavily reuses logic in https://github.com/HHS/simpler-grants-gov/issues/5248, as most of the complexity in this task is reusing the `link_sam_gov_entity_if_not_exists` function.
Additional context provided in ticket: https://github.com/HHS/simpler-grants-gov/issues/5250
See new unit tests.
> [Issue #5248] When a user logs in for the first time - check if they are an ebiz POC and create their org

- .grype.yml
- analytics/poetry.lock
- api/Dockerfile
- api/poetry.lock
- api/src/data_migration/transformation/transform_oracle_data_task.py
- api/src/db/migrations/alembic.ini
- api/src/services/applications/create_application_attachment.py
- api/src/task/notifications/base_notification.py
- api/tests/src/adapters/db/clients/test_postgres_client.py
- api/tests/src/api/applications/test_application_attachment_routes.py
- api/tests/src/api/opportunities_v1/test_opportunity_route_search.py
- api/tests/src/db/test_migrations.py
- api/tests/src/services/applications/test_update_application_attachment.py
Updated packages for vulnerability scans - which then needed the following fixes:
* MyPy ignore for how we setup Metrics class in a few cases (might be a better way to handle typing, didn't look too deep and just ignored)
* MyPy recognized that the filename can be null for our attachment work, added some guardrails and tests to account for it
* Alembic had a new warning for a config value they added being recommended, set it to the default (shouldn't matter for us I think?)
* An ignore we had (B1) for some logging stuff is no longer in the ruff rules
> [Unticketed] Update package versions for vulnerability scans

- frontend/src/components/LoginModal.tsx
- frontend/src/components/user/OpportunityCompetitionStart.tsx
- frontend/src/components/workspace/CompetitionStartFormIndividiual.tsx
- frontend/src/components/workspace/StartApplicationModal.tsx
- frontend/src/i18n/messages/en/index.ts
- frontend/src/services/fetch/fetchers/clientApplicationFetcher.ts
- frontend/tests/components/workspace/StartApplicationModal.test.tsx
Fixes #5123
1. Start app button is now visible for anon users and directs user to login if they aren't already logged in: ![image](https://github.com/user-attachments/assets/03f56cb1-a628-49be-85cb-558dbbc41401)
2. Provides a specific error for "unauthorized" for if the user times out while submitting the app:
Keeps the same error if there is another error with the API:
It would be ideal perhaps to provide more than an error state, but that would blow up the scope of the ticket.
1. start dev server and api server locally
2. go to an opportunity with a competition (112 or 114). You can check the `opportunity_id` in the competition table in the database to be sure
3. click "Start new application" when not logged in. You should be directed to login
4. login and find you are rerouted back to …
> [Issue #5123] Update start application auth handling

- infra/api/service/main.tf
- infra/modules/service/load_balancer.tf
- infra/modules/service/main.tf
- infra/modules/service/variables.tf
Fixes #5286
We need an ALB that has mutual TLS Client Certificate Passthrough on for the SOAP Proxy/Router but that prompts browsers to ask for a client certificate.
Move the SOAP Proxy/Router off to it's own ALB that is configured almost identically, but supports mTLS passthrough. This also gives us the flexibility to use a unique DNS name for this and split it's traffic load off to other containers in the future if needed.
Ran the terraform apply locally to validate everything was working and happy both in API (which should get an mTLS ALB and frontend which should be totally unaffected by this change).
> [Issue #5286] Enable mTLS on a SOAP Proxy/Router specific ALB

- api/src/form_schema/rule_processing/json_rule_util.py
- api/src/form_schema/rule_processing/json_rule_validator.py
- api/tests/src/form_schema/rule_processing/test_json_rule_processor.py
- api/tests/src/form_schema/rule_processing/test_json_rule_util.py
Fixes #5388
Modify the rule validator for validating attachment IDs to also handle the value we're validating being a list of attachment IDs
Attachment ID questions in our forms can either be a single ID, or a list of IDs (ie. the question asks you to upload multiple files). This handles supporting that behavior, as well as building the path to include the index in the list. We know the SF424 that we're likely going to need to support has at least one question like this.
> [Issue #5388] Add attachment ID support for list fields in validation

- api/Dockerfile
Getting several vulnerability scans for a libxml2 Debian package. Forcing that to upgrade
> [Unticketed] Fix XML vulnerabilities in Debian

- api/src/data_migration/transformation/transform_oracle_data_task.py
Fixes #5518
This pr enables the transform ecs task to run the transform competition automatically in all environments.
This is required for syncing competition data from grants.gov into simpler.
This is validated as part of [this](https://github.com/HHS/simpler-grants-gov/issues/4483)
> [Issue #5518] Enable transform competition to ECS task.

- api/src/task/notifications/search_notification.py
- api/tests/src/task/notifications/test_search_notification.py
Work for #5605
We noticed in testing that of the 3 email notifications, the saved search one wasn't linking the user to the Opportunity page. So we added that.
> [Issue #5605] Include links to Opportuntiy page in Saved Search emails 

- api/src/form_schema/forms/sf424a.py
- api/src/form_schema/jsonschema_validator.py
- api/tests/lib/seed_form.py
- api/tests/lib/seed_local_db.py
- api/tests/src/form_schema/forms/test_sf424.py
- api/tests/src/form_schema/forms/test_sf424a.py
Fixes #5520
Setup the JSON schema for an SF424A budget form
Slightly adjustment to the error message for maxItems
Adjustments to DB seed script to add this form to the local competition + adjusted how we setup the other competition that uses more generic forms.
This is the complex budget form that has a whole bunch of tables, but the data structure works a bit differently internally as line items cross tables. I've tried my best to label the fields and where they appear.
I adjusted the maxItems validator because the message dumped the entire array into the message which if something like the activity line items exceeded was just unreadable due to the size.
Something wasn't working on the frontend for me to view the forms (not just these forms, but any), this form has almost nothing in it …
> [Issue #5520] Create the JSON schema for a SF424A

- frontend/src/services/logger/simplerLogger.tsx
Work for #5608
If the middleware logger detects it's a request to /health, pull a random number to only log 1/10 actual hits to /health.
If my math is right, we're sending about 622MB of health check logs a month to NewRelic/CloudWatch.
1. Checkout the branch
2. Run `npm run dev | grep "/health"`
3. Refresh http://localhost:3000/health multiple times
a. Note that not every request logs the JSON info style log line
4. Validate that other URLs still log as expected
> [Issue #5608] Sample logs for /health

- .github/workflows/ci-frontend-e2e.yml
- frontend/src/components/search/Filters/AgencyFilterContent.tsx
- frontend/src/components/search/SearchFilters.tsx
- frontend/src/components/search/SearchVersionTwo.tsx
- frontend/src/services/fetch/endpointConfigs.ts
- frontend/src/services/fetch/fetchers/agenciesFetcher.ts
- frontend/src/services/fetch/fetchers/clientAgenciesFetcher.ts
- frontend/src/services/fetch/fetchers/fetchers.ts
- frontend/tests/components/search/Filters/AgencyFilterContent.test.tsx
- frontend/tests/components/search/SearchFilters.test.tsx
- frontend/tests/services/fetch/fetchers/agenciesFetcher.test.ts
Work for #5243 
* uses the agency search endpoint for all agency data fetches from the frontend
* pass correct filter params to limit agency response to agencies associated with at least one "posted" or "forecasted" opportunity
This will fix a number of bugs with the current agency search behavior, caused by a mismatch between the initially fetched set of agencies (which were filtered for active agencies), and the agencies returned from results (which were not)
1. point your local environment at the dev api server
2. start a local server on this branch
3. visit http://localhost:3000/search?status=none
4. _VERIFY_: all agency options displayed have a > 0 facet count
5. search agencies for `"food and drug"`
6. _VERIFY_: no search results appear (for further verification test this out in …
> [Isse #5243] fetch agencies the right way

- api/tests/src/task/opportunities/test_store_opportunity_version_task.py
Fix a few tests that were flaky, likely due to the UUID issue causing the ordering to change (going from int primary key to uuid)
> [Unticketed] Fix a flaky test after the UUID work

- frontend/src/app/[locale]/maintenance/page.tsx
unticketed
fixes centering text on maintenance page
1. start a local server
2. visit http://localhost:3000/maintenance
3. _VERIFY_: looks ok
> [unticketed] correctly center maintenance text

- infra/api/app-config/env-config/scheduled_jobs.tf
Work for #5534
Enabled the following scheduled jobs
- load-transform
- load-search-opportunity-data
- export-opportunity-data
- create-analytics-db-csvs
- load-search-agency-data
Re enabling these scheduled jobs to automatically run since UUID migration is complete.
> [Issue #5534] Enabled scheduled jobs 

- infra/api/app-config/dev.tf
- infra/api/app-config/env-config/outputs.tf
- infra/api/app-config/env-config/variables.tf
- infra/api/app-config/prod.tf
- infra/api/app-config/staging.tf
- infra/api/service/main.tf
- infra/modules/service/load_balancer.tf
- infra/modules/service/variables.tf
Work for #5379 
Following the process for CDN domain names and certificate references, hook up the mtls domain and certificate for the soap.<env>.simpler.grants.gov URLs.
Manually deployed branch to Dev using terraform apply and tested successfully.
> [Issue #5379] Hook up MTLS ceritificates to MTLS ALBs

- api/openapi.generated.yml
- api/src/api/users/user_routes.py
- api/src/api/users/user_schemas.py
- api/src/services/users/get_user_applications.py
- api/tests/src/api/users/test_user_application_routes.py
- api/tests/src/services/users/test_get_user_applications.py
Work for #5475
Add new Application List endpoint, associated schema objects
Add service to `get_user_applications`
Add unit tests
In order to create an application list view, we need to create an endpoint to return all in-progress and completed applications.
See attached unit tests
> [Issue #5475] Add application list view endpoint

- frontend/src/i18n/messages/en/index.ts
Work for #4940 (partial)
changes language from published to posted date in search results table
2. visit http://localhost:3000/search?_ff=searchTableOn:true
3. _VERIFY_: language in agency column data reads "posted date"
> [Issue #4940] 'published' -> 'posted date' in search results table

- api/tests/lib/seed_agencies.py
- api/tests/lib/seed_local_db.py
- frontend/src/app/[locale]/search/page.tsx
- frontend/src/app/api/agencies/handler.ts
- frontend/src/components/search/Filters/AgencyFilterContent.tsx
- frontend/src/components/search/SearchDrawerFilters.tsx
- frontend/src/components/search/SearchFilterAccordion/AgencyFilterAccordion.tsx
- frontend/src/components/search/SearchFilters.tsx
- frontend/src/components/search/SearchVersionTwo.tsx
- frontend/src/constants/search.ts
- frontend/src/services/fetch/fetchers/agenciesFetcher.ts
- frontend/src/services/fetch/fetchers/clientAgenciesFetcher.ts
- frontend/src/utils/search/searchUtils.ts
- frontend/tests/api/agencies/route.test.ts
- frontend/tests/components/search/Filters/AgencyFilterContent.test.tsx
- frontend/tests/services/fetch/fetchers/agenciesFetcher.test.ts
- frontend/tests/utils/search/searchUtils.test.ts
Work for #4934
Allows agency search calls to filter agencies based on opportunity statuses. All responses should include agencies with at least one opportunity with a "posted" or "forecasted" status. If the current opportunity search includes "archived" or "closed" opportunities as well, the agency search should also return agencies that have "archived" or "closed" opportunities respectively.
* adds two agencies and some opportunities to the seed in order to test situations specific to agencies that contain only closed or archived opportunities
3. _VERIFY_: "Agency of closed opportunities" and "Agency of archived opportunities" do not appear in the list of agencies in the agency filter
4. select the "archived" …
> [Issue #4934] fetch agencies by status

- frontend/.pa11yci-desktop.json
- frontend/.pa11yci-mobile.json
- frontend/next.config.js
- frontend/src/app/[locale]/layout.tsx
- frontend/src/components/ScriptInjector.tsx
- frontend/src/constants/environments.ts
- frontend/src/styles/_uswds-theme-custom-styles.scss
- frontend/src/utils/injectableScripts.tsx
- frontend/tests/components/ScriptInjector.test.tsx
Work for #5582
Adds a from ethino to add a CSAT (customer satisfaction) survey on search pages. Since ethnio doesn't support the sort of page level targeting that need, this also adds a conditional script tag injector component.
Along with the 7/16 / 7/19 search launch we want to gauge user satisfaction. This survey should go out with the changes to enable the full search v2 experience.
Introduces a check for CI into the layout to avoid e2e or test failures due to script behavior that does not need to be covered by testing
Note that ad blockers may block this script, I've had good luck using Chrome private windows for testing
3. visit http://localhost:3000
4. _VERIFY_: a survey popup does not open
5. click "search" nav item
6. _VERIFY_: a survey …
> [Issue #5582] add ethnio script for search launch survey

- documentation/frontend/development.md
Update the API make commands referenced in the FE docs to ones that are more wholistic. Addresses some snags Chris Freeman hit while trying to poke around in our E2E testing process.
> [Unticketed] Clean up docs for better steps to get someone from 0 to 1 on local FE

- frontend/src/app/[locale]/opportunity/[id]/page.tsx
Work for #5634
If an Opportunity page is loaded using an Int ID, redirect to the same opportunity URL but with the new UUID
1. Checkout the branch
2. Go to an int ID: https://localhost:3000/opportunity/3
3. Verify you're redirected to a UUID URL
4. Do a search
5. Click a search result
6. Verify the page loads without any redirect
> [Issue #5634] Redirect prior int Opp ID to new UUID

- frontend/src/components/search/SaveSearchSelector.tsx
- frontend/src/hooks/useSearchParamUpdater.ts
- frontend/src/utils/injectableScripts.tsx
Work for #4412
Changes logic for resetting selected saved search state that was not airtight, and resulted in the state not being reset when search paramters were updated after applying a saved search
3. log in
4. set up a search to save with a keyword and various filters selected
5. save the search
6. _VERIFY_: correct saved search appears in saved search drop down
7. update filters
8. _VERIFY_: saved search drop down resets to default state
9. select saved search from drop down
10. _VERIFY_: correct saved search appears in saved search drop down
11. update keyword term
8. _VERIFY_: saved search drop down resets to default state
9. visit http://localhost:3000/saved-search-queries
10. click on a saved search
10. …
> [Issue #4412] fix unstable saved search select state

- api/src/form_schema/forms/sf424b.py
- api/tests/lib/seed_local_db.py
- api/tests/src/form_schema/forms/test_sf424b.py
Work for #5601
Add the SF424B form definition
Another short form, nothing new here.
`make db-seed-local` now has the form added, going to the competition it creates has a form that looks like this right now:
> [Issue #5601] Setup SF424B form

- api/src/services/applications/application_validation.py
- api/src/services/applications/get_application_form.py
- api/src/services/applications/update_application_form.py
- api/src/validation/validation_constants.py
- api/tests/src/api/applications/test_application_routes.py
- api/tests/src/services/applications/test_application_validation.py
- api/tests/src/services/applications/test_submit_application.py
Work for #5239
Added new validation logic for `is_included_in_submission` flag on application forms
Added new validation error type `MISSING_INCLUDED_IN_SUBMISSION`
Updated `validate_application_form` to implement conditional validation logic based on form requirement status / inclusion flag
Add tests
Gives users explicit control over validation for non-required forms. Previously, all forms (required and non-required) would always run JSON schema validation
See updated unit tests
> [Issue #5239] Allow users to skip validation for non-required forms

- api/src/form_schema/forms/budget_narrative_attachment.py
- api/src/form_schema/forms/project_narrative_attachment.py
- api/tests/lib/seed_local_db.py
- api/tests/src/form_schema/forms/test_budget_narrative_attachment.py
- api/tests/src/form_schema/forms/test_project_narrative_attachment.py
Work for #5697
Work for #5698 
Add JSON schema for Budget Narrative Attachment Form
Add JSON schema for Project Narrative Attachment Form
These two forms are identical as far as the schemas go with just a minor difference in file name and some of the text a user will see.
Note that in the current PDF the attachment is setup as two fields a "required" attachment and then an "optional" list of attachments. But in the underlying data schema, it's a list like what I've done here.
`make db-seed-local` will create an opportunity+competition with these attached. They don't quite render right because the attachment logic isn't fully implemented on the frontend / UI schema would need to be updated too.
> [Issue #5697 & #5698] Add Budget & Project Narrative Attachment Forms

- api/src/task/notifications/closing_date_notification.py
- api/src/task/notifications/opportunity_notifcation.py
- api/src/task/notifications/search_notification.py
- api/tests/src/task/notifications/test_opportunity_notification.py
- api/tests/src/task/notifications/test_search_notification.py
Work for #5737 
Remove the temporary language that flagged the first batch of email notification emails as testing while we validated the content and recipients.
> [Issue #5737] Remove email test disclaimer from subjects

- frontend/src/components/search/SearchResultsTable.tsx
- frontend/src/components/search/SearchResultsView.tsx
- frontend/tests/components/search/SearchResultsTable.test.tsx
- frontend/tests/components/search/__snapshots__/SearchResultsTable.test.tsx.snap
Work for #5733
The non-table view had ids on the Links (now a tags) so that we could report on how often users click on the top 3 Opportunities in the Search Results.  This adds that id to the Table layout so we can continue reporting on that.
> [Issue #5733] Restore Click Thru Tracking metadata

- api/src/db/models/competition_models.py
- api/src/form_schema/forms/project_abstract_summary.py
- api/src/form_schema/forms/sf424.py
- api/src/form_schema/forms/sflll.py
- api/src/form_schema/rule_processing/json_rule_field_population.py
- api/tests/src/form_schema/rule_processing/conftest.py
- api/tests/src/form_schema/rule_processing/test_json_rule_field_population.py
- api/tests/src/form_schema/rule_processing/test_json_rule_processor.py
Fixes #5419
This adds additional prepopulation rules that we can configure.
All of the newly added rules are pretty straightforward, UEI is a bit odd for applications without orgs because they have to get a UEI still, which is that odd `000000000INDV` one which is copied from how grants.gov handles this.
I reworked tests and added dedicated tests for these to minimize the complexity of the test setup a bit.
> [Issue #5419] Add more prepopulation rules

- frontend/src/components/search/SearchAnalytics.tsx
- frontend/src/types/search/searchQueryTypes.ts
Work for #5721
we're doing this to primarily track incoming links from grants.gov
Could test this with NR locally but I didn't bother
1. after deploy, visit http://dev.simpler.grants.gov/search?utm_source=test
2. _VERIFY_: you see a hit for this query in new relic
```
FROM BrowserInteraction SELECT search_param_utm_source WHERE appName = 'frontend-dev' SINCE 1 day ago
```
> [Issue #5721] some non-search related query params as custom new relic attributes

- frontend/src/app/[locale]/search/page.tsx
- frontend/src/components/search/SearchVersionTwo.tsx
- frontend/src/i18n/messages/en/index.ts
Work for #5763 
- Edits the BetaAlert text on the /search page to link to an Ethnio survey (instead of contact us email or prompting GitHub issue submission) 
See https://docs.google.com/document/d/1HPYT8YXcGfjoGFOAM06BN9OJ8swdegBzKisJ61OcT7o/edit?tab=t.0 
- Load the search page
- Click the "1-minute survey" link in the alert
- It should open an Ethnio survey in a new tab
> [Issue 5763] Update search alert w/ ethnio survey link

- analytics/Dockerfile
- api/Dockerfile
- frontend/Dockerfile
Recent Platform template updates note that we should be doing both apt-get clean and deleting the lists (which we were already doing).
> [Unticketed] Update to latest template pattern for post apt-get install cleanup

- api/bin/setup-soap.sh
- api/src/legacy_soap_api/legacy_soap_api_auth.py
- api/src/legacy_soap_api/legacy_soap_api_proxy.py
- api/tests/src/legacy_soap_api/test_legacy_soap_api_auth.py
Fixes #4515
Adjust how we define certs to include an ID that we can log
We want to have an ID for each cert that isn't secret. Now the env var JSON will have an ID in it alongside the cert for logging. 
Before we can merge this, we'll need to update the env var in dev/staging/prod in parameter store, but holding on that until right before I merge to avoid breaking things / confirm this approach.
Delete your existing soap-api.env file and run `make setup-soap-proxy` to generate the env var in the same format.
Testing using the example SOAP call in the cert secret from 1password you'll now see the logs have the ID value of that cert:
> [Issue #4515] Add unique ID to certs in SOAP calls

- api/tests/lib/seed_local_db.py
- frontend/src/app/[locale]/opportunity/[id]/page.tsx
- frontend/src/components/opportunity/OpportunityAwardGridRow.tsx
- frontend/src/components/opportunity/OpportunityAwardInfo.tsx
- frontend/src/components/opportunity/OpportunityDownload.tsx
- frontend/src/components/opportunity/OpportunityEligibility.tsx
- frontend/src/components/opportunity/OpportunityHistory.tsx
- frontend/src/components/opportunity/OpportunityIntro.tsx
- frontend/src/components/opportunity/OpportunityStatusWidget.tsx
- frontend/src/styles/_uswds-theme-custom-styles.scss
- frontend/tests/components/opportunity/OpportunityAwardGridRow.test.tsx
Work for #5383
Improves spacing on opportunity detail page
Looks like some vertical spacing related to first and last <p> tag children was lost during the typography refactor. This adds it back
1. find your local opportunity that has a long description and attachments
2. start a local server on this branch
3. visit http://localhost:3000/opportunity/<your complete opportunity id>
4. _VERIFY_: spacing matches screenshot, mobile an desktop views look correct
> [Issue #5383] opportunity detail margins

- api/openapi.generated.yml
- api/src/api/opportunities_v1/opportunity_schemas.py
- api/tests/src/task/notifications/test_opportunity_notification.py
Allow `version_number` to be null in search response schema
I setup an opportunity manually in dev/staging for our apply pilot and set this to null in the DB, but when search tries to return it, it errors because the schema validation. This just makes it work.
Create an opportunity locally like this via `make console`
```py
x = f.OpportunityFactory()
x.current_opportunity_summary.opportunity_summary.version_number = None
dbs.commit()
```
Run `make populate-search-opportunities`
Go to localhost:3000/search and it shouldn't error.
> [Unticketed] Allow version_number to be null in search response

- api/src/legacy_soap_api/legacy_soap_api_auth.py
- api/src/legacy_soap_api/legacy_soap_api_client.py
- api/src/legacy_soap_api/legacy_soap_api_config.py
- api/src/legacy_soap_api/legacy_soap_api_constants.py
- api/src/legacy_soap_api/legacy_soap_api_proxy.py
- api/src/legacy_soap_api/legacy_soap_api_routes.py
- api/src/legacy_soap_api/simpler_soap_api.py
- api/src/logging/flask_logger.py
- api/tests/src/legacy_soap_api/test_legacy_soap_api_routes.py
Fixes #5684
Add a `soap_api_event` to most logs in the SOAP API to easily get metrics for various scenarios.
Adjusted API-wide logging to always put the class whenever an exception is logged.
The soap api events are just to make graphs and metrics easy in New Relic.
A few other miscellaneous changes:
* Removed uses of `traceback` in favor of `exc_info=True` to keep how errors get formatted in logs consistent.
* Either use exception or info logs
* Added a few additional values to all logs at the start of the request.
No logic behavior should have been changed by this, just a bunch of log additions/adjustments.
Hard to test every scenario since I'm not sure how we'd even cause some of them locally, but at least in some cases it logs:
> [Issue #5684] Update logging in SOAP endpoint to easily pull out various scenarios

- frontend/src/app/[locale]/login/page.tsx
This was a quick fix for the redirect.
becomes:
This could use an actual design and better content, but this took a few mins and looks better.
> [Unticketed] Update redirect on login page

- api/src/form_schema/forms/sflll.py
- frontend/package.json
- frontend/src/components/applyForm/actions.ts
- frontend/src/components/applyForm/formDataToJson.ts
- frontend/src/components/applyForm/types.ts
- frontend/src/components/applyForm/utils.tsx
- frontend/src/components/applyForm/validate.ts
- frontend/src/components/applyForm/widgets/CheckboxWidget.tsx
- frontend/src/components/applyForm/widgets/RadioWidget.tsx
- frontend/src/components/applyForm/widgets/SelectWidget.tsx
- frontend/src/components/applyForm/widgets/TextAreaWidget.tsx
- frontend/src/services/fetch/fetchers/applicationFetcher.ts
- frontend/tests/components/applyForm/utils.test.tsx
- frontend/tests/components/applyForm/validate.test.ts
- frontend/tests/utils/formDataToJson.test.ts
Work for #5701 
Adds UI implementation for the "Disclosure of Lobbying Activities (SF-LLL)" form
This relies on some changes from https://github.com/HHS/simpler-grants-gov/pull/5717, and is based off of that branch. This PR will merge into that branch rather than main.
Other than form implementation, this PR handles:
* properly referencing nested json schema properties. HTML input ids will now reflect the nested nature of the schema, using `--` as a delimiter for nested paths.
* transforming a flat set of form data into a properly nested format. This draws on the library here, but required some customization for our use case, so copy pasted it over and made the necessary changes https://github.com/ArturKot95/FormData2Json
* proper validation indicators for some nested fields. Address/city …
> [Issue #5701] SF-LLL form

- frontend/src/app/[locale]/opportunity/[id]/page.tsx
- frontend/src/components/SaveIcon.tsx
- frontend/src/components/search/SearchResultsTable.tsx
- frontend/src/components/user/OpportunitySaveUserControl.tsx
- frontend/src/styles/_uswds-theme-custom-styles.scss
- frontend/tests/components/SaveIcon.test.tsx
- frontend/tests/components/search/SearchResultsTable.test.tsx
- frontend/tests/components/search/__snapshots__/SearchResultsTable.test.tsx.snap
- frontend/tests/components/user/OpportunitySaveUserControl.test.tsx
Work for #5759 
Added ability to opportunities from search results table. 
Had to manually implement CSS classes to change how button was displayed in this context without impacting how the button is used on the opportunity page.
> [Issue #5759] Add ability to save opportunities from search results table

- api/src/services/applications/application_validation.py
- api/tests/src/api/applications/test_application_routes.py
- api/tests/src/services/applications/test_application_validation.py
Fixes / Work for #5489 
Set `do_post_population=True`
Set `application_form.application_response = context.json_data` in validate
Update tests
Signature and current date would be disabled while filling out the application, and then we would auto-populate them upon submission.
See updated unit tests
> [Issue #5489] Run post-population during submit flow

- frontend/src/app/[locale]/maintenance/page.tsx
- frontend/src/components/ClientMaintenanceCheck.tsx
- frontend/tests/pages/maintenance/page.test.tsx
Work for #4994
Stop redirecting from /maintenance to the home page if no "major" features are off. This wasn't working reliably and we've seen from past downtime that folks don't seem to end up "stuck" on the maintenance page.
> [Issue #4994] Drop redirect when not in maintenance mode for now

- api/src/task/sam_extracts/process_sam_extracts.py
- api/tests/src/task/sam_extracts/test_process_sam_extracts.py
Fixes / Work for #5314 
Modified sam.gov extract parsing to account for duplicate UEIs in a given extract file (see below for context)
Modified extract processing to use a bit less memory, not loading entire entity table into memory, and processing file line-by-line instead of as a big text blob.
A few other refactors for simplifying logic.
I assumed that we would only receive a single row in a given extract file for a UEI, but it turns out that was wrong. If a given entity has multiple "EFT Indicators" then each of those will be a separate row in the data we receive. This indicator is related to bank account information according to the docs, and is for the most part irrelevant to us. From validating the monthly extract, I verified that the only two fields that ever differ across these …
> [Issue #5314] Adjust sam.gov extract parsing based on testing

- frontend/src/i18n/messages/en/index.ts
- frontend/src/types/search/searchQueryTypes.ts
- frontend/src/types/search/searchRequestTypes.ts
- frontend/src/utils/search/searchFormatUtils.ts
- frontend/src/utils/testing/fixtures.ts
- frontend/tests/components/workspace/SavedSearchesList.test.tsx
Work for #5591 
Adds support for recalling the "and/or" selection of a user's saved search when applying it from the dropdown or workspace page
Since the operator only matters when there is a keyword term, we won't apply or show it to users unless the saved search contains a keyword
3. log in
4. enter a keyword term and hit search
5. save your search
6. remove the keyword and select a filter
7. save your search
8. visit your saved searches page
9. _VERIFY_: you see your two saved searches, one with an entry for "Query and/or operator" and one without
> [Issue #5591] add and|or operator to frontend side saved searches

- frontend/src/app/[locale]/saved-opportunities/layout.tsx
- frontend/src/i18n/messages/en/index.ts
Fixes #3797 
update saved opportunities page metadata description
2. visit http://localhost:3000
3. log in
4. click over to saved opportunities page
5. inspect page source
6. _VERIFY_: document head contains a meta tag looking like `<meta name="description" content="View your saved funding opportunities.">`
> [Issue #3797] update saved opportunities page metadata description

- api/Makefile
- api/src/task/__init__.py
- api/src/task/generate_internal_token.py
- documentation/api/auth/short-lived-auth.md
Fixes #5851
Create docs, makefile command, and utility to create an internal JWT token that can be used to authenticate with endpoints that accept internal authentication.
We want to create a local-only script that calls our [internal jwt auth](https://github.com/HHS/simpler-grants-gov/blob/main/api/src/auth/internal_jwt_auth.py) code and can generate a token. This is needed to allow the frontend folks to test/build an endpoint for PDF generation.
The script should be runnable via make, and we should put it in the test/lib folder. It just needs to generate a token that someone could copy paste to call the GET application form endpoint (which can take this token in).
See docs and screenshot of local usage.
> [Issue #5851] Create script for generating internal token

- frontend/src/components/search/SearchVersionTwo.tsx
Work for #5857
Bug exists where pills can end up without labels when messing around with opportunity statuses and agencies / top level agencies
Fixes bug by passing full list of agencies to pill list to ensure pills always have labels
Note that I was not reliably able to reproduce without messing with opportunity status, I was able to reproduce at least once. Not sure how / why, but this fix should handle whatever case that represents regardless
1. start a local server on main
2. visit http://localhost:3000/search?_ff=filterDrawerOn:true
3. select "archived" opportunity status filter
4. select "CDC ATSDR" agency filter
5. deselect "archived" opportunity status filter
6. _VERIFY_: an empty pill is present
7. restart local server on this branch
8. repeat steps 2 - 5
9. _VERIFY_: no empty …
> [Issue #5857] fix bug with empty pills by maintaining list of all agencies

- api/openapi.generated.yml
- api/src/api/application_alpha/application_schemas.py
- api/tests/src/api/applications/test_application_routes.py
Add form the the API schema for an application form
I thought we already did this, but it turns out we don't return the form from the application form endpoint. When talking with @doug-s-nava - realized the frontend was having to do a roundabout way of getting the form's schema on the app form page, this should help fix that weird logic to get it via a competition.
> [Unticketed] Add form schema to app form API model

- frontend/src/components/search/SearchResultsView.tsx
Work for #5818
Adds pagination beneath search results table
2. visit http://localhost:3000/search?_ff=searchDrawerOn:true
3. _VERIFY_: pagination appears at bottom of page beneath search results table
> [Issue #5818] add pagination beneath search results

- api/src/services/users/get_saved_opportunities.py
Instead of `selectinload("*")` when fetch saved opportunities, only fetch what we need.
This endpoint suddenly has a lot of traffic as anyone logged in calls this on search. This highlighted the bad performance of this endpoint with the worst requests taking 3 seconds:
This is almost certainly due to fetching way too much in the query. The `*` approach fetches every relationship from an opportunity which means we're currently fetching almost every table record connected to an opportunity. The response model only needs the opportunity and its current opportunity summary. There isn't much info that needs to be returned for this endpoint to work. This should massively reduce how long these requests take.
> [Unticketed] Adjust saved-opp query to fetch much less

- api/src/form_schema/forms/project_narrative_attachment.py
Work for #5699 
Gets the project narrative attachment form basically working
Note that there are still problems with validation and keeping track of uploaded documents that will be resolved later.
1. start a local frontend server on this branch
2. run `make volume-recreate db-seed-local populate-search-opportunities populate-search-agencies start` on /api
3. start an application as described in the readme (https://github.com/HHS/simpler-grants-gov/blob/16f5ca621c3ce1469d0a5b250efe52d6718ae28e/frontend/src/app/%5Blocale%5D/workspace/applications/application/%5BapplicationId%5D/README.md)
4. open the project narrative attachment form
5. click save
6. _VERIFY_: validation errors are returned
7. add multiple attachments
8. click save
9. _VERIFY_: it saves (validation errors are expected at …
> [Issue #5699] ui for project narrative attachment form

- frontend/next.config.js
- frontend/package.json
- frontend/src/app/[locale]/workspace/applications/application/[applicationId]/README.md
- frontend/src/components/Layout.tsx
- frontend/src/components/application/ApplicationFormsTable.tsx
- frontend/src/components/applyForm/ApplyForm.tsx
- frontend/src/components/applyForm/ApplyFormMessage.tsx
- frontend/src/components/applyForm/utils.tsx
- frontend/src/components/applyForm/widgets/FieldsetWidget.tsx
- frontend/src/components/opportunity/OpportunityDocuments.tsx
- frontend/src/components/opportunity/OpportunityDownload.tsx
- frontend/src/styles/_uswds-theme-custom-styles.scss
- frontend/tests/components/opportunity/OpportunityDownload.test.tsx
Work for #4281 
Fixes bug where internal anchor links were not taking the sticky header into account, and consequently putting the important linked stuff behind the header on scroll
I identified 4 places in the code where internal anchors were being used:
* the "jump to documents" link on opportunity detail
* application form validation warning links
* application form side nav links
* application submission validation warning links
If there are others, I missed them and they are not covered by this change
This also adds a readme file directing users how to access an application page, since that is a common path needed for validation, testing and development that is not very clear
Note that any future anchor links we add that do not fit into any of the 4 categories described above will …
> [Issue #4281] add page anchor scroll offset

- api/src/adapters/sam_gov/client.py
- api/src/task/sam_extracts/process_sam_extracts.py
- api/tests/src/task/sam_extracts/test_process_sam_extracts.py
Fixes for #5859
* Add a little more logging to extract file download to say which file it is downloading
* Fix logic for setting the processing status of a sam.gov extract so it actually gets set
Processing status wasn't getting set when run because we fetch the extract files in one transaction, and update it in a different one, so they aren't associated with the DB session in the latter case so the update doesn't do anything. Adding them to the DB session fixes this.
> [Issue #5859] Small fixes/adjustments to sam.gov processing

- api/openapi.generated.yml
- api/src/api/users/user_routes.py
- api/src/api/users/user_schemas.py
- api/src/services/users/rename_api_key.py
- api/tests/src/api/users/test_user_rename_api_key.py
- api/tests/src/services/users/test_rename_api_key.py
Fixes #5798
Added endpoint and utilities to rename an API key
> [Issue #5798] Add service to rename API keys from logged in user in DB

- frontend/src/components/applyForm/utils.tsx
- frontend/tests/components/applyForm/utils.test.tsx
Fixes #6016
This is a bit of a prerequisite for https://github.com/HHS/simpler-grants-gov/issues/5832
An issue exists where validation of conditionally required fields were coming back with false positives. By making sure we do not pass any form data up for fields that do not have data we can ensure that these false validation failures occur.
3. open the sf-LLL form
4. click save
5. _VALIDATE_: no validation errors are returned relating to the `prime_reporting_entity`
6. select "subawardee" as "entity type"
7. click save
5. _VALIDATE_: …
> [Issue #6016] fix conditional nested requires

- frontend/src/components/application/IncludeFormInSubmissionRadio.tsx
- frontend/tests/components/application/__snapshots__/ApplicationFormsTable.test.tsx.snap
Work for #6002
Fixes bug that made it impossible to effectively select application inclusion in a competition with multiple optional forms
1. make an additional form on the seeded pilot competition optional (set "IS_REQUIRED" to false in the competition_forms table)
2. start a local server on this branch using `npm run dev`
3. start an application using this [readme](https://github.com/HHS/simpler-grants-gov/blob/main/frontend/src/app/%5Blocale%5D/workspace/applications/application/%5BapplicationId%5D/README.md)
4. toggle application inclusion on and off for both optional forms
5. _VERIFY_: no weirdness or bugs
6. refresh
7. _VERIFY_: your inclusion selections are persisted
> [Issue #6002] fix issues with inclusion radio for multiple optional forms

- frontend/src/components/applyForm/ApplyFormMessage.tsx
unticketed
Fixes bug related to incorrect anchor links being set in form validation warnings
This bug may originate here, though I'm not positive https://github.com/HHS/simpler-grants-gov/pull/6070/files
3. open the sf424
4. click save
5. click the first validation warning link
6. _VERIFY_: link takes you to the correct field
> [unticketed] strip cruft from valdation field path

- frontend/src/app/[locale]/(print)/print/application/[applicationId]/form/[appFormId]/page.tsx
- frontend/src/components/applyForm/PrintForm.tsx
unticketed
Fixes bug where the print route for forms that have attachments fails due to lack of an AttachmentsProvider
1. visit a form page for a form with attachments
2. generate an internal api token
3. add the internal api token as X-SGG-Internal-Token header using mod header
4. load up something like this http://localhost:3000/print/application/2ddc1e3d-1c7f-45b3-a1a8-f7083220570a/form/6d0795bc-e733-4031-a063-b49417c759a0
5. _VERIFY_: page loads
> add attachments provider to form print view

- frontend/src/components/applyForm/utils.tsx
- frontend/src/components/applyForm/widgets/MultipleAttachmentUploadWidget.tsx
- frontend/tests/components/applyForm/utils.test.tsx
Fixes #6045 
Updates `flatFormDataToArray()` to return the correct errors for the upload widgets.
The updated form behavior:
We have an issue with array support. Currently arrays are supported through the budget form and the upload widget. They both want data in a different form, so the `flatFormDataToArray()` function returns an array of objects for the budget form or a array of strings for the upload widget. 
We currently don't support generic arrays. I created #6092 to address this.
> [Issue #6045] Update flatFormDataToArray and upload widget

- api/src/form_schema/forms/sf424.py
- frontend/src/components/applyForm/utils.tsx
- frontend/src/components/applyForm/widgets/RadioWidget.tsx
This is only a partial fix to: Delinquent Federal Debt [#6097](https://github.com/HHS/simpler-grants-gov/issues/6097)
I've added the Radio widget manually to the ui schema
it now displays, the YES / NO options
I tried to make it as type safe as possible
added some utils and helpers to work with the options that are returned/created 
This does not contain the validation portion. That will come in a second PR-
1. to run locally, you would need to `run npm run build && npm start`
2. `make remake-backend && docker compose up`
3. navigate to `search`
4. search for `pilot`
5. you should see an opportunity called `Local Pilot-equivalent Opportunity`
6. sign in
7. start new application
8. navigate to form table of the application
9. click Application for Federal Assistance (SF-424)
10. scroll …
> [Issue #6097]: Delinquent Federal Debt Radio button

- analytics/poetry.lock
- analytics/pyproject.toml
We're seeing migrations fail during deploy with an error message about importing the requests library. This tries
to fix that error by explicitly listing requests as a dependency
Fixes #6169 
- Explicitly adds `requests` to dependencies
PR #6176 resulted in a failed deployment after simply removing some unused dependencies. The logs seemed to display an error message about failure to import the `requests` library, even though this is listed in the `poetry.lock` file as a transitive dependency of several other direct dependencies.
As a test, I want to see if listing `requests` as a direct dependency fixes this error.
> [Issue #6169] Fix analytics migrations

- infra/api/app-config/env-config/scheduled_jobs.tf
Fixes #5976
Add terraform config to call `create-application-submission` nightly at 2AM EDT.
Is there a preference for what time of night this runs?
See TF applied once merged.
> [Issue #5976] Setup a schedule for the application zip creation job

- api/src/legacy_soap_api/soap_payload_handler.py
- api/tests/src/legacy_soap_api/test_legacy_soap_api_client.py
Fixes inconsistent XML element ordering between different environments, resulting in sporadic test failures.
Sort XML keys, adjust tests to account for ordering.
We ran into [unreproducible test failures](https://github.com/HHS/simpler-grants-gov/actions/runs/17497241102/job/49701142555) in nonprod due to inconsistent XML key ordering. This resolves it.
Ensure tests pass across deployment environments.
> [Unticketed] Fix inconsistent XML element ordering between different environments

- frontend/src/components/Layout.tsx
- frontend/src/components/user/OpportunitySaveUserControl.tsx
- frontend/src/services/auth/LoginModalProvider.tsx
- frontend/tests/components/user/OpportunitySaveUserControl.test.tsx
- frontend/tests/services/auth/LoginModalProvider.test.tsx
Partial Work for #5906 
Adds the ability for the site to reuse a single login modal with multiple triggers
This solves an issue where a page, such as the current search page, will load a separate modal for each trigger on the page
This:
* creates a context that can be used to control a single login modal
* implements that context on the search and opportunity pages
As the main reason to do this work now was to clean up the main modals on the search page, this doesn't implement the context for use across all usages of the login modal, that can be done in a later ticket.
2. visit http://localhost:3000/search?_ff=applyFormPrototypeOff:false
3. open developer console and search DOM for `.usa-modal`
4. _VERIFY_: you find 2 or maybe 3 …
> [Issue #5906] reuse login modal

- frontend/src/components/application/attachments/AttachmentsCardForm.tsx
Work for #6375 
Removes list of accepted file types for application attachments uploader
The `accept` attribute does not do much to prevent uploading any file you want, since there are workarounds in each browser, and it was causing confusion with users.
3. attempt to upload all kinds of files to the application
4. _VERIFY_: no impediment to uploading whatever you want
> [Issue #6375] remove application attachment file type filter

- frontend/.pa11yci-desktop.json
- frontend/.pa11yci-mobile.json
- frontend/tests/e2e/404.spec.ts
Fix for #4495 
Re-enables some tests that were skipped as a result of the next bug here, which has now been fixed https://github.com/vercel/next.js/issues/77512
This bug has been fixed for a while, so the user facing issue (title and other metadata not showing on the 404 page) fixed itself - this is just clean up of related tests in our system
1. _VERIFY_: all tests pass in CI
> [Isse #4495] revert next js metadata bug workarounds

- frontend/src/constants/defaultFeatureFlags.ts
- frontend/src/constants/environments.ts
- infra/frontend/app-config/env-config/environment_variables.tf
Fixes / Work for #6200 
Adds a 'userAdminOff' feature flag to control appearance of any new user / organization pages
1. the flag isn't set up to do anything yet, so this is really just a code review to make sure it looks right based on previous flag setups
> [Issue #6200] add userAdminOff flag

- api/src/form_schema/rule_processing/README.md
- api/src/form_schema/rule_processing/json_rule_field_population.py
- api/src/form_schema/rule_processing/json_rule_util.py
- api/tests/lib/data_factories.py
- api/tests/src/form_schema/forms/test_sf424.py
- api/tests/src/form_schema/rule_processing/conftest.py
- api/tests/src/form_schema/rule_processing/test_json_rule_field_population.py
- api/tests/src/form_schema/rule_processing/test_json_rule_util.py
Fixes  #6404
Adjust behavior of prepopulation when a value is null, by default the field should not be populated AND any existing value is removed.
Adjust some of our prepopulation logic to not let a field be null (opportunity number, opportunity title, and agency name) to avoid issues where a required field can't be populated
Add some additional tests to the SF424 validation pre-population behavior
Some prepopulation fields can be null as the field is not required, for example the competition title is a commonly nullable field. But our JSON schema doesn't like those fields being null, even if they're not required. Null != missing, missing is fine, null would require we change the type from `string` to `["string", "null"]` which is a much bigger change. Instead we'll change the default to …
> [Issue #6404] Fix prepopulation when value is null

- infra/modules/service/access_control.tf
Gives API ECS service permissions to hit API Gateway internal API
- New IAM policy attached to API ECS role
This PR provides the API ECS service the required permissions to hit the [internal API for API gateway](https://docs.aws.amazon.com/apigateway/latest/api/API_Operations.html)
This will be tested manually once the API code side PR is merged. We'll use an inline policy so it won't require this to be merged for it to work
> Give API ECS role API Gateway permissions

- frontend/src/components/applyForm/utils.ts
- frontend/src/components/applyForm/widgets/budget/budgetErrorLabels.ts
- frontend/tests/components/applyForm/utils.test.ts
Fixes / Work for #6440
Only a single activity line item with the activity title filled in is required in section A of the budget form
Currently if activity titles are not filled in, failed validation comes back for all activity titles. With this change, the activity title should be marked as invalid only if:
* there is other data in the line item, but the title is missing
* there is no data for any line items, and the activity title is in the first line item
3. open the budget form
4. save
5. _VERIFY_: the activity title box for the first …
> [Issue #6440] correctly mark failed validation for missing activity title when no activity line items are saved

- .github/ISSUE_TEMPLATE/4_internal_deliverable.yml
- .github/linters/documentation/ISSUE_BODY_LINTER.md
- .github/linters/scripts/lint-issue-body.sh
- .github/workflows/lint-deliverable-metrics.yml
Fixes #6271 and #6272 
This PR: 
* Extends the deliverable linter to post comments to GitHub issues
* Fixes logic for certain edge cases (e.g. status=null)
* Adds documentation to explain the deliverable linter and deliverable formatting expectations
* Updates deliverable issue template (used to create new deliverables) to link to the linter documentation 
This is a follow-up to https://github.com/HHS/simpler-grants-gov/pull/6417 
Trigger workflow manually from GitHub Actions page
> [Issue #6272] Update deliverable linter to post comments to GitHub 

- frontend/src/app/[locale]/(print)/print/application/[applicationId]/form/[appFormId]/page.tsx
- frontend/src/components/applyForm/ApplyForm.tsx
- frontend/src/components/applyForm/PrintForm.tsx
- frontend/src/components/applyForm/widgets/AttachmentUploadWidget.tsx
- frontend/src/components/applyForm/widgets/MultiAttachmentUploadList.tsx
- frontend/src/components/applyForm/widgets/MultipleAttachmentUploadWidget.tsx
- frontend/src/hooks/ApplicationAttachments.tsx
- frontend/src/i18n/messages/en/index.ts
Work for #6445 
Add attachment changed state tracking to parallel the form change that already pops the warning of navigating away with pending changes.
1. Checkout the branch
2. Disable strict mode in Next config
3. Run `npm run dev`
4. Sign in with one_org_user
5. Go to the Budget Narrative Attachment Form for an Application 
6. Ensure there is nothing uploaded, delete and Save if there is.  And refresh the page.
7. Upload a file but don't save
8. Try to navigate away and confirm you get the warning "You have unsaved changes or attachments that will be lost if you click OK"
9. Click cancel
10. Save
11. Try to navigate away (you should get no warning)
12. Go back to the form
13. Remove the attachment but don't save
14. Try to navigate away and confirm you get the warning "You have …
> [Issue #6445] Warn to save after an attachment is deleted

- .github/linters/scripts/inherit-parent-deliverable.sh
Fixes a bug in how the deliverable option ID was passed to one of our linter scripts which caused it to fail when the option ID looked like a number (i.e. no alpha characters)
- Switches flag passing option ID value to `--raw-field` to preserve the escaping which makes it a string
- Switches to the more verbose (and clear) `--field` and `--raw-field` instead of (`-F` and `-f` respectively)
This error was flagged by @chris-kuryak after he noticed this GitHub action failed when he was creating some issues. It only failed on issues created for the "Scale apply user workflow *" deliverable because that option ID doesn't contain any alpha characters (`35970549`) and the gh CLI was parsing it as a number instead of a string even when escaping it with quotes. …
> [No ticket] Fix inherit parent metadata linter

- api/src/legacy_soap_api/legacy_soap_api_routes.py
- api/src/legacy_soap_api/legacy_soap_api_utils.py
- api/tests/fixtures/legacy_soap_api/grantors/get_application_request.xml
- api/tests/fixtures/legacy_soap_api/grantors/get_application_zip_request.xml
- api/tests/src/legacy_soap_api/test_legacy_soap_api_routes.py
- api/tests/src/legacy_soap_api/test_legacy_soap_api_utils.py
If it is Simpler format, skip sending request to Grants.gov
Added a check to see if the incoming request meets the following criteria:
- It is either GetApplicationZip or GetApplication
- It has a GrantsGovTrackingNumber that starts with an 8 or a 9
If both those critera are met, do not forward the request on to grants.gov. 
Hitting grants.gov can be slow, so if we know for sure the data is not in grants.gov we won't bother actually making the request.
> [Issue #6359] Skip sending to grants.gov if simpler formatted id

- frontend/src/services/fetch/fetchers/applicationFetcher.ts
Work for #6511  
At some point we had a hard coded default to include any form that the user touched at some point. Removing that for now as that's not the desired behavior.
> [Issue #6511] Don't always set the form to be included in the submission 

- api/tests/lib/seed_orgs_and_users.py
When creating users in our seed script, give them some API keys.
As we switch over to the new API key approach, we can't rely on our statically defined API key for hitting the local DB. We might want to have a generic statically defined key (especially when the frontend switches over), but for now we can just add it to the users we're already generating in our seed script.
Running `make db-seed-local` will create the keys, you can copy one of them any hit an endpoint like GET opportunity uneventfully with it. The `key_id` field we set is what you put in the auth header.
> [Unticketed] Give our local test users API keys by default

- api/poetry.lock
- api/pyproject.toml
- api/src/task/__init__.py
- api/src/task/forms/README.md
- api/src/task/forms/form_task_shared.py
- api/src/task/forms/list_forms_task.py
- api/src/task/forms/update_form_task.py
- api/tests/src/task/forms/conftest.py
- api/tests/src/task/forms/test_form_task_shared.py
- api/tests/src/task/forms/test_list_forms_task.py
- api/tests/src/task/forms/test_update_form_task.py
Fixes  #6492  
* Creates a script to list forms in a given environment and tell you whether they are up-to-date
* Remove the dry-run/diff logic from the update-form script (made redundant by this script)
* A bunch of refactoring to move code shared by both scripts to a central location
The update-form script has been very helpful in checking forms and updating them, but is a bit clunky to check multiple forms. So, I made a new script that just checks everything and makes it even less effort to update forms by giving you an output.
The goal of this script is to generally run this before the update-form script, then copy the output to make it so you don't even need to find commands to run.
First make sure to run `make db-seed-local` so all of your forms locally are up-to-date.
If you make …
> [Issue #6492] Create a script to list the status of forms in an env

- frontend/src/app/[locale]/(base)/search/page.tsx
- frontend/src/app/[locale]/(base)/user/account/actions.ts
- frontend/src/app/[locale]/(base)/user/account/page.tsx
- frontend/src/app/[locale]/(base)/user/layout.tsx
- frontend/src/components/ConditionalFormActionError.tsx
- frontend/src/components/RequiredFieldIndicator.tsx
- frontend/src/components/user/UserProfileForm.tsx
- frontend/src/components/workspace/StartApplicationModal/IneligibleStartApplicationModal.tsx
- frontend/src/components/workspace/StartApplicationModal/StartApplicationDescription.tsx
- frontend/src/components/workspace/StartApplicationModal/StartApplicationInputs.tsx
- frontend/src/components/workspace/StartApplicationModal/StartApplicationModal.tsx
- frontend/src/components/workspace/StartApplicationModal/StartApplicationModalControl.tsx
- frontend/src/i18n/messages/en/index.ts
- frontend/src/services/fetch/fetchers/userFetcher.ts
- frontend/src/types/UserTypes.ts
- frontend/src/types/userTypes.ts
- frontend/src/utils/testing/fixtures.ts
- frontend/tests/api/user/organizations/route.test.ts
- frontend/tests/components/ConditionalFormActionError.test.tsx
- frontend/tests/components/RequiredFieldIndicator.test.tsx
- frontend/tests/components/__snapshots__/ConditionalFormActionError.test.tsx.snap
- frontend/tests/components/__snapshots__/RequiredFieldIndicator.test.tsx.snap
- frontend/tests/components/user/UserProfileForm.test.tsx
- frontend/tests/components/user/__snapshots__/UserProfileForm.test.tsx.snap
- frontend/tests/pages/user/account/actions.test.ts
- frontend/tests/utils/getRoutes.test.ts
Work for #6522
Depends on https://github.com/HHS/simpler-grants-gov/pull/6521 
connects user profile form to API to fetch and save data
also adds success and API error messaging
2. visit http://localhost:3000/user/account
3. log in
4. _VERIFY_: form is blank
5. fill in the form
6. save
7. _VERIFY_: success message is showed
8. _VERIFY_: your updates persist in the form
9. refresh page
10. _VERIFY_: your updates persist in the form
> [Issue #6522] wire up account page

- infra/frontend/app-config/env-config/environment_variables.tf
Fixes bug introduced from previous PR
- Fixes the naming for env var for API gateway token in frontend
In my previous PR, I copied pasted the object to add my env var, and I forgot to change the name. This caused my param to overwrite the API JWT token, causing the frontend to fail
> Fix Frontend env naming for API Gateway

- api/src/task/sam_extracts/sam_extract_cli.py
- api/src/task/sam_extracts/setup_lower_env_sam_extracts.py
- api/tests/src/task/sam_extracts/test_setup_lower_env_sam_extracts.py
- infra/api/app-config/env-config/scheduled_jobs.tf
Fixes #6536
Create a new task that will automatically generate a sam.gov extract file in our lower environments giving everyone their own personal organization.
This solves two problems in one:
* Sam.gov doesn't generate extracts in the lower environment that we can process
* In dev/staging, it's really tedious to manually setup orgs for folks. This'll give every user an automatic organization. It does not prevent us from making other orgs, or even from folks inviting to each others orgs.
This task is only meant to run in our lower environments, by default it is off, I modified the job to only enable it in dev/staging AND the task will outright fail if you try to run in prod/training.
If you run `make db-seed-local`, a few users will be created. You can then run this by doing something …
> [Issue #6536] Create a task that automatically makes sam.gov extracts from users in lower envs

- .github/linters/coplanning/README.md
- .github/linters/coplanning/fider.py
- .github/linters/coplanning/run.py
- .github/linters/coplanning/utils.py
- .github/workflows/coplanning-sync-fider-to-gh.yml
- .github/workflows/coplanning-sync-gh-to-fider.yml
Updates the GitHub to Fider Co-planning sync script to allow us to populate Fider posts with multiple sections from the GitHub issue body.
Fixes #6563 
- Fixes a few small type checking warnings
- Adds support for passing multiple sections to the `--issue-sections` flag
- Updates the CI script to use all of the sections in the GitHub issue template for co-planning proposals
In the "Internal - Co-planning Proposal" issue template, we replaced the "Summary" section with a new set of sections that we want to be copied over. The previous syncing pattern only allowed us to copy over a single section (or would default to the entire ticket if that section wasn't found).
This new pattern allows us to copy over multiple sections and includes any matching sections in the Fider post. If no matching …
> [Issue #6563] Update co-planning sync script

- frontend/src/components/application/ApplicationContainer.tsx
- frontend/tests/components/application/ApplicationContainer.test.tsx
Fixes #6507  
Refreshes server-side data to get updated application_status from API to Hide Submit Button After Submission/Acceptance
after submission
after submission revisiting/refreshing
> [Issue #6507] hide submit application button after application has been submitted

- frontend/src/components/application/InformationCard.tsx
- frontend/tests/components/application/InformationCard.test.tsx
Fixes #6207 
Prevent user from editing application filinging name after submitting the application
We don't have acceptance implemented yet
> [Issue #6207] Remove ability to change application name after successful submission

- frontend/src/app/[locale]/(base)/workspace/applications/application/[applicationId]/form/[appFormId]/page.tsx
- frontend/src/components/applyForm/ApplyForm.tsx
Work for #6186
Adds css to make the div containing the form save button sticky at the top of the form
Without design guidance I'm not sure if this is the best implementation, but it gets the job done for now
3. open the sf424 form
4. scroll the form down
5. _VERIFY_: save button stays at top of form during scroll
> [Issue #6186] keep form save in view

- frontend/src/app/[locale]/(print)/print/application/[applicationId]/form/[appFormId]/page.tsx
- frontend/src/components/applyForm/types.ts
- frontend/src/components/applyForm/utils.ts
- frontend/src/components/applyForm/widgets/PrintAttachmentWidget.tsx
- frontend/src/components/applyForm/widgets/PrintWidget.tsx
- frontend/src/components/applyForm/widgets/Widgets.tsx
- frontend/tests/components/applyForm/PrintForm.test.tsx
- frontend/tests/components/applyForm/utils.test.ts
- frontend/tests/components/applyForm/widgets/PrintAttachmentWidget.test.tsx
- frontend/tests/components/applyForm/widgets/PrintWidget.test.tsx
Fixes / Work for #6544 #6138 #6141 #6142
Creates new print widgets and print component to make the print view look better. Updates uiSchema for print to display printed versions. Ignores `multiField`, so no update to budget forms.
https://www.figma.com/design/zPlDWcYM396szw2yL3UXvk/Simpler-Grants-2025?node-id=5219-57461&m=dev
1. Create a new application, fill out the forms.
2. Create a token in the API folder `make generate-internal-token`
3. Replace `workspace/applications` with `print` in form URL
4. View the form (I use https://modheader.com/) to add the internal token so I can see it in the web browser
> [Issue #6544] Update print page with print widgets
